//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

using System;

#if NET7_0_OR_GREATER
using System.Numerics;
#endif

#nullable enable

namespace UnitsNet.NumberExtensions.NumberToThermalTransmitance
{
    /// <summary>
    /// A number to ThermalTransmitance Extensions
    /// </summary>
    public static class NumberToThermalTransmitanceExtensions
    {
        /// <inheritdoc cref="ThermalTransmitance.FromBtusPerHourSquareFeetDegreeFahrenheit(QuantityValue)" />
        public static ThermalTransmitance BtusPerHourSquareFeetDegreeFahrenheit<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
            => ThermalTransmitance.FromBtusPerHourSquareFeetDegreeFahrenheit(QuantityValue.CreateChecked(value));
#else
            , IConvertible
            => ThermalTransmitance.FromBtusPerHourSquareFeetDegreeFahrenheit(value.ToQuantityValue());
#endif

        /// <inheritdoc cref="ThermalTransmitance.FromKilocaloriesPerSquareCentimeterHourDegreeCelsius(QuantityValue)" />
        public static ThermalTransmitance KilocaloriesPerSquareCentimeterHourDegreeCelsius<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
            => ThermalTransmitance.FromKilocaloriesPerSquareCentimeterHourDegreeCelsius(QuantityValue.CreateChecked(value));
#else
            , IConvertible
            => ThermalTransmitance.FromKilocaloriesPerSquareCentimeterHourDegreeCelsius(value.ToQuantityValue());
#endif

        /// <inheritdoc cref="ThermalTransmitance.FromKilowattsPerSquareMeterKelvin(QuantityValue)" />
        public static ThermalTransmitance KilowattsPerSquareMeterKelvin<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
            => ThermalTransmitance.FromKilowattsPerSquareMeterKelvin(QuantityValue.CreateChecked(value));
#else
            , IConvertible
            => ThermalTransmitance.FromKilowattsPerSquareMeterKelvin(value.ToQuantityValue());
#endif

        /// <inheritdoc cref="ThermalTransmitance.FromWattsPerSquareCentimeterKelvin(QuantityValue)" />
        public static ThermalTransmitance WattsPerSquareCentimeterKelvin<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
            => ThermalTransmitance.FromWattsPerSquareCentimeterKelvin(QuantityValue.CreateChecked(value));
#else
            , IConvertible
            => ThermalTransmitance.FromWattsPerSquareCentimeterKelvin(value.ToQuantityValue());
#endif

        /// <inheritdoc cref="ThermalTransmitance.FromWattsPerSquareMeterDegreeCelsius(QuantityValue)" />
        public static ThermalTransmitance WattsPerSquareMeterDegreeCelsius<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
            => ThermalTransmitance.FromWattsPerSquareMeterDegreeCelsius(QuantityValue.CreateChecked(value));
#else
            , IConvertible
            => ThermalTransmitance.FromWattsPerSquareMeterDegreeCelsius(value.ToQuantityValue());
#endif

        /// <inheritdoc cref="ThermalTransmitance.FromWattsPerSquareMeterKelvin(QuantityValue)" />
        public static ThermalTransmitance WattsPerSquareMeterKelvin<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
            => ThermalTransmitance.FromWattsPerSquareMeterKelvin(QuantityValue.CreateChecked(value));
#else
            , IConvertible
            => ThermalTransmitance.FromWattsPerSquareMeterKelvin(value.ToQuantityValue());
#endif

        /// <inheritdoc cref="ThermalTransmitance.FromWattsPerSquareMillimeterKelvin(QuantityValue)" />
        public static ThermalTransmitance WattsPerSquareMillimeterKelvin<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
            => ThermalTransmitance.FromWattsPerSquareMillimeterKelvin(QuantityValue.CreateChecked(value));
#else
            , IConvertible
            => ThermalTransmitance.FromWattsPerSquareMillimeterKelvin(value.ToQuantityValue());
#endif

    }
}
