//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

using System;

#if NET7_0_OR_GREATER
using System.Numerics;
#endif

#nullable enable

namespace UnitsNet.NumberExtensions.NumberToThermalTransmittance
{
    /// <summary>
    /// A number to ThermalTransmittance Extensions
    /// </summary>
    public static class NumberToThermalTransmittanceExtensions
    {
        /// <inheritdoc cref="ThermalTransmittance.FromBtusPerHourSquareFeetDegreeFahrenheit(QuantityValue)" />
        public static ThermalTransmittance BtusPerHourSquareFeetDegreeFahrenheit<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
            => ThermalTransmittance.FromBtusPerHourSquareFeetDegreeFahrenheit(QuantityValue.CreateChecked(value));
#else
            , IConvertible
            => ThermalTransmittance.FromBtusPerHourSquareFeetDegreeFahrenheit(value.ToQuantityValue());
#endif

        /// <inheritdoc cref="ThermalTransmittance.FromKilocaloriesPerSquareCentimeterHourDegreeCelsius(QuantityValue)" />
        public static ThermalTransmittance KilocaloriesPerSquareCentimeterHourDegreeCelsius<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
            => ThermalTransmittance.FromKilocaloriesPerSquareCentimeterHourDegreeCelsius(QuantityValue.CreateChecked(value));
#else
            , IConvertible
            => ThermalTransmittance.FromKilocaloriesPerSquareCentimeterHourDegreeCelsius(value.ToQuantityValue());
#endif

        /// <inheritdoc cref="ThermalTransmittance.FromKilowattsPerSquareMeterKelvin(QuantityValue)" />
        public static ThermalTransmittance KilowattsPerSquareMeterKelvin<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
            => ThermalTransmittance.FromKilowattsPerSquareMeterKelvin(QuantityValue.CreateChecked(value));
#else
            , IConvertible
            => ThermalTransmittance.FromKilowattsPerSquareMeterKelvin(value.ToQuantityValue());
#endif

        /// <inheritdoc cref="ThermalTransmittance.FromWattsPerSquareCentimeterKelvin(QuantityValue)" />
        public static ThermalTransmittance WattsPerSquareCentimeterKelvin<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
            => ThermalTransmittance.FromWattsPerSquareCentimeterKelvin(QuantityValue.CreateChecked(value));
#else
            , IConvertible
            => ThermalTransmittance.FromWattsPerSquareCentimeterKelvin(value.ToQuantityValue());
#endif

        /// <inheritdoc cref="ThermalTransmittance.FromWattsPerSquareMeterDegreeCelsius(QuantityValue)" />
        public static ThermalTransmittance WattsPerSquareMeterDegreeCelsius<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
            => ThermalTransmittance.FromWattsPerSquareMeterDegreeCelsius(QuantityValue.CreateChecked(value));
#else
            , IConvertible
            => ThermalTransmittance.FromWattsPerSquareMeterDegreeCelsius(value.ToQuantityValue());
#endif

        /// <inheritdoc cref="ThermalTransmittance.FromWattsPerSquareMeterKelvin(QuantityValue)" />
        public static ThermalTransmittance WattsPerSquareMeterKelvin<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
            => ThermalTransmittance.FromWattsPerSquareMeterKelvin(QuantityValue.CreateChecked(value));
#else
            , IConvertible
            => ThermalTransmittance.FromWattsPerSquareMeterKelvin(value.ToQuantityValue());
#endif

        /// <inheritdoc cref="ThermalTransmittance.FromWattsPerSquareMillimeterKelvin(QuantityValue)" />
        public static ThermalTransmittance WattsPerSquareMillimeterKelvin<T>(this T value)
            where T : notnull
#if NET7_0_OR_GREATER
            , INumber<T>
            => ThermalTransmittance.FromWattsPerSquareMillimeterKelvin(QuantityValue.CreateChecked(value));
#else
            , IConvertible
            => ThermalTransmittance.FromWattsPerSquareMillimeterKelvin(value.ToQuantityValue());
#endif

    }
}
