//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading;
using UnitsNet.InternalHelpers;
using UnitsNet.Tests.Helpers;
using UnitsNet.Tests.TestsBase;
using UnitsNet.Units;
using Xunit;

// Disable build warning CS1718: Comparison made to same variable; did you mean to compare something else?
#pragma warning disable 1718

// ReSharper disable once CheckNamespace
namespace UnitsNet.Tests
{
    /// <summary>
    /// Test of ThermalTransmitance.
    /// </summary>
// ReSharper disable once PartialTypeWithSinglePart
    public abstract partial class ThermalTransmitanceTestsBase : QuantityTestsBase
    {
        protected abstract double BtusPerHourSquareFeetDegreeFahrenheitInOneKilowattPerSquareMeterKelvin { get; }
        protected abstract double KilocaloriesPerSquareCentimeterHourDegreeCelsiusInOneKilowattPerSquareMeterKelvin { get; }
        protected abstract double KilowattsPerSquareMeterKelvinInOneKilowattPerSquareMeterKelvin { get; }
        protected abstract double WattsPerSquareCentimeterKelvinInOneKilowattPerSquareMeterKelvin { get; }
        protected abstract double WattsPerSquareMeterDegreeCelsiusInOneKilowattPerSquareMeterKelvin { get; }
        protected abstract double WattsPerSquareMeterKelvinInOneKilowattPerSquareMeterKelvin { get; }
        protected abstract double WattsPerSquareMillimeterKelvinInOneKilowattPerSquareMeterKelvin { get; }

// ReSharper disable VirtualMemberNeverOverriden.Global
        protected virtual double BtusPerHourSquareFeetDegreeFahrenheitTolerance { get { return 1e-5; } }
        protected virtual double KilocaloriesPerSquareCentimeterHourDegreeCelsiusTolerance { get { return 1e-5; } }
        protected virtual double KilowattsPerSquareMeterKelvinTolerance { get { return 1e-5; } }
        protected virtual double WattsPerSquareCentimeterKelvinTolerance { get { return 1e-5; } }
        protected virtual double WattsPerSquareMeterDegreeCelsiusTolerance { get { return 1e-5; } }
        protected virtual double WattsPerSquareMeterKelvinTolerance { get { return 1e-5; } }
        protected virtual double WattsPerSquareMillimeterKelvinTolerance { get { return 1e-5; } }
// ReSharper restore VirtualMemberNeverOverriden.Global

        protected (double UnitsInBaseUnit, double Tolerence) GetConversionFactor(ThermalTransmitanceUnit unit)
        {
            return unit switch
            {
                ThermalTransmitanceUnit.BtuPerHourSquareFeetDegreeFahrenheit => (BtusPerHourSquareFeetDegreeFahrenheitInOneKilowattPerSquareMeterKelvin, BtusPerHourSquareFeetDegreeFahrenheitTolerance),
                ThermalTransmitanceUnit.KilocaloriePerSquareCentimeterHourDegreeCelsius => (KilocaloriesPerSquareCentimeterHourDegreeCelsiusInOneKilowattPerSquareMeterKelvin, KilocaloriesPerSquareCentimeterHourDegreeCelsiusTolerance),
                ThermalTransmitanceUnit.KilowattPerSquareMeterKelvin => (KilowattsPerSquareMeterKelvinInOneKilowattPerSquareMeterKelvin, KilowattsPerSquareMeterKelvinTolerance),
                ThermalTransmitanceUnit.WattPerSquareCentimeterKelvin => (WattsPerSquareCentimeterKelvinInOneKilowattPerSquareMeterKelvin, WattsPerSquareCentimeterKelvinTolerance),
                ThermalTransmitanceUnit.WattPerSquareMeterDegreeCelsius => (WattsPerSquareMeterDegreeCelsiusInOneKilowattPerSquareMeterKelvin, WattsPerSquareMeterDegreeCelsiusTolerance),
                ThermalTransmitanceUnit.WattPerSquareMeterKelvin => (WattsPerSquareMeterKelvinInOneKilowattPerSquareMeterKelvin, WattsPerSquareMeterKelvinTolerance),
                ThermalTransmitanceUnit.WattPerSquareMillimeterKelvin => (WattsPerSquareMillimeterKelvinInOneKilowattPerSquareMeterKelvin, WattsPerSquareMillimeterKelvinTolerance),
                _ => throw new NotSupportedException()
            };
        }

        public static IEnumerable<object[]> UnitTypes = new List<object[]>
        {
            new object[] { ThermalTransmitanceUnit.BtuPerHourSquareFeetDegreeFahrenheit },
            new object[] { ThermalTransmitanceUnit.KilocaloriePerSquareCentimeterHourDegreeCelsius },
            new object[] { ThermalTransmitanceUnit.KilowattPerSquareMeterKelvin },
            new object[] { ThermalTransmitanceUnit.WattPerSquareCentimeterKelvin },
            new object[] { ThermalTransmitanceUnit.WattPerSquareMeterDegreeCelsius },
            new object[] { ThermalTransmitanceUnit.WattPerSquareMeterKelvin },
            new object[] { ThermalTransmitanceUnit.WattPerSquareMillimeterKelvin },
        };

        [Fact]
        public void DefaultCtor_ReturnsQuantityWithZeroValueAndBaseUnit()
        {
            var quantity = new ThermalTransmitance();
            Assert.Equal(0, quantity.Value);
            Assert.Equal(ThermalTransmitanceUnit.KilowattPerSquareMeterKelvin, quantity.Unit);
        }

        [Fact]
        public void Ctor_WithInfinityValue_DoNotThrowsArgumentException()
        {
            var exception1 = Record.Exception(() => new ThermalTransmitance(double.PositiveInfinity, ThermalTransmitanceUnit.KilowattPerSquareMeterKelvin));
            var exception2 = Record.Exception(() => new ThermalTransmitance(double.NegativeInfinity, ThermalTransmitanceUnit.KilowattPerSquareMeterKelvin));

            Assert.Null(exception1);
            Assert.Null(exception2);
        }

        [Fact]
        public void Ctor_WithNaNValue_DoNotThrowsArgumentException()
        {
            var exception = Record.Exception(() => new ThermalTransmitance(double.NaN, ThermalTransmitanceUnit.KilowattPerSquareMeterKelvin));

            Assert.Null(exception);
        }

        [Fact]
        public void Ctor_NullAsUnitSystem_ThrowsArgumentNullException()
        {
            Assert.Throws<ArgumentNullException>(() => new ThermalTransmitance(value: 1, unitSystem: null));
        }

        [Fact]
        public virtual void Ctor_SIUnitSystem_ReturnsQuantityWithSIUnits()
        {
            var quantity = new ThermalTransmitance(value: 1, unitSystem: UnitSystem.SI);
            Assert.Equal(1, quantity.Value);
            Assert.True(quantity.QuantityInfo[quantity.Unit].BaseUnits.IsSubsetOf(UnitSystem.SI.BaseUnits));
        }

        [Fact]
        public void Ctor_UnitSystem_ThrowsArgumentExceptionIfNotSupported()
        {
            var unsupportedUnitSystem = new UnitSystem(UnsupportedBaseUnits);
            Assert.Throws<ArgumentException>(() => new ThermalTransmitance(value: 1, unitSystem: unsupportedUnitSystem));
        }

        [Fact]
        public void ThermalTransmitance_QuantityInfo_ReturnsQuantityInfoDescribingQuantity()
        {
            ThermalTransmitanceUnit[] unitsOrderedByName = EnumHelper.GetValues<ThermalTransmitanceUnit>().OrderBy(x => x.ToString(), StringComparer.OrdinalIgnoreCase).ToArray();
            var quantity = new ThermalTransmitance(1, ThermalTransmitanceUnit.KilowattPerSquareMeterKelvin);

            QuantityInfo<ThermalTransmitance, ThermalTransmitanceUnit> quantityInfo = quantity.QuantityInfo;

            Assert.Equal("ThermalTransmitance", quantityInfo.Name);
            Assert.Equal(ThermalTransmitance.Zero, quantityInfo.Zero);
            Assert.Equal(ThermalTransmitance.BaseUnit, quantityInfo.BaseUnitInfo.Value);
            Assert.Equal(unitsOrderedByName, quantityInfo.Units);
            Assert.Equal(unitsOrderedByName, quantityInfo.UnitInfos.Select(x => x.Value));
            Assert.Equal(ThermalTransmitance.Info, quantityInfo);
            Assert.Equal(quantityInfo, ((IQuantity)quantity).QuantityInfo);
            Assert.Equal(quantityInfo, ((IQuantity<ThermalTransmitanceUnit>)quantity).QuantityInfo);
        }

        [Fact]
        public void ThermalTransmitanceInfo_CreateWithCustomUnitInfos()
        {
            ThermalTransmitanceUnit[] expectedUnits = [ThermalTransmitanceUnit.KilowattPerSquareMeterKelvin];

            ThermalTransmitance.ThermalTransmitanceInfo quantityInfo = ThermalTransmitance.ThermalTransmitanceInfo.CreateDefault(mappings => mappings.SelectUnits(expectedUnits));

            Assert.Equal("ThermalTransmitance", quantityInfo.Name);
            Assert.Equal(ThermalTransmitance.Zero, quantityInfo.Zero);
            Assert.Equal(ThermalTransmitance.BaseUnit, quantityInfo.BaseUnitInfo.Value);
            Assert.Equal(expectedUnits, quantityInfo.Units);
            Assert.Equal(expectedUnits, quantityInfo.UnitInfos.Select(x => x.Value));
        }

        [Fact]
        public void KilowattPerSquareMeterKelvinToThermalTransmitanceUnits()
        {
            ThermalTransmitance kilowattpersquaremeterkelvin = ThermalTransmitance.FromKilowattsPerSquareMeterKelvin(1);
            AssertEx.EqualTolerance(BtusPerHourSquareFeetDegreeFahrenheitInOneKilowattPerSquareMeterKelvin, kilowattpersquaremeterkelvin.BtusPerHourSquareFeetDegreeFahrenheit, BtusPerHourSquareFeetDegreeFahrenheitTolerance);
            AssertEx.EqualTolerance(KilocaloriesPerSquareCentimeterHourDegreeCelsiusInOneKilowattPerSquareMeterKelvin, kilowattpersquaremeterkelvin.KilocaloriesPerSquareCentimeterHourDegreeCelsius, KilocaloriesPerSquareCentimeterHourDegreeCelsiusTolerance);
            AssertEx.EqualTolerance(KilowattsPerSquareMeterKelvinInOneKilowattPerSquareMeterKelvin, kilowattpersquaremeterkelvin.KilowattsPerSquareMeterKelvin, KilowattsPerSquareMeterKelvinTolerance);
            AssertEx.EqualTolerance(WattsPerSquareCentimeterKelvinInOneKilowattPerSquareMeterKelvin, kilowattpersquaremeterkelvin.WattsPerSquareCentimeterKelvin, WattsPerSquareCentimeterKelvinTolerance);
            AssertEx.EqualTolerance(WattsPerSquareMeterDegreeCelsiusInOneKilowattPerSquareMeterKelvin, kilowattpersquaremeterkelvin.WattsPerSquareMeterDegreeCelsius, WattsPerSquareMeterDegreeCelsiusTolerance);
            AssertEx.EqualTolerance(WattsPerSquareMeterKelvinInOneKilowattPerSquareMeterKelvin, kilowattpersquaremeterkelvin.WattsPerSquareMeterKelvin, WattsPerSquareMeterKelvinTolerance);
            AssertEx.EqualTolerance(WattsPerSquareMillimeterKelvinInOneKilowattPerSquareMeterKelvin, kilowattpersquaremeterkelvin.WattsPerSquareMillimeterKelvin, WattsPerSquareMillimeterKelvinTolerance);
        }

        [Fact]
        public void From_ValueAndUnit_ReturnsQuantityWithSameValueAndUnit()
        {
            Assert.All(EnumHelper.GetValues<ThermalTransmitanceUnit>(), unit =>
            {
                var quantity = ThermalTransmitance.From(1, unit);
                Assert.Equal(1, quantity.Value);
                Assert.Equal(unit, quantity.Unit);
            });
        }

        [Fact]
        public void FromKilowattsPerSquareMeterKelvin_WithInfinityValue_DoNotThrowsArgumentException()
        {
            var exception1 = Record.Exception(() => ThermalTransmitance.FromKilowattsPerSquareMeterKelvin(double.PositiveInfinity));
            var exception2 = Record.Exception(() => ThermalTransmitance.FromKilowattsPerSquareMeterKelvin(double.NegativeInfinity));

            Assert.Null(exception1);
            Assert.Null(exception2);
        }

        [Fact]
        public void FromKilowattsPerSquareMeterKelvin_WithNanValue_DoNotThrowsArgumentException()
        {
            var exception = Record.Exception(() => ThermalTransmitance.FromKilowattsPerSquareMeterKelvin(double.NaN));

            Assert.Null(exception);
        }

        [Fact]
        public void As()
        {
            var kilowattpersquaremeterkelvin = ThermalTransmitance.FromKilowattsPerSquareMeterKelvin(1);
            AssertEx.EqualTolerance(BtusPerHourSquareFeetDegreeFahrenheitInOneKilowattPerSquareMeterKelvin, kilowattpersquaremeterkelvin.As(ThermalTransmitanceUnit.BtuPerHourSquareFeetDegreeFahrenheit), BtusPerHourSquareFeetDegreeFahrenheitTolerance);
            AssertEx.EqualTolerance(KilocaloriesPerSquareCentimeterHourDegreeCelsiusInOneKilowattPerSquareMeterKelvin, kilowattpersquaremeterkelvin.As(ThermalTransmitanceUnit.KilocaloriePerSquareCentimeterHourDegreeCelsius), KilocaloriesPerSquareCentimeterHourDegreeCelsiusTolerance);
            AssertEx.EqualTolerance(KilowattsPerSquareMeterKelvinInOneKilowattPerSquareMeterKelvin, kilowattpersquaremeterkelvin.As(ThermalTransmitanceUnit.KilowattPerSquareMeterKelvin), KilowattsPerSquareMeterKelvinTolerance);
            AssertEx.EqualTolerance(WattsPerSquareCentimeterKelvinInOneKilowattPerSquareMeterKelvin, kilowattpersquaremeterkelvin.As(ThermalTransmitanceUnit.WattPerSquareCentimeterKelvin), WattsPerSquareCentimeterKelvinTolerance);
            AssertEx.EqualTolerance(WattsPerSquareMeterDegreeCelsiusInOneKilowattPerSquareMeterKelvin, kilowattpersquaremeterkelvin.As(ThermalTransmitanceUnit.WattPerSquareMeterDegreeCelsius), WattsPerSquareMeterDegreeCelsiusTolerance);
            AssertEx.EqualTolerance(WattsPerSquareMeterKelvinInOneKilowattPerSquareMeterKelvin, kilowattpersquaremeterkelvin.As(ThermalTransmitanceUnit.WattPerSquareMeterKelvin), WattsPerSquareMeterKelvinTolerance);
            AssertEx.EqualTolerance(WattsPerSquareMillimeterKelvinInOneKilowattPerSquareMeterKelvin, kilowattpersquaremeterkelvin.As(ThermalTransmitanceUnit.WattPerSquareMillimeterKelvin), WattsPerSquareMillimeterKelvinTolerance);
        }

        [Fact]
        public virtual void BaseUnit_HasSIBase()
        {
            var baseUnitInfo = ThermalTransmitance.Info.BaseUnitInfo;
            Assert.True(baseUnitInfo.BaseUnits.IsSubsetOf(UnitSystem.SI.BaseUnits));
        }

        [Fact]
        public virtual void As_UnitSystem_SI_ReturnsQuantityInSIUnits()
        {
            var quantity = new ThermalTransmitance(value: 1, unit: ThermalTransmitance.BaseUnit);
            var expectedValue = quantity.As(ThermalTransmitance.Info.GetDefaultUnit(UnitSystem.SI));

            var convertedValue = quantity.As(UnitSystem.SI);

            Assert.Equal(expectedValue, convertedValue);
        }

        [Fact]
        public void As_UnitSystem_ThrowsArgumentNullExceptionIfNull()
        {
            var quantity = new ThermalTransmitance(value: 1, unit: ThermalTransmitance.BaseUnit);
            UnitSystem nullUnitSystem = null!;
            Assert.Throws<ArgumentNullException>(() => quantity.As(nullUnitSystem));
        }

        [Fact]
        public void As_UnitSystem_ThrowsArgumentExceptionIfNotSupported()
        {
            var quantity = new ThermalTransmitance(value: 1, unit: ThermalTransmitance.BaseUnit);
            var unsupportedUnitSystem = new UnitSystem(UnsupportedBaseUnits);
            Assert.Throws<ArgumentException>(() => quantity.As(unsupportedUnitSystem));
        }

        [Fact]
        public virtual void ToUnit_UnitSystem_SI_ReturnsQuantityInSIUnits()
        {
            var quantity = new ThermalTransmitance(value: 1, unit: ThermalTransmitance.BaseUnit);
            var expectedUnit = ThermalTransmitance.Info.GetDefaultUnit(UnitSystem.SI);
            var expectedValue = quantity.As(expectedUnit);

            Assert.Multiple(() =>
            {
                ThermalTransmitance quantityToConvert = quantity;

                ThermalTransmitance convertedQuantity = quantityToConvert.ToUnit(UnitSystem.SI);

                Assert.Equal(expectedUnit, convertedQuantity.Unit);
                Assert.Equal(expectedValue, convertedQuantity.Value);
            }, () =>
            {
                IQuantity<ThermalTransmitanceUnit> quantityToConvert = quantity;

                IQuantity<ThermalTransmitanceUnit> convertedQuantity = quantityToConvert.ToUnit(UnitSystem.SI);

                Assert.Equal(expectedUnit, convertedQuantity.Unit);
                Assert.Equal(expectedValue, convertedQuantity.Value);
            }, () =>
            {
                IQuantity quantityToConvert = quantity;

                IQuantity convertedQuantity = quantityToConvert.ToUnit(UnitSystem.SI);

                Assert.Equal(expectedUnit, convertedQuantity.Unit);
                Assert.Equal(expectedValue, convertedQuantity.Value);
            });
        }

        [Fact]
        public void ToUnit_UnitSystem_ThrowsArgumentNullExceptionIfNull()
        {
            UnitSystem nullUnitSystem = null!;
            Assert.Multiple(() =>
            {
                var quantity = new ThermalTransmitance(value: 1, unit: ThermalTransmitance.BaseUnit);
                Assert.Throws<ArgumentNullException>(() => quantity.ToUnit(nullUnitSystem));
            }, () =>
            {
                IQuantity<ThermalTransmitanceUnit> quantity = new ThermalTransmitance(value: 1, unit: ThermalTransmitance.BaseUnit);
                Assert.Throws<ArgumentNullException>(() => quantity.ToUnit(nullUnitSystem));
            }, () =>
            {
                IQuantity quantity = new ThermalTransmitance(value: 1, unit: ThermalTransmitance.BaseUnit);
                Assert.Throws<ArgumentNullException>(() => quantity.ToUnit(nullUnitSystem));
            });
        }

        [Fact]
        public void ToUnit_UnitSystem_ThrowsArgumentExceptionIfNotSupported()
        {
            var unsupportedUnitSystem = new UnitSystem(UnsupportedBaseUnits);
            Assert.Multiple(() =>
            {
                var quantity = new ThermalTransmitance(value: 1, unit: ThermalTransmitance.BaseUnit);
                Assert.Throws<ArgumentException>(() => quantity.ToUnit(unsupportedUnitSystem));
            }, () =>
            {
                IQuantity<ThermalTransmitanceUnit> quantity = new ThermalTransmitance(value: 1, unit: ThermalTransmitance.BaseUnit);
                Assert.Throws<ArgumentException>(() => quantity.ToUnit(unsupportedUnitSystem));
            }, () =>
            {
                IQuantity quantity = new ThermalTransmitance(value: 1, unit: ThermalTransmitance.BaseUnit);
                Assert.Throws<ArgumentException>(() => quantity.ToUnit(unsupportedUnitSystem));
            });
        }

        [Theory]
        [InlineData("en-US", "4.2 Btu/Hrft²°F", ThermalTransmitanceUnit.BtuPerHourSquareFeetDegreeFahrenheit, 4.2)]
        [InlineData("en-US", "4.2 kcal/cm²Hr°C", ThermalTransmitanceUnit.KilocaloriePerSquareCentimeterHourDegreeCelsius, 4.2)]
        [InlineData("en-US", "4.2 kW/m²K", ThermalTransmitanceUnit.KilowattPerSquareMeterKelvin, 4.2)]
        [InlineData("en-US", "4.2 W/cm²K", ThermalTransmitanceUnit.WattPerSquareCentimeterKelvin, 4.2)]
        [InlineData("en-US", "4.2 W/m²°C", ThermalTransmitanceUnit.WattPerSquareMeterDegreeCelsius, 4.2)]
        [InlineData("en-US", "4.2 W/m²K", ThermalTransmitanceUnit.WattPerSquareMeterKelvin, 4.2)]
        [InlineData("en-US", "4.2 W/mm²K", ThermalTransmitanceUnit.WattPerSquareMillimeterKelvin, 4.2)]
        public void Parse(string culture, string quantityString, ThermalTransmitanceUnit expectedUnit, decimal expectedValue)
        {
            using var _ = new CultureScope(culture);
            var parsed = ThermalTransmitance.Parse(quantityString);
            Assert.Equal(expectedUnit, parsed.Unit);
            Assert.Equal(expectedValue, parsed.Value);
        }

        [Theory]
        [InlineData("en-US", "4.2 Btu/Hrft²°F", ThermalTransmitanceUnit.BtuPerHourSquareFeetDegreeFahrenheit, 4.2)]
        [InlineData("en-US", "4.2 kcal/cm²Hr°C", ThermalTransmitanceUnit.KilocaloriePerSquareCentimeterHourDegreeCelsius, 4.2)]
        [InlineData("en-US", "4.2 kW/m²K", ThermalTransmitanceUnit.KilowattPerSquareMeterKelvin, 4.2)]
        [InlineData("en-US", "4.2 W/cm²K", ThermalTransmitanceUnit.WattPerSquareCentimeterKelvin, 4.2)]
        [InlineData("en-US", "4.2 W/m²°C", ThermalTransmitanceUnit.WattPerSquareMeterDegreeCelsius, 4.2)]
        [InlineData("en-US", "4.2 W/m²K", ThermalTransmitanceUnit.WattPerSquareMeterKelvin, 4.2)]
        [InlineData("en-US", "4.2 W/mm²K", ThermalTransmitanceUnit.WattPerSquareMillimeterKelvin, 4.2)]
        public void TryParse(string culture, string quantityString, ThermalTransmitanceUnit expectedUnit, decimal expectedValue)
        {
            using var _ = new CultureScope(culture);
            Assert.True(ThermalTransmitance.TryParse(quantityString, out ThermalTransmitance parsed));
            Assert.Equal(expectedUnit, parsed.Unit);
            Assert.Equal(expectedValue, parsed.Value);
        }

        [Theory]
        [InlineData("Btu/Hrft²°F", ThermalTransmitanceUnit.BtuPerHourSquareFeetDegreeFahrenheit)]
        [InlineData("kcal/cm²Hr°C", ThermalTransmitanceUnit.KilocaloriePerSquareCentimeterHourDegreeCelsius)]
        [InlineData("kW/m²K", ThermalTransmitanceUnit.KilowattPerSquareMeterKelvin)]
        [InlineData("W/cm²K", ThermalTransmitanceUnit.WattPerSquareCentimeterKelvin)]
        [InlineData("W/m²°C", ThermalTransmitanceUnit.WattPerSquareMeterDegreeCelsius)]
        [InlineData("W/m²K", ThermalTransmitanceUnit.WattPerSquareMeterKelvin)]
        [InlineData("W/mm²K", ThermalTransmitanceUnit.WattPerSquareMillimeterKelvin)]
        public void ParseUnit_WithUsEnglishCurrentCulture(string abbreviation, ThermalTransmitanceUnit expectedUnit)
        {
            // Fallback culture "en-US" is always localized
            using var _ = new CultureScope("en-US");
            ThermalTransmitanceUnit parsedUnit = ThermalTransmitance.ParseUnit(abbreviation);
            Assert.Equal(expectedUnit, parsedUnit);
        }

        [Theory]
        [InlineData("Btu/Hrft²°F", ThermalTransmitanceUnit.BtuPerHourSquareFeetDegreeFahrenheit)]
        [InlineData("kcal/cm²Hr°C", ThermalTransmitanceUnit.KilocaloriePerSquareCentimeterHourDegreeCelsius)]
        [InlineData("kW/m²K", ThermalTransmitanceUnit.KilowattPerSquareMeterKelvin)]
        [InlineData("W/cm²K", ThermalTransmitanceUnit.WattPerSquareCentimeterKelvin)]
        [InlineData("W/m²°C", ThermalTransmitanceUnit.WattPerSquareMeterDegreeCelsius)]
        [InlineData("W/m²K", ThermalTransmitanceUnit.WattPerSquareMeterKelvin)]
        [InlineData("W/mm²K", ThermalTransmitanceUnit.WattPerSquareMillimeterKelvin)]
        public void ParseUnit_WithUnsupportedCurrentCulture_FallsBackToUsEnglish(string abbreviation, ThermalTransmitanceUnit expectedUnit)
        {
            // Currently, no abbreviations are localized for Icelandic, so it should fall back to "en-US" when parsing.
            using var _ = new CultureScope("is-IS");
            ThermalTransmitanceUnit parsedUnit = ThermalTransmitance.ParseUnit(abbreviation);
            Assert.Equal(expectedUnit, parsedUnit);
        }

        [Theory]
        [InlineData("en-US", "Btu/Hrft²°F", ThermalTransmitanceUnit.BtuPerHourSquareFeetDegreeFahrenheit)]
        [InlineData("en-US", "kcal/cm²Hr°C", ThermalTransmitanceUnit.KilocaloriePerSquareCentimeterHourDegreeCelsius)]
        [InlineData("en-US", "kW/m²K", ThermalTransmitanceUnit.KilowattPerSquareMeterKelvin)]
        [InlineData("en-US", "W/cm²K", ThermalTransmitanceUnit.WattPerSquareCentimeterKelvin)]
        [InlineData("en-US", "W/m²°C", ThermalTransmitanceUnit.WattPerSquareMeterDegreeCelsius)]
        [InlineData("en-US", "W/m²K", ThermalTransmitanceUnit.WattPerSquareMeterKelvin)]
        [InlineData("en-US", "W/mm²K", ThermalTransmitanceUnit.WattPerSquareMillimeterKelvin)]
        public void ParseUnit_WithCurrentCulture(string culture, string abbreviation, ThermalTransmitanceUnit expectedUnit)
        {
            using var _ = new CultureScope(culture);
            ThermalTransmitanceUnit parsedUnit = ThermalTransmitance.ParseUnit(abbreviation);
            Assert.Equal(expectedUnit, parsedUnit);
        }

        [Theory]
        [InlineData("en-US", "Btu/Hrft²°F", ThermalTransmitanceUnit.BtuPerHourSquareFeetDegreeFahrenheit)]
        [InlineData("en-US", "kcal/cm²Hr°C", ThermalTransmitanceUnit.KilocaloriePerSquareCentimeterHourDegreeCelsius)]
        [InlineData("en-US", "kW/m²K", ThermalTransmitanceUnit.KilowattPerSquareMeterKelvin)]
        [InlineData("en-US", "W/cm²K", ThermalTransmitanceUnit.WattPerSquareCentimeterKelvin)]
        [InlineData("en-US", "W/m²°C", ThermalTransmitanceUnit.WattPerSquareMeterDegreeCelsius)]
        [InlineData("en-US", "W/m²K", ThermalTransmitanceUnit.WattPerSquareMeterKelvin)]
        [InlineData("en-US", "W/mm²K", ThermalTransmitanceUnit.WattPerSquareMillimeterKelvin)]
        public void ParseUnit_WithCulture(string culture, string abbreviation, ThermalTransmitanceUnit expectedUnit)
        {
            ThermalTransmitanceUnit parsedUnit = ThermalTransmitance.ParseUnit(abbreviation, CultureInfo.GetCultureInfo(culture));
            Assert.Equal(expectedUnit, parsedUnit);
        }

        [Theory]
        [InlineData("Btu/Hrft²°F", ThermalTransmitanceUnit.BtuPerHourSquareFeetDegreeFahrenheit)]
        [InlineData("kcal/cm²Hr°C", ThermalTransmitanceUnit.KilocaloriePerSquareCentimeterHourDegreeCelsius)]
        [InlineData("kW/m²K", ThermalTransmitanceUnit.KilowattPerSquareMeterKelvin)]
        [InlineData("W/cm²K", ThermalTransmitanceUnit.WattPerSquareCentimeterKelvin)]
        [InlineData("W/m²°C", ThermalTransmitanceUnit.WattPerSquareMeterDegreeCelsius)]
        [InlineData("W/m²K", ThermalTransmitanceUnit.WattPerSquareMeterKelvin)]
        [InlineData("W/mm²K", ThermalTransmitanceUnit.WattPerSquareMillimeterKelvin)]
        public void TryParseUnit_WithUsEnglishCurrentCulture(string abbreviation, ThermalTransmitanceUnit expectedUnit)
        {
            // Fallback culture "en-US" is always localized
            using var _ = new CultureScope("en-US");
            Assert.True(ThermalTransmitance.TryParseUnit(abbreviation, out ThermalTransmitanceUnit parsedUnit));
            Assert.Equal(expectedUnit, parsedUnit);
        }

        [Theory]
        [InlineData("Btu/Hrft²°F", ThermalTransmitanceUnit.BtuPerHourSquareFeetDegreeFahrenheit)]
        [InlineData("kcal/cm²Hr°C", ThermalTransmitanceUnit.KilocaloriePerSquareCentimeterHourDegreeCelsius)]
        [InlineData("kW/m²K", ThermalTransmitanceUnit.KilowattPerSquareMeterKelvin)]
        [InlineData("W/cm²K", ThermalTransmitanceUnit.WattPerSquareCentimeterKelvin)]
        [InlineData("W/m²°C", ThermalTransmitanceUnit.WattPerSquareMeterDegreeCelsius)]
        [InlineData("W/m²K", ThermalTransmitanceUnit.WattPerSquareMeterKelvin)]
        [InlineData("W/mm²K", ThermalTransmitanceUnit.WattPerSquareMillimeterKelvin)]
        public void TryParseUnit_WithUnsupportedCurrentCulture_FallsBackToUsEnglish(string abbreviation, ThermalTransmitanceUnit expectedUnit)
        {
            // Currently, no abbreviations are localized for Icelandic, so it should fall back to "en-US" when parsing.
            using var _ = new CultureScope("is-IS");
            Assert.True(ThermalTransmitance.TryParseUnit(abbreviation, out ThermalTransmitanceUnit parsedUnit));
            Assert.Equal(expectedUnit, parsedUnit);
        }

        [Theory]
        [InlineData("en-US", "Btu/Hrft²°F", ThermalTransmitanceUnit.BtuPerHourSquareFeetDegreeFahrenheit)]
        [InlineData("en-US", "kcal/cm²Hr°C", ThermalTransmitanceUnit.KilocaloriePerSquareCentimeterHourDegreeCelsius)]
        [InlineData("en-US", "kW/m²K", ThermalTransmitanceUnit.KilowattPerSquareMeterKelvin)]
        [InlineData("en-US", "W/cm²K", ThermalTransmitanceUnit.WattPerSquareCentimeterKelvin)]
        [InlineData("en-US", "W/m²°C", ThermalTransmitanceUnit.WattPerSquareMeterDegreeCelsius)]
        [InlineData("en-US", "W/m²K", ThermalTransmitanceUnit.WattPerSquareMeterKelvin)]
        [InlineData("en-US", "W/mm²K", ThermalTransmitanceUnit.WattPerSquareMillimeterKelvin)]
        public void TryParseUnit_WithCurrentCulture(string culture, string abbreviation, ThermalTransmitanceUnit expectedUnit)
        {
            using var _ = new CultureScope(culture);
            Assert.True(ThermalTransmitance.TryParseUnit(abbreviation, out ThermalTransmitanceUnit parsedUnit));
            Assert.Equal(expectedUnit, parsedUnit);
        }

        [Theory]
        [InlineData("en-US", "Btu/Hrft²°F", ThermalTransmitanceUnit.BtuPerHourSquareFeetDegreeFahrenheit)]
        [InlineData("en-US", "kcal/cm²Hr°C", ThermalTransmitanceUnit.KilocaloriePerSquareCentimeterHourDegreeCelsius)]
        [InlineData("en-US", "kW/m²K", ThermalTransmitanceUnit.KilowattPerSquareMeterKelvin)]
        [InlineData("en-US", "W/cm²K", ThermalTransmitanceUnit.WattPerSquareCentimeterKelvin)]
        [InlineData("en-US", "W/m²°C", ThermalTransmitanceUnit.WattPerSquareMeterDegreeCelsius)]
        [InlineData("en-US", "W/m²K", ThermalTransmitanceUnit.WattPerSquareMeterKelvin)]
        [InlineData("en-US", "W/mm²K", ThermalTransmitanceUnit.WattPerSquareMillimeterKelvin)]
        public void TryParseUnit_WithCulture(string culture, string abbreviation, ThermalTransmitanceUnit expectedUnit)
        {
            Assert.True(ThermalTransmitance.TryParseUnit(abbreviation, CultureInfo.GetCultureInfo(culture), out ThermalTransmitanceUnit parsedUnit));
            Assert.Equal(expectedUnit, parsedUnit);
        }

        [Theory]
        [InlineData("en-US", ThermalTransmitanceUnit.BtuPerHourSquareFeetDegreeFahrenheit, "Btu/Hrft²°F")]
        [InlineData("en-US", ThermalTransmitanceUnit.KilocaloriePerSquareCentimeterHourDegreeCelsius, "kcal/cm²Hr°C")]
        [InlineData("en-US", ThermalTransmitanceUnit.KilowattPerSquareMeterKelvin, "kW/m²K")]
        [InlineData("en-US", ThermalTransmitanceUnit.WattPerSquareCentimeterKelvin, "W/cm²K")]
        [InlineData("en-US", ThermalTransmitanceUnit.WattPerSquareMeterDegreeCelsius, "W/m²°C")]
        [InlineData("en-US", ThermalTransmitanceUnit.WattPerSquareMeterKelvin, "W/m²K")]
        [InlineData("en-US", ThermalTransmitanceUnit.WattPerSquareMillimeterKelvin, "W/mm²K")]
        public void GetAbbreviationForCulture(string culture, ThermalTransmitanceUnit unit, string expectedAbbreviation)
        {
            var defaultAbbreviation = ThermalTransmitance.GetAbbreviation(unit, CultureInfo.GetCultureInfo(culture));
            Assert.Equal(expectedAbbreviation, defaultAbbreviation);
        }

        [Fact]
        public void GetAbbreviationWithDefaultCulture()
        {
            Assert.All(ThermalTransmitance.Units, unit =>
            {
                var expectedAbbreviation = UnitsNetSetup.Default.UnitAbbreviations.GetDefaultAbbreviation(unit);

                var defaultAbbreviation = ThermalTransmitance.GetAbbreviation(unit);

                Assert.Equal(expectedAbbreviation, defaultAbbreviation);
            });
        }

        [Theory]
        [MemberData(nameof(UnitTypes))]
        public void ToUnit(ThermalTransmitanceUnit unit)
        {
            var inBaseUnits = ThermalTransmitance.From(1.0, ThermalTransmitance.BaseUnit);
            var converted = inBaseUnits.ToUnit(unit);

            var conversionFactor = GetConversionFactor(unit);
            AssertEx.EqualTolerance(conversionFactor.UnitsInBaseUnit, converted.Value, conversionFactor.Tolerence);
            Assert.Equal(unit, converted.Unit);
        }

        [Theory]
        [MemberData(nameof(UnitTypes))]
        public void ToUnit_WithSameUnits_AreEqual(ThermalTransmitanceUnit unit)
        {
            var quantity = ThermalTransmitance.From(3.0, unit);
            var toUnitWithSameUnit = quantity.ToUnit(unit);
            Assert.Equal(quantity, toUnitWithSameUnit);
        }

        [Theory]
        [MemberData(nameof(UnitTypes))]
        public void ToUnit_FromNonBaseUnit_ReturnsQuantityWithGivenUnit(ThermalTransmitanceUnit unit)
        {
            Assert.All(ThermalTransmitance.Units.Where(u => u != ThermalTransmitance.BaseUnit), fromUnit =>
            {
                var quantity = ThermalTransmitance.From(3.0, fromUnit);
                var converted = quantity.ToUnit(unit);
                Assert.Equal(converted.Unit, unit);
                Assert.Equal(quantity, converted);
            });
        }

        [Theory]
        [MemberData(nameof(UnitTypes))]
        public virtual void ToUnit_FromDefaultQuantity_ReturnsQuantityWithGivenUnit(ThermalTransmitanceUnit unit)
        {
            var quantity = default(ThermalTransmitance);
            var converted = quantity.ToUnit(unit);
            Assert.Equal(converted.Unit, unit);
        }

        [Theory]
        [MemberData(nameof(UnitTypes))]
        public void ToUnit_FromIQuantity_ReturnsTheExpectedIQuantity(ThermalTransmitanceUnit unit)
        {
            var quantity = ThermalTransmitance.From(3, ThermalTransmitance.BaseUnit);
            ThermalTransmitance expectedQuantity = quantity.ToUnit(unit);
            Assert.Multiple(() =>
            {
                IQuantity<ThermalTransmitanceUnit> quantityToConvert = quantity;
                IQuantity<ThermalTransmitanceUnit> convertedQuantity = quantityToConvert.ToUnit(unit);
                Assert.Equal(unit, convertedQuantity.Unit);
                Assert.Equal(expectedQuantity, convertedQuantity);
            }, () =>
            {
                IQuantity quantityToConvert = quantity;
                IQuantity convertedQuantity = quantityToConvert.ToUnit(unit);
                Assert.Equal(unit, convertedQuantity.Unit);
                Assert.Equal(expectedQuantity, convertedQuantity);
            });
        }

        [Fact]
        public void ConversionRoundTrip()
        {
            ThermalTransmitance kilowattpersquaremeterkelvin = ThermalTransmitance.FromKilowattsPerSquareMeterKelvin(3);
            Assert.Equal(3, ThermalTransmitance.FromBtusPerHourSquareFeetDegreeFahrenheit(kilowattpersquaremeterkelvin.BtusPerHourSquareFeetDegreeFahrenheit).KilowattsPerSquareMeterKelvin);
            Assert.Equal(3, ThermalTransmitance.FromKilocaloriesPerSquareCentimeterHourDegreeCelsius(kilowattpersquaremeterkelvin.KilocaloriesPerSquareCentimeterHourDegreeCelsius).KilowattsPerSquareMeterKelvin);
            Assert.Equal(3, ThermalTransmitance.FromKilowattsPerSquareMeterKelvin(kilowattpersquaremeterkelvin.KilowattsPerSquareMeterKelvin).KilowattsPerSquareMeterKelvin);
            Assert.Equal(3, ThermalTransmitance.FromWattsPerSquareCentimeterKelvin(kilowattpersquaremeterkelvin.WattsPerSquareCentimeterKelvin).KilowattsPerSquareMeterKelvin);
            Assert.Equal(3, ThermalTransmitance.FromWattsPerSquareMeterDegreeCelsius(kilowattpersquaremeterkelvin.WattsPerSquareMeterDegreeCelsius).KilowattsPerSquareMeterKelvin);
            Assert.Equal(3, ThermalTransmitance.FromWattsPerSquareMeterKelvin(kilowattpersquaremeterkelvin.WattsPerSquareMeterKelvin).KilowattsPerSquareMeterKelvin);
            Assert.Equal(3, ThermalTransmitance.FromWattsPerSquareMillimeterKelvin(kilowattpersquaremeterkelvin.WattsPerSquareMillimeterKelvin).KilowattsPerSquareMeterKelvin);
        }

        [Fact]
        public void ArithmeticOperators()
        {
            ThermalTransmitance v = ThermalTransmitance.FromKilowattsPerSquareMeterKelvin(1);
            Assert.Equal(-1, -v.KilowattsPerSquareMeterKelvin);
            Assert.Equal(2, (ThermalTransmitance.FromKilowattsPerSquareMeterKelvin(3) - v).KilowattsPerSquareMeterKelvin);
            Assert.Equal(2, (v + v).KilowattsPerSquareMeterKelvin);
            Assert.Equal(10, (v * 10).KilowattsPerSquareMeterKelvin);
            Assert.Equal(10, (10 * v).KilowattsPerSquareMeterKelvin);
            Assert.Equal(2, (ThermalTransmitance.FromKilowattsPerSquareMeterKelvin(10) / 5).KilowattsPerSquareMeterKelvin);
            Assert.Equal(2, ThermalTransmitance.FromKilowattsPerSquareMeterKelvin(10) / ThermalTransmitance.FromKilowattsPerSquareMeterKelvin(5));
        }

        [Fact]
        public void ComparisonOperators()
        {
            ThermalTransmitance oneKilowattPerSquareMeterKelvin = ThermalTransmitance.FromKilowattsPerSquareMeterKelvin(1);
            ThermalTransmitance twoKilowattsPerSquareMeterKelvin = ThermalTransmitance.FromKilowattsPerSquareMeterKelvin(2);

            Assert.True(oneKilowattPerSquareMeterKelvin < twoKilowattsPerSquareMeterKelvin);
            Assert.True(oneKilowattPerSquareMeterKelvin <= twoKilowattsPerSquareMeterKelvin);
            Assert.True(twoKilowattsPerSquareMeterKelvin > oneKilowattPerSquareMeterKelvin);
            Assert.True(twoKilowattsPerSquareMeterKelvin >= oneKilowattPerSquareMeterKelvin);

            Assert.False(oneKilowattPerSquareMeterKelvin > twoKilowattsPerSquareMeterKelvin);
            Assert.False(oneKilowattPerSquareMeterKelvin >= twoKilowattsPerSquareMeterKelvin);
            Assert.False(twoKilowattsPerSquareMeterKelvin < oneKilowattPerSquareMeterKelvin);
            Assert.False(twoKilowattsPerSquareMeterKelvin <= oneKilowattPerSquareMeterKelvin);
        }

        [Fact]
        public void CompareToIsImplemented()
        {
            ThermalTransmitance kilowattpersquaremeterkelvin = ThermalTransmitance.FromKilowattsPerSquareMeterKelvin(1);
            Assert.Equal(0, kilowattpersquaremeterkelvin.CompareTo(kilowattpersquaremeterkelvin));
            Assert.True(kilowattpersquaremeterkelvin.CompareTo(ThermalTransmitance.Zero) > 0);
            Assert.True(ThermalTransmitance.Zero.CompareTo(kilowattpersquaremeterkelvin) < 0);
        }

        [Fact]
        public void CompareToThrowsOnTypeMismatch()
        {
            ThermalTransmitance kilowattpersquaremeterkelvin = ThermalTransmitance.FromKilowattsPerSquareMeterKelvin(1);
            Assert.Throws<ArgumentException>(() => kilowattpersquaremeterkelvin.CompareTo(new object()));
        }

        [Fact]
        public void CompareToThrowsOnNull()
        {
            ThermalTransmitance kilowattpersquaremeterkelvin = ThermalTransmitance.FromKilowattsPerSquareMeterKelvin(1);
            Assert.Throws<ArgumentNullException>(() => kilowattpersquaremeterkelvin.CompareTo(null));
        }

        [Theory]
        [InlineData(1, ThermalTransmitanceUnit.KilowattPerSquareMeterKelvin, 1, ThermalTransmitanceUnit.KilowattPerSquareMeterKelvin, true)]  // Same value and unit.
        [InlineData(1, ThermalTransmitanceUnit.KilowattPerSquareMeterKelvin, 2, ThermalTransmitanceUnit.KilowattPerSquareMeterKelvin, false)] // Different value.
        public void Equals_ReturnsTrue_IfValueAndUnitAreEqual(double valueA, ThermalTransmitanceUnit unitA, double valueB, ThermalTransmitanceUnit unitB, bool expectEqual)
        {
            var a = new ThermalTransmitance(valueA, unitA);
            var b = new ThermalTransmitance(valueB, unitB);

            // Operator overloads.
            Assert.Equal(expectEqual, a == b);
            Assert.Equal(expectEqual, b == a);
            Assert.Equal(!expectEqual, a != b);
            Assert.Equal(!expectEqual, b != a);

            // IEquatable<T>
            Assert.Equal(expectEqual, a.Equals(b));
            Assert.Equal(expectEqual, b.Equals(a));

            // IEquatable
            Assert.Equal(expectEqual, a.Equals((object)b));
            Assert.Equal(expectEqual, b.Equals((object)a));
        }

        [Fact]
        public void Equals_Null_ReturnsFalse()
        {
            var a = ThermalTransmitance.Zero;

            Assert.False(a.Equals((object)null));

            // "The result of the expression is always 'false'..."
            #pragma warning disable CS8073
            Assert.False(a == null);
            Assert.False(null == a);
            Assert.True(a != null);
            Assert.True(null != a);
            #pragma warning restore CS8073
        }

        [Fact]
        public void EqualsReturnsFalseOnTypeMismatch()
        {
            ThermalTransmitance kilowattpersquaremeterkelvin = ThermalTransmitance.FromKilowattsPerSquareMeterKelvin(1);
            Assert.False(kilowattpersquaremeterkelvin.Equals(new object()));
        }

        [Fact]
        public void EqualsReturnsFalseOnNull()
        {
            ThermalTransmitance kilowattpersquaremeterkelvin = ThermalTransmitance.FromKilowattsPerSquareMeterKelvin(1);
            Assert.False(kilowattpersquaremeterkelvin.Equals(null));
        }

        [Theory]
        [InlineData(1, 2)]
        [InlineData(100, 110)]
        [InlineData(100, 90)]
        public void Equals_WithTolerance(double firstValue, double secondValue)
        {
            var quantity = ThermalTransmitance.FromKilowattsPerSquareMeterKelvin(firstValue);
            var otherQuantity = ThermalTransmitance.FromKilowattsPerSquareMeterKelvin(secondValue);
            ThermalTransmitance maxTolerance = quantity > otherQuantity ? quantity - otherQuantity : otherQuantity - quantity;
            var largerTolerance = maxTolerance * 1.1m;
            var smallerTolerance = maxTolerance / 1.1m;
            Assert.True(quantity.Equals(quantity, ThermalTransmitance.Zero));
            Assert.True(quantity.Equals(quantity, maxTolerance));
            Assert.True(quantity.Equals(otherQuantity, maxTolerance));
            Assert.True(quantity.Equals(otherQuantity, largerTolerance));
            Assert.False(quantity.Equals(otherQuantity, smallerTolerance));
        }

        [Fact]
        public void Equals_WithNegativeTolerance_ThrowsArgumentOutOfRangeException()
        {
            var quantity = ThermalTransmitance.FromKilowattsPerSquareMeterKelvin(1);
            var negativeTolerance = ThermalTransmitance.FromKilowattsPerSquareMeterKelvin(-1);
            Assert.Throws<ArgumentOutOfRangeException>(() => quantity.Equals(quantity, negativeTolerance));
        }

        [Fact]
        public void HasAtLeastOneAbbreviationSpecified()
        {
            var units = EnumHelper.GetValues<ThermalTransmitanceUnit>();
            foreach (var unit in units)
            {
                var defaultAbbreviation = UnitsNetSetup.Default.UnitAbbreviations.GetDefaultAbbreviation(unit);
            }
        }

        [Fact]
        public void BaseDimensionsShouldNeverBeNull()
        {
            Assert.False(ThermalTransmitance.BaseDimensions is null);
        }

        [Fact]
        public void Units_ReturnsTheQuantityInfoUnits()
        {
            Assert.Equal(ThermalTransmitance.Info.Units, ThermalTransmitance.Units);
        }

        [Fact]
        public void DefaultConversionFunctions_ReturnsTheDefaultUnitConverter()
        {
            Assert.Equal(UnitConverter.Default, ThermalTransmitance.DefaultConversionFunctions);
        }

        [Fact]
        public void ToString_ReturnsValueAndUnitAbbreviationInCurrentCulture()
        {
            using var _ = new CultureScope("en-US");
            Assert.Equal("1 Btu/Hrft²°F", new ThermalTransmitance(1, ThermalTransmitanceUnit.BtuPerHourSquareFeetDegreeFahrenheit).ToString());
            Assert.Equal("1 kcal/cm²Hr°C", new ThermalTransmitance(1, ThermalTransmitanceUnit.KilocaloriePerSquareCentimeterHourDegreeCelsius).ToString());
            Assert.Equal("1 kW/m²K", new ThermalTransmitance(1, ThermalTransmitanceUnit.KilowattPerSquareMeterKelvin).ToString());
            Assert.Equal("1 W/cm²K", new ThermalTransmitance(1, ThermalTransmitanceUnit.WattPerSquareCentimeterKelvin).ToString());
            Assert.Equal("1 W/m²°C", new ThermalTransmitance(1, ThermalTransmitanceUnit.WattPerSquareMeterDegreeCelsius).ToString());
            Assert.Equal("1 W/m²K", new ThermalTransmitance(1, ThermalTransmitanceUnit.WattPerSquareMeterKelvin).ToString());
            Assert.Equal("1 W/mm²K", new ThermalTransmitance(1, ThermalTransmitanceUnit.WattPerSquareMillimeterKelvin).ToString());
        }

        [Fact]
        public void ToString_WithSwedishCulture_ReturnsUnitAbbreviationForEnglishCultureSinceThereAreNoMappings()
        {
            // Chose this culture, because we don't currently have any abbreviations mapped for that culture and we expect the en-US to be used as fallback.
            var swedishCulture = CultureInfo.GetCultureInfo("sv-SE");

            Assert.Equal("1 Btu/Hrft²°F", new ThermalTransmitance(1, ThermalTransmitanceUnit.BtuPerHourSquareFeetDegreeFahrenheit).ToString(swedishCulture));
            Assert.Equal("1 kcal/cm²Hr°C", new ThermalTransmitance(1, ThermalTransmitanceUnit.KilocaloriePerSquareCentimeterHourDegreeCelsius).ToString(swedishCulture));
            Assert.Equal("1 kW/m²K", new ThermalTransmitance(1, ThermalTransmitanceUnit.KilowattPerSquareMeterKelvin).ToString(swedishCulture));
            Assert.Equal("1 W/cm²K", new ThermalTransmitance(1, ThermalTransmitanceUnit.WattPerSquareCentimeterKelvin).ToString(swedishCulture));
            Assert.Equal("1 W/m²°C", new ThermalTransmitance(1, ThermalTransmitanceUnit.WattPerSquareMeterDegreeCelsius).ToString(swedishCulture));
            Assert.Equal("1 W/m²K", new ThermalTransmitance(1, ThermalTransmitanceUnit.WattPerSquareMeterKelvin).ToString(swedishCulture));
            Assert.Equal("1 W/mm²K", new ThermalTransmitance(1, ThermalTransmitanceUnit.WattPerSquareMillimeterKelvin).ToString(swedishCulture));
        }

        [Theory]
        [InlineData(null)]
        [InlineData("en-US")]
        public void ToString_NullFormat_DefaultsToGeneralFormat(string cultureName)
        {
            var quantity = ThermalTransmitance.FromKilowattsPerSquareMeterKelvin(1.0);
            CultureInfo formatProvider = cultureName == null
                ? null
                : CultureInfo.GetCultureInfo(cultureName);

            Assert.Equal(quantity.ToString("G", formatProvider), quantity.ToString(null, formatProvider));
        }

        [Theory]
        [InlineData(null)]
        [InlineData("g")]
        public void ToString_NullProvider_EqualsCurrentCulture(string format)
        {
            var quantity = ThermalTransmitance.FromKilowattsPerSquareMeterKelvin(1.0);
            Assert.Equal(quantity.ToString(format, CultureInfo.CurrentCulture), quantity.ToString(format, null));
        }

        [Fact]
        public void GetHashCode_Equals()
        {
            var quantity = ThermalTransmitance.FromKilowattsPerSquareMeterKelvin(1.0);
            var expected = Comparison.GetHashCode(typeof(ThermalTransmitance), quantity.As(ThermalTransmitance.BaseUnit));
            Assert.Equal(expected, quantity.GetHashCode());
        }

        [Theory]
        [InlineData(1.0)]
        [InlineData(-1.0)]
        public void NegationOperator_ReturnsQuantity_WithNegatedValue(double value)
        {
            var quantity = ThermalTransmitance.FromKilowattsPerSquareMeterKelvin(value);
            Assert.Equal(ThermalTransmitance.FromKilowattsPerSquareMeterKelvin(-value), -quantity);
        }
    }
}
