//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading;
using UnitsNet.InternalHelpers;
using UnitsNet.Tests.Helpers;
using UnitsNet.Tests.TestsBase;
using UnitsNet.Units;
using Xunit;

// Disable build warning CS1718: Comparison made to same variable; did you mean to compare something else?
#pragma warning disable 1718

// ReSharper disable once CheckNamespace
namespace UnitsNet.Tests
{
    /// <summary>
    /// Test of ThermalConductance.
    /// </summary>
// ReSharper disable once PartialTypeWithSinglePart
    public abstract partial class ThermalConductanceTestsBase : QuantityTestsBase
    {
        protected abstract double WattsPerDegreeCelsiusInOneWattPerKelvin { get; }
        protected abstract double WattsPerKelvinInOneWattPerKelvin { get; }

// ReSharper disable VirtualMemberNeverOverriden.Global
        protected virtual double WattsPerDegreeCelsiusTolerance { get { return 1e-5; } }
        protected virtual double WattsPerKelvinTolerance { get { return 1e-5; } }
// ReSharper restore VirtualMemberNeverOverriden.Global

        protected (double UnitsInBaseUnit, double Tolerence) GetConversionFactor(ThermalConductanceUnit unit)
        {
            return unit switch
            {
                ThermalConductanceUnit.WattPerDegreeCelsius => (WattsPerDegreeCelsiusInOneWattPerKelvin, WattsPerDegreeCelsiusTolerance),
                ThermalConductanceUnit.WattPerKelvin => (WattsPerKelvinInOneWattPerKelvin, WattsPerKelvinTolerance),
                _ => throw new NotSupportedException()
            };
        }

        public static IEnumerable<object[]> UnitTypes = new List<object[]>
        {
            new object[] { ThermalConductanceUnit.WattPerDegreeCelsius },
            new object[] { ThermalConductanceUnit.WattPerKelvin },
        };

        [Fact]
        public void DefaultCtor_ReturnsQuantityWithZeroValueAndBaseUnit()
        {
            var quantity = new ThermalConductance();
            Assert.Equal(0, quantity.Value);
            Assert.Equal(ThermalConductanceUnit.WattPerKelvin, quantity.Unit);
        }

        [Fact]
        public void Ctor_WithInfinityValue_DoNotThrowsArgumentException()
        {
            var exception1 = Record.Exception(() => new ThermalConductance(double.PositiveInfinity, ThermalConductanceUnit.WattPerKelvin));
            var exception2 = Record.Exception(() => new ThermalConductance(double.NegativeInfinity, ThermalConductanceUnit.WattPerKelvin));

            Assert.Null(exception1);
            Assert.Null(exception2);
        }

        [Fact]
        public void Ctor_WithNaNValue_DoNotThrowsArgumentException()
        {
            var exception = Record.Exception(() => new ThermalConductance(double.NaN, ThermalConductanceUnit.WattPerKelvin));

            Assert.Null(exception);
        }

        [Fact]
        public void Ctor_NullAsUnitSystem_ThrowsArgumentNullException()
        {
            Assert.Throws<ArgumentNullException>(() => new ThermalConductance(value: 1, unitSystem: null));
        }

        [Fact]
        public virtual void Ctor_SIUnitSystem_ReturnsQuantityWithSIUnits()
        {
            var quantity = new ThermalConductance(value: 1, unitSystem: UnitSystem.SI);
            Assert.Equal(1, quantity.Value);
            Assert.True(quantity.QuantityInfo[quantity.Unit].BaseUnits.IsSubsetOf(UnitSystem.SI.BaseUnits));
        }

        [Fact]
        public void Ctor_UnitSystem_ThrowsArgumentExceptionIfNotSupported()
        {
            var unsupportedUnitSystem = new UnitSystem(UnsupportedBaseUnits);
            Assert.Throws<ArgumentException>(() => new ThermalConductance(value: 1, unitSystem: unsupportedUnitSystem));
        }

        [Fact]
        public void ThermalConductance_QuantityInfo_ReturnsQuantityInfoDescribingQuantity()
        {
            ThermalConductanceUnit[] unitsOrderedByName = EnumHelper.GetValues<ThermalConductanceUnit>().OrderBy(x => x.ToString(), StringComparer.OrdinalIgnoreCase).ToArray();
            var quantity = new ThermalConductance(1, ThermalConductanceUnit.WattPerKelvin);

            QuantityInfo<ThermalConductance, ThermalConductanceUnit> quantityInfo = quantity.QuantityInfo;

            Assert.Equal("ThermalConductance", quantityInfo.Name);
            Assert.Equal(ThermalConductance.Zero, quantityInfo.Zero);
            Assert.Equal(ThermalConductance.BaseUnit, quantityInfo.BaseUnitInfo.Value);
            Assert.Equal(unitsOrderedByName, quantityInfo.Units);
            Assert.Equal(unitsOrderedByName, quantityInfo.UnitInfos.Select(x => x.Value));
            Assert.Equal(ThermalConductance.Info, quantityInfo);
            Assert.Equal(quantityInfo, ((IQuantity)quantity).QuantityInfo);
            Assert.Equal(quantityInfo, ((IQuantity<ThermalConductanceUnit>)quantity).QuantityInfo);
        }

        [Fact]
        public void ThermalConductanceInfo_CreateWithCustomUnitInfos()
        {
            ThermalConductanceUnit[] expectedUnits = [ThermalConductanceUnit.WattPerKelvin];

            ThermalConductance.ThermalConductanceInfo quantityInfo = ThermalConductance.ThermalConductanceInfo.CreateDefault(mappings => mappings.SelectUnits(expectedUnits));

            Assert.Equal("ThermalConductance", quantityInfo.Name);
            Assert.Equal(ThermalConductance.Zero, quantityInfo.Zero);
            Assert.Equal(ThermalConductance.BaseUnit, quantityInfo.BaseUnitInfo.Value);
            Assert.Equal(expectedUnits, quantityInfo.Units);
            Assert.Equal(expectedUnits, quantityInfo.UnitInfos.Select(x => x.Value));
        }

        [Fact]
        public void WattPerKelvinToThermalConductanceUnits()
        {
            ThermalConductance wattperkelvin = ThermalConductance.FromWattsPerKelvin(1);
            AssertEx.EqualTolerance(WattsPerDegreeCelsiusInOneWattPerKelvin, wattperkelvin.WattsPerDegreeCelsius, WattsPerDegreeCelsiusTolerance);
            AssertEx.EqualTolerance(WattsPerKelvinInOneWattPerKelvin, wattperkelvin.WattsPerKelvin, WattsPerKelvinTolerance);
        }

        [Fact]
        public void From_ValueAndUnit_ReturnsQuantityWithSameValueAndUnit()
        {
            Assert.All(EnumHelper.GetValues<ThermalConductanceUnit>(), unit =>
            {
                var quantity = ThermalConductance.From(1, unit);
                Assert.Equal(1, quantity.Value);
                Assert.Equal(unit, quantity.Unit);
            });
        }

        [Fact]
        public void FromWattsPerKelvin_WithInfinityValue_DoNotThrowsArgumentException()
        {
            var exception1 = Record.Exception(() => ThermalConductance.FromWattsPerKelvin(double.PositiveInfinity));
            var exception2 = Record.Exception(() => ThermalConductance.FromWattsPerKelvin(double.NegativeInfinity));

            Assert.Null(exception1);
            Assert.Null(exception2);
        }

        [Fact]
        public void FromWattsPerKelvin_WithNanValue_DoNotThrowsArgumentException()
        {
            var exception = Record.Exception(() => ThermalConductance.FromWattsPerKelvin(double.NaN));

            Assert.Null(exception);
        }

        [Fact]
        public void As()
        {
            var wattperkelvin = ThermalConductance.FromWattsPerKelvin(1);
            AssertEx.EqualTolerance(WattsPerDegreeCelsiusInOneWattPerKelvin, wattperkelvin.As(ThermalConductanceUnit.WattPerDegreeCelsius), WattsPerDegreeCelsiusTolerance);
            AssertEx.EqualTolerance(WattsPerKelvinInOneWattPerKelvin, wattperkelvin.As(ThermalConductanceUnit.WattPerKelvin), WattsPerKelvinTolerance);
        }

        [Fact]
        public virtual void BaseUnit_HasSIBase()
        {
            var baseUnitInfo = ThermalConductance.Info.BaseUnitInfo;
            Assert.True(baseUnitInfo.BaseUnits.IsSubsetOf(UnitSystem.SI.BaseUnits));
        }

        [Fact]
        public virtual void As_UnitSystem_SI_ReturnsQuantityInSIUnits()
        {
            var quantity = new ThermalConductance(value: 1, unit: ThermalConductance.BaseUnit);
            var expectedValue = quantity.As(ThermalConductance.Info.GetDefaultUnit(UnitSystem.SI));

            var convertedValue = quantity.As(UnitSystem.SI);

            Assert.Equal(expectedValue, convertedValue);
        }

        [Fact]
        public void As_UnitSystem_ThrowsArgumentNullExceptionIfNull()
        {
            var quantity = new ThermalConductance(value: 1, unit: ThermalConductance.BaseUnit);
            UnitSystem nullUnitSystem = null!;
            Assert.Throws<ArgumentNullException>(() => quantity.As(nullUnitSystem));
        }

        [Fact]
        public void As_UnitSystem_ThrowsArgumentExceptionIfNotSupported()
        {
            var quantity = new ThermalConductance(value: 1, unit: ThermalConductance.BaseUnit);
            var unsupportedUnitSystem = new UnitSystem(UnsupportedBaseUnits);
            Assert.Throws<ArgumentException>(() => quantity.As(unsupportedUnitSystem));
        }

        [Fact]
        public virtual void ToUnit_UnitSystem_SI_ReturnsQuantityInSIUnits()
        {
            var quantity = new ThermalConductance(value: 1, unit: ThermalConductance.BaseUnit);
            var expectedUnit = ThermalConductance.Info.GetDefaultUnit(UnitSystem.SI);
            var expectedValue = quantity.As(expectedUnit);

            Assert.Multiple(() =>
            {
                ThermalConductance quantityToConvert = quantity;

                ThermalConductance convertedQuantity = quantityToConvert.ToUnit(UnitSystem.SI);

                Assert.Equal(expectedUnit, convertedQuantity.Unit);
                Assert.Equal(expectedValue, convertedQuantity.Value);
            }, () =>
            {
                IQuantity<ThermalConductanceUnit> quantityToConvert = quantity;

                IQuantity<ThermalConductanceUnit> convertedQuantity = quantityToConvert.ToUnit(UnitSystem.SI);

                Assert.Equal(expectedUnit, convertedQuantity.Unit);
                Assert.Equal(expectedValue, convertedQuantity.Value);
            }, () =>
            {
                IQuantity quantityToConvert = quantity;

                IQuantity convertedQuantity = quantityToConvert.ToUnit(UnitSystem.SI);

                Assert.Equal(expectedUnit, convertedQuantity.Unit);
                Assert.Equal(expectedValue, convertedQuantity.Value);
            });
        }

        [Fact]
        public void ToUnit_UnitSystem_ThrowsArgumentNullExceptionIfNull()
        {
            UnitSystem nullUnitSystem = null!;
            Assert.Multiple(() =>
            {
                var quantity = new ThermalConductance(value: 1, unit: ThermalConductance.BaseUnit);
                Assert.Throws<ArgumentNullException>(() => quantity.ToUnit(nullUnitSystem));
            }, () =>
            {
                IQuantity<ThermalConductanceUnit> quantity = new ThermalConductance(value: 1, unit: ThermalConductance.BaseUnit);
                Assert.Throws<ArgumentNullException>(() => quantity.ToUnit(nullUnitSystem));
            }, () =>
            {
                IQuantity quantity = new ThermalConductance(value: 1, unit: ThermalConductance.BaseUnit);
                Assert.Throws<ArgumentNullException>(() => quantity.ToUnit(nullUnitSystem));
            });
        }

        [Fact]
        public void ToUnit_UnitSystem_ThrowsArgumentExceptionIfNotSupported()
        {
            var unsupportedUnitSystem = new UnitSystem(UnsupportedBaseUnits);
            Assert.Multiple(() =>
            {
                var quantity = new ThermalConductance(value: 1, unit: ThermalConductance.BaseUnit);
                Assert.Throws<ArgumentException>(() => quantity.ToUnit(unsupportedUnitSystem));
            }, () =>
            {
                IQuantity<ThermalConductanceUnit> quantity = new ThermalConductance(value: 1, unit: ThermalConductance.BaseUnit);
                Assert.Throws<ArgumentException>(() => quantity.ToUnit(unsupportedUnitSystem));
            }, () =>
            {
                IQuantity quantity = new ThermalConductance(value: 1, unit: ThermalConductance.BaseUnit);
                Assert.Throws<ArgumentException>(() => quantity.ToUnit(unsupportedUnitSystem));
            });
        }

        [Theory]
        [InlineData("en-US", "4.2 W/°C", ThermalConductanceUnit.WattPerDegreeCelsius, 4.2)]
        [InlineData("en-US", "4.2 W/K", ThermalConductanceUnit.WattPerKelvin, 4.2)]
        public void Parse(string culture, string quantityString, ThermalConductanceUnit expectedUnit, decimal expectedValue)
        {
            using var _ = new CultureScope(culture);
            var parsed = ThermalConductance.Parse(quantityString);
            Assert.Equal(expectedUnit, parsed.Unit);
            Assert.Equal(expectedValue, parsed.Value);
        }

        [Theory]
        [InlineData("en-US", "4.2 W/°C", ThermalConductanceUnit.WattPerDegreeCelsius, 4.2)]
        [InlineData("en-US", "4.2 W/K", ThermalConductanceUnit.WattPerKelvin, 4.2)]
        public void TryParse(string culture, string quantityString, ThermalConductanceUnit expectedUnit, decimal expectedValue)
        {
            using var _ = new CultureScope(culture);
            Assert.True(ThermalConductance.TryParse(quantityString, out ThermalConductance parsed));
            Assert.Equal(expectedUnit, parsed.Unit);
            Assert.Equal(expectedValue, parsed.Value);
        }

        [Theory]
        [InlineData("W/°C", ThermalConductanceUnit.WattPerDegreeCelsius)]
        [InlineData("W/K", ThermalConductanceUnit.WattPerKelvin)]
        public void ParseUnit_WithUsEnglishCurrentCulture(string abbreviation, ThermalConductanceUnit expectedUnit)
        {
            // Fallback culture "en-US" is always localized
            using var _ = new CultureScope("en-US");
            ThermalConductanceUnit parsedUnit = ThermalConductance.ParseUnit(abbreviation);
            Assert.Equal(expectedUnit, parsedUnit);
        }

        [Theory]
        [InlineData("W/°C", ThermalConductanceUnit.WattPerDegreeCelsius)]
        [InlineData("W/K", ThermalConductanceUnit.WattPerKelvin)]
        public void ParseUnit_WithUnsupportedCurrentCulture_FallsBackToUsEnglish(string abbreviation, ThermalConductanceUnit expectedUnit)
        {
            // Currently, no abbreviations are localized for Icelandic, so it should fall back to "en-US" when parsing.
            using var _ = new CultureScope("is-IS");
            ThermalConductanceUnit parsedUnit = ThermalConductance.ParseUnit(abbreviation);
            Assert.Equal(expectedUnit, parsedUnit);
        }

        [Theory]
        [InlineData("en-US", "W/°C", ThermalConductanceUnit.WattPerDegreeCelsius)]
        [InlineData("en-US", "W/K", ThermalConductanceUnit.WattPerKelvin)]
        public void ParseUnit_WithCurrentCulture(string culture, string abbreviation, ThermalConductanceUnit expectedUnit)
        {
            using var _ = new CultureScope(culture);
            ThermalConductanceUnit parsedUnit = ThermalConductance.ParseUnit(abbreviation);
            Assert.Equal(expectedUnit, parsedUnit);
        }

        [Theory]
        [InlineData("en-US", "W/°C", ThermalConductanceUnit.WattPerDegreeCelsius)]
        [InlineData("en-US", "W/K", ThermalConductanceUnit.WattPerKelvin)]
        public void ParseUnit_WithCulture(string culture, string abbreviation, ThermalConductanceUnit expectedUnit)
        {
            ThermalConductanceUnit parsedUnit = ThermalConductance.ParseUnit(abbreviation, CultureInfo.GetCultureInfo(culture));
            Assert.Equal(expectedUnit, parsedUnit);
        }

        [Theory]
        [InlineData("W/°C", ThermalConductanceUnit.WattPerDegreeCelsius)]
        [InlineData("W/K", ThermalConductanceUnit.WattPerKelvin)]
        public void TryParseUnit_WithUsEnglishCurrentCulture(string abbreviation, ThermalConductanceUnit expectedUnit)
        {
            // Fallback culture "en-US" is always localized
            using var _ = new CultureScope("en-US");
            Assert.True(ThermalConductance.TryParseUnit(abbreviation, out ThermalConductanceUnit parsedUnit));
            Assert.Equal(expectedUnit, parsedUnit);
        }

        [Theory]
        [InlineData("W/°C", ThermalConductanceUnit.WattPerDegreeCelsius)]
        [InlineData("W/K", ThermalConductanceUnit.WattPerKelvin)]
        public void TryParseUnit_WithUnsupportedCurrentCulture_FallsBackToUsEnglish(string abbreviation, ThermalConductanceUnit expectedUnit)
        {
            // Currently, no abbreviations are localized for Icelandic, so it should fall back to "en-US" when parsing.
            using var _ = new CultureScope("is-IS");
            Assert.True(ThermalConductance.TryParseUnit(abbreviation, out ThermalConductanceUnit parsedUnit));
            Assert.Equal(expectedUnit, parsedUnit);
        }

        [Theory]
        [InlineData("en-US", "W/°C", ThermalConductanceUnit.WattPerDegreeCelsius)]
        [InlineData("en-US", "W/K", ThermalConductanceUnit.WattPerKelvin)]
        public void TryParseUnit_WithCurrentCulture(string culture, string abbreviation, ThermalConductanceUnit expectedUnit)
        {
            using var _ = new CultureScope(culture);
            Assert.True(ThermalConductance.TryParseUnit(abbreviation, out ThermalConductanceUnit parsedUnit));
            Assert.Equal(expectedUnit, parsedUnit);
        }

        [Theory]
        [InlineData("en-US", "W/°C", ThermalConductanceUnit.WattPerDegreeCelsius)]
        [InlineData("en-US", "W/K", ThermalConductanceUnit.WattPerKelvin)]
        public void TryParseUnit_WithCulture(string culture, string abbreviation, ThermalConductanceUnit expectedUnit)
        {
            Assert.True(ThermalConductance.TryParseUnit(abbreviation, CultureInfo.GetCultureInfo(culture), out ThermalConductanceUnit parsedUnit));
            Assert.Equal(expectedUnit, parsedUnit);
        }

        [Theory]
        [InlineData("en-US", ThermalConductanceUnit.WattPerDegreeCelsius, "W/°C")]
        [InlineData("en-US", ThermalConductanceUnit.WattPerKelvin, "W/K")]
        public void GetAbbreviationForCulture(string culture, ThermalConductanceUnit unit, string expectedAbbreviation)
        {
            var defaultAbbreviation = ThermalConductance.GetAbbreviation(unit, CultureInfo.GetCultureInfo(culture));
            Assert.Equal(expectedAbbreviation, defaultAbbreviation);
        }

        [Fact]
        public void GetAbbreviationWithDefaultCulture()
        {
            Assert.All(ThermalConductance.Units, unit =>
            {
                var expectedAbbreviation = UnitsNetSetup.Default.UnitAbbreviations.GetDefaultAbbreviation(unit);

                var defaultAbbreviation = ThermalConductance.GetAbbreviation(unit);

                Assert.Equal(expectedAbbreviation, defaultAbbreviation);
            });
        }

        [Theory]
        [MemberData(nameof(UnitTypes))]
        public void ToUnit(ThermalConductanceUnit unit)
        {
            var inBaseUnits = ThermalConductance.From(1.0, ThermalConductance.BaseUnit);
            var converted = inBaseUnits.ToUnit(unit);

            var conversionFactor = GetConversionFactor(unit);
            AssertEx.EqualTolerance(conversionFactor.UnitsInBaseUnit, converted.Value, conversionFactor.Tolerence);
            Assert.Equal(unit, converted.Unit);
        }

        [Theory]
        [MemberData(nameof(UnitTypes))]
        public void ToUnit_WithSameUnits_AreEqual(ThermalConductanceUnit unit)
        {
            var quantity = ThermalConductance.From(3.0, unit);
            var toUnitWithSameUnit = quantity.ToUnit(unit);
            Assert.Equal(quantity, toUnitWithSameUnit);
        }

        [Theory]
        [MemberData(nameof(UnitTypes))]
        public void ToUnit_FromNonBaseUnit_ReturnsQuantityWithGivenUnit(ThermalConductanceUnit unit)
        {
            Assert.All(ThermalConductance.Units.Where(u => u != ThermalConductance.BaseUnit), fromUnit =>
            {
                var quantity = ThermalConductance.From(3.0, fromUnit);
                var converted = quantity.ToUnit(unit);
                Assert.Equal(converted.Unit, unit);
                Assert.Equal(quantity, converted);
            });
        }

        [Theory]
        [MemberData(nameof(UnitTypes))]
        public virtual void ToUnit_FromDefaultQuantity_ReturnsQuantityWithGivenUnit(ThermalConductanceUnit unit)
        {
            var quantity = default(ThermalConductance);
            var converted = quantity.ToUnit(unit);
            Assert.Equal(converted.Unit, unit);
        }

        [Theory]
        [MemberData(nameof(UnitTypes))]
        public void ToUnit_FromIQuantity_ReturnsTheExpectedIQuantity(ThermalConductanceUnit unit)
        {
            var quantity = ThermalConductance.From(3, ThermalConductance.BaseUnit);
            ThermalConductance expectedQuantity = quantity.ToUnit(unit);
            Assert.Multiple(() =>
            {
                IQuantity<ThermalConductanceUnit> quantityToConvert = quantity;
                IQuantity<ThermalConductanceUnit> convertedQuantity = quantityToConvert.ToUnit(unit);
                Assert.Equal(unit, convertedQuantity.Unit);
                Assert.Equal(expectedQuantity, convertedQuantity);
            }, () =>
            {
                IQuantity quantityToConvert = quantity;
                IQuantity convertedQuantity = quantityToConvert.ToUnit(unit);
                Assert.Equal(unit, convertedQuantity.Unit);
                Assert.Equal(expectedQuantity, convertedQuantity);
            });
        }

        [Fact]
        public void ConversionRoundTrip()
        {
            ThermalConductance wattperkelvin = ThermalConductance.FromWattsPerKelvin(3);
            Assert.Equal(3, ThermalConductance.FromWattsPerDegreeCelsius(wattperkelvin.WattsPerDegreeCelsius).WattsPerKelvin);
            Assert.Equal(3, ThermalConductance.FromWattsPerKelvin(wattperkelvin.WattsPerKelvin).WattsPerKelvin);
        }

        [Fact]
        public void ArithmeticOperators()
        {
            ThermalConductance v = ThermalConductance.FromWattsPerKelvin(1);
            Assert.Equal(-1, -v.WattsPerKelvin);
            Assert.Equal(2, (ThermalConductance.FromWattsPerKelvin(3) - v).WattsPerKelvin);
            Assert.Equal(2, (v + v).WattsPerKelvin);
            Assert.Equal(10, (v * 10).WattsPerKelvin);
            Assert.Equal(10, (10 * v).WattsPerKelvin);
            Assert.Equal(2, (ThermalConductance.FromWattsPerKelvin(10) / 5).WattsPerKelvin);
            Assert.Equal(2, ThermalConductance.FromWattsPerKelvin(10) / ThermalConductance.FromWattsPerKelvin(5));
        }

        [Fact]
        public void ComparisonOperators()
        {
            ThermalConductance oneWattPerKelvin = ThermalConductance.FromWattsPerKelvin(1);
            ThermalConductance twoWattsPerKelvin = ThermalConductance.FromWattsPerKelvin(2);

            Assert.True(oneWattPerKelvin < twoWattsPerKelvin);
            Assert.True(oneWattPerKelvin <= twoWattsPerKelvin);
            Assert.True(twoWattsPerKelvin > oneWattPerKelvin);
            Assert.True(twoWattsPerKelvin >= oneWattPerKelvin);

            Assert.False(oneWattPerKelvin > twoWattsPerKelvin);
            Assert.False(oneWattPerKelvin >= twoWattsPerKelvin);
            Assert.False(twoWattsPerKelvin < oneWattPerKelvin);
            Assert.False(twoWattsPerKelvin <= oneWattPerKelvin);
        }

        [Fact]
        public void CompareToIsImplemented()
        {
            ThermalConductance wattperkelvin = ThermalConductance.FromWattsPerKelvin(1);
            Assert.Equal(0, wattperkelvin.CompareTo(wattperkelvin));
            Assert.True(wattperkelvin.CompareTo(ThermalConductance.Zero) > 0);
            Assert.True(ThermalConductance.Zero.CompareTo(wattperkelvin) < 0);
        }

        [Fact]
        public void CompareToThrowsOnTypeMismatch()
        {
            ThermalConductance wattperkelvin = ThermalConductance.FromWattsPerKelvin(1);
            Assert.Throws<ArgumentException>(() => wattperkelvin.CompareTo(new object()));
        }

        [Fact]
        public void CompareToThrowsOnNull()
        {
            ThermalConductance wattperkelvin = ThermalConductance.FromWattsPerKelvin(1);
            Assert.Throws<ArgumentNullException>(() => wattperkelvin.CompareTo(null));
        }

        [Theory]
        [InlineData(1, ThermalConductanceUnit.WattPerKelvin, 1, ThermalConductanceUnit.WattPerKelvin, true)]  // Same value and unit.
        [InlineData(1, ThermalConductanceUnit.WattPerKelvin, 2, ThermalConductanceUnit.WattPerKelvin, false)] // Different value.
        public void Equals_ReturnsTrue_IfValueAndUnitAreEqual(double valueA, ThermalConductanceUnit unitA, double valueB, ThermalConductanceUnit unitB, bool expectEqual)
        {
            var a = new ThermalConductance(valueA, unitA);
            var b = new ThermalConductance(valueB, unitB);

            // Operator overloads.
            Assert.Equal(expectEqual, a == b);
            Assert.Equal(expectEqual, b == a);
            Assert.Equal(!expectEqual, a != b);
            Assert.Equal(!expectEqual, b != a);

            // IEquatable<T>
            Assert.Equal(expectEqual, a.Equals(b));
            Assert.Equal(expectEqual, b.Equals(a));

            // IEquatable
            Assert.Equal(expectEqual, a.Equals((object)b));
            Assert.Equal(expectEqual, b.Equals((object)a));
        }

        [Fact]
        public void Equals_Null_ReturnsFalse()
        {
            var a = ThermalConductance.Zero;

            Assert.False(a.Equals((object)null));

            // "The result of the expression is always 'false'..."
            #pragma warning disable CS8073
            Assert.False(a == null);
            Assert.False(null == a);
            Assert.True(a != null);
            Assert.True(null != a);
            #pragma warning restore CS8073
        }

        [Fact]
        public void EqualsReturnsFalseOnTypeMismatch()
        {
            ThermalConductance wattperkelvin = ThermalConductance.FromWattsPerKelvin(1);
            Assert.False(wattperkelvin.Equals(new object()));
        }

        [Fact]
        public void EqualsReturnsFalseOnNull()
        {
            ThermalConductance wattperkelvin = ThermalConductance.FromWattsPerKelvin(1);
            Assert.False(wattperkelvin.Equals(null));
        }

        [Theory]
        [InlineData(1, 2)]
        [InlineData(100, 110)]
        [InlineData(100, 90)]
        public void Equals_WithTolerance(double firstValue, double secondValue)
        {
            var quantity = ThermalConductance.FromWattsPerKelvin(firstValue);
            var otherQuantity = ThermalConductance.FromWattsPerKelvin(secondValue);
            ThermalConductance maxTolerance = quantity > otherQuantity ? quantity - otherQuantity : otherQuantity - quantity;
            var largerTolerance = maxTolerance * 1.1m;
            var smallerTolerance = maxTolerance / 1.1m;
            Assert.True(quantity.Equals(quantity, ThermalConductance.Zero));
            Assert.True(quantity.Equals(quantity, maxTolerance));
            Assert.True(quantity.Equals(otherQuantity, maxTolerance));
            Assert.True(quantity.Equals(otherQuantity, largerTolerance));
            Assert.False(quantity.Equals(otherQuantity, smallerTolerance));
        }

        [Fact]
        public void Equals_WithNegativeTolerance_ThrowsArgumentOutOfRangeException()
        {
            var quantity = ThermalConductance.FromWattsPerKelvin(1);
            var negativeTolerance = ThermalConductance.FromWattsPerKelvin(-1);
            Assert.Throws<ArgumentOutOfRangeException>(() => quantity.Equals(quantity, negativeTolerance));
        }

        [Fact]
        public void HasAtLeastOneAbbreviationSpecified()
        {
            var units = EnumHelper.GetValues<ThermalConductanceUnit>();
            foreach (var unit in units)
            {
                var defaultAbbreviation = UnitsNetSetup.Default.UnitAbbreviations.GetDefaultAbbreviation(unit);
            }
        }

        [Fact]
        public void BaseDimensionsShouldNeverBeNull()
        {
            Assert.False(ThermalConductance.BaseDimensions is null);
        }

        [Fact]
        public void Units_ReturnsTheQuantityInfoUnits()
        {
            Assert.Equal(ThermalConductance.Info.Units, ThermalConductance.Units);
        }

        [Fact]
        public void DefaultConversionFunctions_ReturnsTheDefaultUnitConverter()
        {
            Assert.Equal(UnitConverter.Default, ThermalConductance.DefaultConversionFunctions);
        }

        [Fact]
        public void ToString_ReturnsValueAndUnitAbbreviationInCurrentCulture()
        {
            using var _ = new CultureScope("en-US");
            Assert.Equal("1 W/°C", new ThermalConductance(1, ThermalConductanceUnit.WattPerDegreeCelsius).ToString());
            Assert.Equal("1 W/K", new ThermalConductance(1, ThermalConductanceUnit.WattPerKelvin).ToString());
        }

        [Fact]
        public void ToString_WithSwedishCulture_ReturnsUnitAbbreviationForEnglishCultureSinceThereAreNoMappings()
        {
            // Chose this culture, because we don't currently have any abbreviations mapped for that culture and we expect the en-US to be used as fallback.
            var swedishCulture = CultureInfo.GetCultureInfo("sv-SE");

            Assert.Equal("1 W/°C", new ThermalConductance(1, ThermalConductanceUnit.WattPerDegreeCelsius).ToString(swedishCulture));
            Assert.Equal("1 W/K", new ThermalConductance(1, ThermalConductanceUnit.WattPerKelvin).ToString(swedishCulture));
        }

        [Theory]
        [InlineData(null)]
        [InlineData("en-US")]
        public void ToString_NullFormat_DefaultsToGeneralFormat(string cultureName)
        {
            var quantity = ThermalConductance.FromWattsPerKelvin(1.0);
            CultureInfo formatProvider = cultureName == null
                ? null
                : CultureInfo.GetCultureInfo(cultureName);

            Assert.Equal(quantity.ToString("G", formatProvider), quantity.ToString(null, formatProvider));
        }

        [Theory]
        [InlineData(null)]
        [InlineData("g")]
        public void ToString_NullProvider_EqualsCurrentCulture(string format)
        {
            var quantity = ThermalConductance.FromWattsPerKelvin(1.0);
            Assert.Equal(quantity.ToString(format, CultureInfo.CurrentCulture), quantity.ToString(format, null));
        }

        [Fact]
        public void GetHashCode_Equals()
        {
            var quantity = ThermalConductance.FromWattsPerKelvin(1.0);
            var expected = Comparison.GetHashCode(typeof(ThermalConductance), quantity.As(ThermalConductance.BaseUnit));
            Assert.Equal(expected, quantity.GetHashCode());
        }

        [Theory]
        [InlineData(1.0)]
        [InlineData(-1.0)]
        public void NegationOperator_ReturnsQuantity_WithNegatedValue(double value)
        {
            var quantity = ThermalConductance.FromWattsPerKelvin(value);
            Assert.Equal(ThermalConductance.FromWattsPerKelvin(-value), -quantity);
        }
    }
}
