//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

using System.Globalization;
using System.Resources;
using System.Runtime.Serialization;
using UnitsNet.Debug;
using System.Runtime.CompilerServices;

#nullable enable

// ReSharper disable once CheckNamespace

namespace UnitsNet
{
    /// <inheritdoc />
    /// <summary>
    ///     The density, or more precisely, the volumetric mass density, of a substance is its mass per unit volume.
    /// </summary>
    /// <remarks>
    ///     http://en.wikipedia.org/wiki/Density
    /// </remarks>
    [DataContract]
    [DebuggerDisplay(QuantityDebugProxy.DisplayFormat)]
    [DebuggerTypeProxy(typeof(QuantityDebugProxy))]
    public readonly partial struct Density :
        ILinearQuantity<Density, DensityUnit>,
#if NET7_0_OR_GREATER
        IDivisionOperators<Density, Density, QuantityValue>,
        IMultiplyOperators<Density, Length, AreaDensity>,
        IMultiplyOperators<Density, KinematicViscosity, DynamicViscosity>,
        IMultiplyOperators<Density, Area, LinearDensity>,
        IMultiplyOperators<Density, Volume, Mass>,
        IMultiplyOperators<Density, VolumeConcentration, MassConcentration>,
        IMultiplyOperators<Density, VolumeFlow, MassFlow>,
        IMultiplyOperators<Density, Speed, MassFlux>,
        IMultiplyOperators<Density, Acceleration, SpecificWeight>,
        IComparisonOperators<Density, Density, bool>,
        IParsable<Density>,
#endif
        IComparable,
        IComparable<Density>,
        IEquatable<Density>,
        IFormattable
    {
        /// <summary>
        ///     The numeric value this quantity was constructed with.
        /// </summary>
        [DataMember(Name = "Value", Order = 1)]
        private readonly QuantityValue _value;

        /// <summary>
        ///     The unit this quantity was constructed with.
        /// </summary>
        [DataMember(Name = "Unit", Order = 2)]
        private readonly DensityUnit? _unit;

        /// <summary>
        ///     Provides detailed information about the <see cref="Density"/> quantity, including its name, base unit, unit mappings, base dimensions, and conversion functions.
        /// </summary>
        public sealed class DensityInfo: QuantityInfo<Density, DensityUnit>
        {
            /// <inheritdoc />
            public DensityInfo(string name, DensityUnit baseUnit, IEnumerable<IUnitDefinition<DensityUnit>> unitMappings, Density zero, BaseDimensions baseDimensions,
                QuantityFromDelegate<Density, DensityUnit> fromDelegate, ResourceManager? unitAbbreviations)
                : base(name, baseUnit, unitMappings, zero, baseDimensions, fromDelegate, unitAbbreviations)
            {
            }

            /// <inheritdoc />
            public DensityInfo(string name, DensityUnit baseUnit, IEnumerable<IUnitDefinition<DensityUnit>> unitMappings, Density zero, BaseDimensions baseDimensions)
                : this(name, baseUnit, unitMappings, zero, baseDimensions, Density.From, new ResourceManager("UnitsNet.GeneratedCode.Resources.Density", typeof(Density).Assembly))
            {
            }

            /// <summary>
            ///     Creates a new instance of the <see cref="DensityInfo"/> class with the default settings for the Density quantity.
            /// </summary>
            /// <returns>A new instance of the <see cref="DensityInfo"/> class with the default settings.</returns>
            public static DensityInfo CreateDefault()
                => new(nameof(Density), DefaultBaseUnit, GetDefaultMappings(), new(0, DefaultBaseUnit), DefaultBaseDimensions);

            /// <summary>
            ///     Creates a new instance of the <see cref="DensityInfo"/> class with the default settings for the Density quantity and a callback for customizing the default unit mappings.
            /// </summary>
            /// <param name="customizeUnits">
            ///     A callback function for customizing the default unit mappings.
            /// </param>
            /// <returns>
            ///     A new instance of the <see cref="DensityInfo"/> class with the default settings.
            /// </returns>
            public static DensityInfo CreateDefault(Func<IEnumerable<UnitDefinition<DensityUnit>>, IEnumerable<IUnitDefinition<DensityUnit>>> customizeUnits)
                => new(nameof(Density), DefaultBaseUnit, customizeUnits(GetDefaultMappings()), new(0, DefaultBaseUnit), DefaultBaseDimensions);

            /// <summary>
            ///     The <see cref="BaseDimensions" /> for <see cref="Density"/> is L^-3M.
            /// </summary>
            public static BaseDimensions DefaultBaseDimensions
            {
                [MethodImpl(MethodImplOptions.AggressiveInlining)]
                get;
            } = new BaseDimensions(-3, 1, 0, 0, 0, 0, 0);

            /// <summary>
            ///     The default base unit of Density is KilogramPerCubicMeter. All conversions, as defined in the <see cref="GetDefaultMappings"/>, go via this value.
            /// </summary>
            public static DensityUnit DefaultBaseUnit
            {
                [MethodImpl(MethodImplOptions.AggressiveInlining)]
                get;
            } = DensityUnit.KilogramPerCubicMeter;

            /// <summary>
            ///     Retrieves the default mappings for <see cref="DensityUnit"/>.
            /// </summary>
            /// <returns>An <see cref="IEnumerable{T}"/> of <see cref="UnitDefinition{DensityUnit}"/> representing the default unit mappings for Density.</returns>
            public static IEnumerable<UnitDefinition<DensityUnit>> GetDefaultMappings()
            {
                yield return new (DensityUnit.CentigramPerDeciliter, "CentigramPerDeciliter", "CentigramsPerDeciliter", BaseUnits.Undefined,
                     10
                );
                yield return new (DensityUnit.CentigramPerLiter, "CentigramPerLiter", "CentigramsPerLiter", new BaseUnits(length: LengthUnit.Decimeter, mass: MassUnit.Centigram),
                     100
                );
                yield return new (DensityUnit.CentigramPerMilliliter, "CentigramPerMilliliter", "CentigramsPerMilliliter", new BaseUnits(length: LengthUnit.Centimeter, mass: MassUnit.Centigram),
                     new QuantityValue(1, 10)
                );
                yield return new (DensityUnit.DecigramPerDeciliter, "DecigramPerDeciliter", "DecigramsPerDeciliter", BaseUnits.Undefined,
                     1
                );
                yield return new (DensityUnit.DecigramPerLiter, "DecigramPerLiter", "DecigramsPerLiter", new BaseUnits(length: LengthUnit.Decimeter, mass: MassUnit.Decigram),
                     10
                );
                yield return new (DensityUnit.DecigramPerMilliliter, "DecigramPerMilliliter", "DecigramsPerMilliliter", new BaseUnits(length: LengthUnit.Centimeter, mass: MassUnit.Decigram),
                     new QuantityValue(1, 100)
                );
                yield return new (DensityUnit.FemtogramPerDeciliter, "FemtogramPerDeciliter", "FemtogramsPerDeciliter", BaseUnits.Undefined,
                     100000000000000
                );
                yield return new (DensityUnit.FemtogramPerLiter, "FemtogramPerLiter", "FemtogramsPerLiter", new BaseUnits(length: LengthUnit.Decimeter, mass: MassUnit.Femtogram),
                     1000000000000000
                );
                yield return new (DensityUnit.FemtogramPerMilliliter, "FemtogramPerMilliliter", "FemtogramsPerMilliliter", new BaseUnits(length: LengthUnit.Centimeter, mass: MassUnit.Femtogram),
                     1000000000000
                );
                yield return new (DensityUnit.GramPerCubicCentimeter, "GramPerCubicCentimeter", "GramsPerCubicCentimeter", new BaseUnits(length: LengthUnit.Centimeter, mass: MassUnit.Gram),
                     new QuantityValue(1, 1000)
                );
                yield return new (DensityUnit.GramPerCubicFoot, "GramPerCubicFoot", "GramsPerCubicFoot", new BaseUnits(length: LengthUnit.Foot, mass: MassUnit.Gram),
                     new QuantityValue(55306341, 1953125)
                );
                yield return new (DensityUnit.GramPerCubicInch, "GramPerCubicInch", "GramsPerCubicInch", new BaseUnits(length: LengthUnit.Inch, mass: MassUnit.Gram),
                     new QuantityValue(2048383, 125000000)
                );
                yield return new (DensityUnit.GramPerCubicMeter, "GramPerCubicMeter", "GramsPerCubicMeter", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Gram),
                     1000
                );
                yield return new (DensityUnit.GramPerCubicMillimeter, "GramPerCubicMillimeter", "GramsPerCubicMillimeter", new BaseUnits(length: LengthUnit.Millimeter, mass: MassUnit.Gram),
                     new QuantityValue(1, 1000000)
                );
                yield return new (DensityUnit.GramPerDeciliter, "GramPerDeciliter", "GramsPerDeciliter", BaseUnits.Undefined,
                     new QuantityValue(1, 10)
                );
                yield return new (DensityUnit.GramPerLiter, "GramPerLiter", "GramsPerLiter", new BaseUnits(length: LengthUnit.Decimeter, mass: MassUnit.Gram),
                     1
                );
                yield return new (DensityUnit.GramPerMilliliter, "GramPerMilliliter", "GramsPerMilliliter", new BaseUnits(length: LengthUnit.Centimeter, mass: MassUnit.Gram),
                     new QuantityValue(1, 1000)
                );
                yield return new (DensityUnit.KilogramPerCubicCentimeter, "KilogramPerCubicCentimeter", "KilogramsPerCubicCentimeter", new BaseUnits(length: LengthUnit.Centimeter, mass: MassUnit.Kilogram),
                     new QuantityValue(1, 1000000)
                );
                yield return new (DensityUnit.KilogramPerCubicMeter, "KilogramPerCubicMeter", "KilogramsPerCubicMeter", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Kilogram));
                yield return new (DensityUnit.KilogramPerCubicMillimeter, "KilogramPerCubicMillimeter", "KilogramsPerCubicMillimeter", new BaseUnits(length: LengthUnit.Millimeter, mass: MassUnit.Kilogram),
                     new QuantityValue(1, 1000000000)
                );
                yield return new (DensityUnit.KilogramPerLiter, "KilogramPerLiter", "KilogramsPerLiter", new BaseUnits(length: LengthUnit.Decimeter, mass: MassUnit.Kilogram),
                     new QuantityValue(1, 1000)
                );
                yield return new (DensityUnit.KilopoundPerCubicFoot, "KilopoundPerCubicFoot", "KilopoundsPerCubicFoot", new BaseUnits(length: LengthUnit.Foot, mass: MassUnit.Kilopound),
                     new QuantityValue(221225364, 3543690390625)
                );
                yield return new (DensityUnit.KilopoundPerCubicInch, "KilopoundPerCubicInch", "KilopoundsPerCubicInch", new BaseUnits(length: LengthUnit.Inch, mass: MassUnit.Kilopound),
                     new QuantityValue(2048383, 56699046250000)
                );
                yield return new (DensityUnit.KilopoundPerCubicYard, "KilopoundPerCubicYard", "KilopoundsPerCubicYard", new BaseUnits(length: LengthUnit.Yard, mass: MassUnit.Kilopound),
                     new QuantityValue(5973084828, 3543690390625)
                );
                yield return new (DensityUnit.MicrogramPerCubicMeter, "MicrogramPerCubicMeter", "MicrogramsPerCubicMeter", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Microgram),
                     1000000000
                );
                yield return new (DensityUnit.MicrogramPerDeciliter, "MicrogramPerDeciliter", "MicrogramsPerDeciliter", BaseUnits.Undefined,
                     100000
                );
                yield return new (DensityUnit.MicrogramPerLiter, "MicrogramPerLiter", "MicrogramsPerLiter", new BaseUnits(length: LengthUnit.Decimeter, mass: MassUnit.Microgram),
                     1000000
                );
                yield return new (DensityUnit.MicrogramPerMilliliter, "MicrogramPerMilliliter", "MicrogramsPerMilliliter", new BaseUnits(length: LengthUnit.Centimeter, mass: MassUnit.Microgram),
                     1000
                );
                yield return new (DensityUnit.MilligramPerCubicMeter, "MilligramPerCubicMeter", "MilligramsPerCubicMeter", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Milligram),
                     1000000
                );
                yield return new (DensityUnit.MilligramPerDeciliter, "MilligramPerDeciliter", "MilligramsPerDeciliter", BaseUnits.Undefined,
                     100
                );
                yield return new (DensityUnit.MilligramPerLiter, "MilligramPerLiter", "MilligramsPerLiter", new BaseUnits(length: LengthUnit.Decimeter, mass: MassUnit.Milligram),
                     1000
                );
                yield return new (DensityUnit.MilligramPerMilliliter, "MilligramPerMilliliter", "MilligramsPerMilliliter", new BaseUnits(length: LengthUnit.Centimeter, mass: MassUnit.Milligram),
                     1
                );
                yield return new (DensityUnit.NanogramPerDeciliter, "NanogramPerDeciliter", "NanogramsPerDeciliter", BaseUnits.Undefined,
                     100000000
                );
                yield return new (DensityUnit.NanogramPerLiter, "NanogramPerLiter", "NanogramsPerLiter", new BaseUnits(length: LengthUnit.Decimeter, mass: MassUnit.Nanogram),
                     1000000000
                );
                yield return new (DensityUnit.NanogramPerMilliliter, "NanogramPerMilliliter", "NanogramsPerMilliliter", new BaseUnits(length: LengthUnit.Centimeter, mass: MassUnit.Nanogram),
                     1000000
                );
                yield return new (DensityUnit.PicogramPerDeciliter, "PicogramPerDeciliter", "PicogramsPerDeciliter", BaseUnits.Undefined,
                     100000000000
                );
                yield return new (DensityUnit.PicogramPerLiter, "PicogramPerLiter", "PicogramsPerLiter", new BaseUnits(length: LengthUnit.Decimeter, mass: MassUnit.Picogram),
                     1000000000000
                );
                yield return new (DensityUnit.PicogramPerMilliliter, "PicogramPerMilliliter", "PicogramsPerMilliliter", new BaseUnits(length: LengthUnit.Centimeter, mass: MassUnit.Picogram),
                     1000000000
                );
                yield return new (DensityUnit.PoundPerCubicCentimeter, "PoundPerCubicCentimeter", "PoundsPerCubicCentimeter", new BaseUnits(length: LengthUnit.Centimeter, mass: MassUnit.Pound),
                     new QuantityValue(100, 45359237)
                );
                yield return new (DensityUnit.PoundPerCubicFoot, "PoundPerCubicFoot", "PoundsPerCubicFoot", new BaseUnits(length: LengthUnit.Foot, mass: MassUnit.Pound),
                     new QuantityValue(1769802912, 28349523125)
                );
                yield return new (DensityUnit.PoundPerCubicInch, "PoundPerCubicInch", "PoundsPerCubicInch", new BaseUnits(length: LengthUnit.Inch, mass: MassUnit.Pound),
                     new QuantityValue(2048383, 56699046250)
                );
                yield return new (DensityUnit.PoundPerCubicMeter, "PoundPerCubicMeter", "PoundsPerCubicMeter", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Pound),
                     new QuantityValue(100000000, 45359237)
                );
                yield return new (DensityUnit.PoundPerCubicMillimeter, "PoundPerCubicMillimeter", "PoundsPerCubicMillimeter", new BaseUnits(length: LengthUnit.Millimeter, mass: MassUnit.Pound),
                     new QuantityValue(1, 453592370)
                );
                yield return new (DensityUnit.PoundPerCubicYard, "PoundPerCubicYard", "PoundsPerCubicYard", new BaseUnits(length: LengthUnit.Yard, mass: MassUnit.Pound),
                     new QuantityValue(47784678624, 28349523125)
                );
                yield return new (DensityUnit.PoundPerImperialGallon, "PoundPerImperialGallon", "PoundsPerImperialGallon", BaseUnits.Undefined,
                     new QuantityValue(454609, 45359237)
                );
                yield return new (DensityUnit.PoundPerUSGallon, "PoundPerUSGallon", "PoundsPerUSGallon", BaseUnits.Undefined,
                     new QuantityValue(6145149, 736351250)
                );
                yield return new (DensityUnit.SlugPerCubicCentimeter, "SlugPerCubicCentimeter", "SlugsPerCubicCentimeter", new BaseUnits(length: LengthUnit.Centimeter, mass: MassUnit.Slug),
                     new QuantityValue(609600, 8896443230521)
                );
                yield return new (DensityUnit.SlugPerCubicFoot, "SlugPerCubicFoot", "SlugsPerCubicFoot", new BaseUnits(length: LengthUnit.Foot, mass: MassUnit.Slug),
                     new QuantityValue(10788718551552, 5560277019075625)
                );
                yield return new (DensityUnit.SlugPerCubicInch, "SlugPerCubicInch", "SlugsPerCubicInch", new BaseUnits(length: LengthUnit.Inch, mass: MassUnit.Slug),
                     new QuantityValue(6243471384, 5560277019075625)
                );
                yield return new (DensityUnit.SlugPerCubicMeter, "SlugPerCubicMeter", "SlugsPerCubicMeter", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Slug),
                     new QuantityValue(609600000000, 8896443230521)
                );
                yield return new (DensityUnit.SlugPerCubicMillimeter, "SlugPerCubicMillimeter", "SlugsPerCubicMillimeter", new BaseUnits(length: LengthUnit.Millimeter, mass: MassUnit.Slug),
                     new QuantityValue(3048, 44482216152605)
                );
                yield return new (DensityUnit.TonnePerCubicCentimeter, "TonnePerCubicCentimeter", "TonnesPerCubicCentimeter", new BaseUnits(length: LengthUnit.Centimeter, mass: MassUnit.Tonne),
                     new QuantityValue(1, 1000000000)
                );
                yield return new (DensityUnit.TonnePerCubicFoot, "TonnePerCubicFoot", "TonnesPerCubicFoot", new BaseUnits(length: LengthUnit.Foot, mass: MassUnit.Tonne),
                     new QuantityValue(55306341, 1953125000000)
                );
                yield return new (DensityUnit.TonnePerCubicInch, "TonnePerCubicInch", "TonnesPerCubicInch", new BaseUnits(length: LengthUnit.Inch, mass: MassUnit.Tonne),
                     new QuantityValue(2048383, 125000000000000)
                );
                yield return new (DensityUnit.TonnePerCubicMeter, "TonnePerCubicMeter", "TonnesPerCubicMeter", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Tonne),
                     new QuantityValue(1, 1000)
                );
                yield return new (DensityUnit.TonnePerCubicMillimeter, "TonnePerCubicMillimeter", "TonnesPerCubicMillimeter", new BaseUnits(length: LengthUnit.Millimeter, mass: MassUnit.Tonne),
                     new QuantityValue(1, 1000000000000)
                );
            }
        }

        static Density()
        {
            Info = UnitsNetSetup.CreateQuantityInfo(DensityInfo.CreateDefault);
        }

        /// <summary>
        ///     Creates the quantity with the given numeric value and unit.
        /// </summary>
        /// <param name="value">The numeric value to construct this quantity with.</param>
        /// <param name="unit">The unit representation to construct this quantity with.</param>
        public Density(QuantityValue value, DensityUnit unit)
        {
            _value = value;
            _unit = unit;
        }

        /// <summary>
        /// Creates an instance of the quantity with the given numeric value in units compatible with the given <see cref="UnitSystem"/>.
        /// If multiple compatible units were found, the first match is used.
        /// </summary>
        /// <param name="value">The numeric value to construct this quantity with.</param>
        /// <param name="unitSystem">The unit system to create the quantity with.</param>
        /// <exception cref="ArgumentNullException">The given <see cref="UnitSystem"/> is null.</exception>
        /// <exception cref="ArgumentException">No unit was found for the given <see cref="UnitSystem"/>.</exception>
        public Density(QuantityValue value, UnitSystem unitSystem)
        {
            _value = value;
            _unit = Info.GetDefaultUnit(unitSystem);
        }

        #region Static Properties

        /// <summary>
        ///     The <see cref="UnitConverter" /> containing the default generated conversion functions for <see cref="Density" /> instances.
        /// </summary>
        [Obsolete("Replaced by UnitConverter.Default")]
        public static UnitConverter DefaultConversionFunctions
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => UnitConverter.Default;
        }

        /// <inheritdoc cref="IQuantity.QuantityInfo"/>
        public static QuantityInfo<Density, DensityUnit> Info { get; }

        /// <summary>
        ///     The <see cref="BaseDimensions" /> of this quantity.
        /// </summary>
        public static BaseDimensions BaseDimensions
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => Info.BaseDimensions;
        }

        /// <summary>
        ///     The base unit of Density, which is KilogramPerCubicMeter. All conversions go via this value.
        /// </summary>
        public static DensityUnit BaseUnit
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => Info.BaseUnitInfo.Value;
        }

        /// <summary>
        ///     All units of measurement for the Density quantity.
        /// </summary>
        public static IReadOnlyCollection<DensityUnit> Units
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => Info.Units;
        }

        /// <summary>
        ///     Gets an instance of this quantity with a value of 0 in the base unit KilogramPerCubicMeter.
        /// </summary>
        public static Density Zero
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => Info.Zero;
        }

        #endregion

        #region Properties

        /// <inheritdoc />
        public QuantityValue Value
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => _value;
        }

        /// <inheritdoc />
        public DensityUnit Unit
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => _unit.GetValueOrDefault(BaseUnit);
        }

        /// <inheritdoc />
        public QuantityInfo<Density, DensityUnit> QuantityInfo
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => Info;
        }

        #region Explicit implementations

        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        UnitKey IQuantity.UnitKey
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => UnitKey.ForUnit(Unit);
        }

#if NETSTANDARD2_0
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        IQuantityInstanceInfo<Density> IQuantityOfType<Density>.QuantityInfo
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => Info;
        }

        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        QuantityInfo<DensityUnit> IQuantity<DensityUnit>.QuantityInfo
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => Info;
        }

        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        QuantityInfo IQuantity.QuantityInfo
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => Info;
        }

        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        Enum IQuantity.Unit
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => Unit;
        }
#endif

        #endregion

        #endregion

        #region Conversion Properties

        /// <inheritdoc cref="IQuantity{Density,DensityUnit}.AsBaseQuantity"/>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Density AsBaseQuantity()
            => new(this.As(BaseUnit), BaseUnit);

        /// <inheritdoc cref="IQuantity{Density,DensityUnit}.AsBaseValue"/>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public QuantityValue AsBaseValue()
            => this.As(BaseUnit);

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="DensityUnit.CentigramPerDeciliter"/>
        /// </summary>
        public QuantityValue CentigramsPerDeciliter
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(DensityUnit.CentigramPerDeciliter);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="DensityUnit.CentigramPerLiter"/>
        /// </summary>
        public QuantityValue CentigramsPerLiter
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(DensityUnit.CentigramPerLiter);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="DensityUnit.CentigramPerMilliliter"/>
        /// </summary>
        public QuantityValue CentigramsPerMilliliter
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(DensityUnit.CentigramPerMilliliter);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="DensityUnit.DecigramPerDeciliter"/>
        /// </summary>
        public QuantityValue DecigramsPerDeciliter
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(DensityUnit.DecigramPerDeciliter);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="DensityUnit.DecigramPerLiter"/>
        /// </summary>
        public QuantityValue DecigramsPerLiter
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(DensityUnit.DecigramPerLiter);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="DensityUnit.DecigramPerMilliliter"/>
        /// </summary>
        public QuantityValue DecigramsPerMilliliter
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(DensityUnit.DecigramPerMilliliter);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="DensityUnit.FemtogramPerDeciliter"/>
        /// </summary>
        public QuantityValue FemtogramsPerDeciliter
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(DensityUnit.FemtogramPerDeciliter);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="DensityUnit.FemtogramPerLiter"/>
        /// </summary>
        public QuantityValue FemtogramsPerLiter
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(DensityUnit.FemtogramPerLiter);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="DensityUnit.FemtogramPerMilliliter"/>
        /// </summary>
        public QuantityValue FemtogramsPerMilliliter
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(DensityUnit.FemtogramPerMilliliter);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="DensityUnit.GramPerCubicCentimeter"/>
        /// </summary>
        public QuantityValue GramsPerCubicCentimeter
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(DensityUnit.GramPerCubicCentimeter);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="DensityUnit.GramPerCubicFoot"/>
        /// </summary>
        public QuantityValue GramsPerCubicFoot
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(DensityUnit.GramPerCubicFoot);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="DensityUnit.GramPerCubicInch"/>
        /// </summary>
        public QuantityValue GramsPerCubicInch
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(DensityUnit.GramPerCubicInch);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="DensityUnit.GramPerCubicMeter"/>
        /// </summary>
        public QuantityValue GramsPerCubicMeter
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(DensityUnit.GramPerCubicMeter);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="DensityUnit.GramPerCubicMillimeter"/>
        /// </summary>
        public QuantityValue GramsPerCubicMillimeter
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(DensityUnit.GramPerCubicMillimeter);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="DensityUnit.GramPerDeciliter"/>
        /// </summary>
        public QuantityValue GramsPerDeciliter
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(DensityUnit.GramPerDeciliter);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="DensityUnit.GramPerLiter"/>
        /// </summary>
        public QuantityValue GramsPerLiter
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(DensityUnit.GramPerLiter);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="DensityUnit.GramPerMilliliter"/>
        /// </summary>
        public QuantityValue GramsPerMilliliter
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(DensityUnit.GramPerMilliliter);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="DensityUnit.KilogramPerCubicCentimeter"/>
        /// </summary>
        public QuantityValue KilogramsPerCubicCentimeter
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(DensityUnit.KilogramPerCubicCentimeter);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="DensityUnit.KilogramPerCubicMeter"/>
        /// </summary>
        public QuantityValue KilogramsPerCubicMeter
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(DensityUnit.KilogramPerCubicMeter);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="DensityUnit.KilogramPerCubicMillimeter"/>
        /// </summary>
        public QuantityValue KilogramsPerCubicMillimeter
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(DensityUnit.KilogramPerCubicMillimeter);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="DensityUnit.KilogramPerLiter"/>
        /// </summary>
        public QuantityValue KilogramsPerLiter
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(DensityUnit.KilogramPerLiter);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="DensityUnit.KilopoundPerCubicFoot"/>
        /// </summary>
        public QuantityValue KilopoundsPerCubicFoot
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(DensityUnit.KilopoundPerCubicFoot);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="DensityUnit.KilopoundPerCubicInch"/>
        /// </summary>
        public QuantityValue KilopoundsPerCubicInch
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(DensityUnit.KilopoundPerCubicInch);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="DensityUnit.KilopoundPerCubicYard"/>
        /// </summary>
        public QuantityValue KilopoundsPerCubicYard
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(DensityUnit.KilopoundPerCubicYard);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="DensityUnit.MicrogramPerCubicMeter"/>
        /// </summary>
        public QuantityValue MicrogramsPerCubicMeter
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(DensityUnit.MicrogramPerCubicMeter);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="DensityUnit.MicrogramPerDeciliter"/>
        /// </summary>
        public QuantityValue MicrogramsPerDeciliter
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(DensityUnit.MicrogramPerDeciliter);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="DensityUnit.MicrogramPerLiter"/>
        /// </summary>
        public QuantityValue MicrogramsPerLiter
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(DensityUnit.MicrogramPerLiter);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="DensityUnit.MicrogramPerMilliliter"/>
        /// </summary>
        public QuantityValue MicrogramsPerMilliliter
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(DensityUnit.MicrogramPerMilliliter);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="DensityUnit.MilligramPerCubicMeter"/>
        /// </summary>
        public QuantityValue MilligramsPerCubicMeter
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(DensityUnit.MilligramPerCubicMeter);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="DensityUnit.MilligramPerDeciliter"/>
        /// </summary>
        public QuantityValue MilligramsPerDeciliter
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(DensityUnit.MilligramPerDeciliter);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="DensityUnit.MilligramPerLiter"/>
        /// </summary>
        public QuantityValue MilligramsPerLiter
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(DensityUnit.MilligramPerLiter);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="DensityUnit.MilligramPerMilliliter"/>
        /// </summary>
        public QuantityValue MilligramsPerMilliliter
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(DensityUnit.MilligramPerMilliliter);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="DensityUnit.NanogramPerDeciliter"/>
        /// </summary>
        public QuantityValue NanogramsPerDeciliter
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(DensityUnit.NanogramPerDeciliter);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="DensityUnit.NanogramPerLiter"/>
        /// </summary>
        public QuantityValue NanogramsPerLiter
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(DensityUnit.NanogramPerLiter);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="DensityUnit.NanogramPerMilliliter"/>
        /// </summary>
        public QuantityValue NanogramsPerMilliliter
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(DensityUnit.NanogramPerMilliliter);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="DensityUnit.PicogramPerDeciliter"/>
        /// </summary>
        public QuantityValue PicogramsPerDeciliter
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(DensityUnit.PicogramPerDeciliter);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="DensityUnit.PicogramPerLiter"/>
        /// </summary>
        public QuantityValue PicogramsPerLiter
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(DensityUnit.PicogramPerLiter);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="DensityUnit.PicogramPerMilliliter"/>
        /// </summary>
        public QuantityValue PicogramsPerMilliliter
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(DensityUnit.PicogramPerMilliliter);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="DensityUnit.PoundPerCubicCentimeter"/>
        /// </summary>
        public QuantityValue PoundsPerCubicCentimeter
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(DensityUnit.PoundPerCubicCentimeter);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="DensityUnit.PoundPerCubicFoot"/>
        /// </summary>
        public QuantityValue PoundsPerCubicFoot
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(DensityUnit.PoundPerCubicFoot);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="DensityUnit.PoundPerCubicInch"/>
        /// </summary>
        public QuantityValue PoundsPerCubicInch
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(DensityUnit.PoundPerCubicInch);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="DensityUnit.PoundPerCubicMeter"/>
        /// </summary>
        public QuantityValue PoundsPerCubicMeter
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(DensityUnit.PoundPerCubicMeter);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="DensityUnit.PoundPerCubicMillimeter"/>
        /// </summary>
        public QuantityValue PoundsPerCubicMillimeter
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(DensityUnit.PoundPerCubicMillimeter);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="DensityUnit.PoundPerCubicYard"/>
        /// </summary>
        public QuantityValue PoundsPerCubicYard
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(DensityUnit.PoundPerCubicYard);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="DensityUnit.PoundPerImperialGallon"/>
        /// </summary>
        public QuantityValue PoundsPerImperialGallon
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(DensityUnit.PoundPerImperialGallon);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="DensityUnit.PoundPerUSGallon"/>
        /// </summary>
        public QuantityValue PoundsPerUSGallon
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(DensityUnit.PoundPerUSGallon);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="DensityUnit.SlugPerCubicCentimeter"/>
        /// </summary>
        public QuantityValue SlugsPerCubicCentimeter
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(DensityUnit.SlugPerCubicCentimeter);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="DensityUnit.SlugPerCubicFoot"/>
        /// </summary>
        public QuantityValue SlugsPerCubicFoot
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(DensityUnit.SlugPerCubicFoot);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="DensityUnit.SlugPerCubicInch"/>
        /// </summary>
        public QuantityValue SlugsPerCubicInch
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(DensityUnit.SlugPerCubicInch);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="DensityUnit.SlugPerCubicMeter"/>
        /// </summary>
        public QuantityValue SlugsPerCubicMeter
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(DensityUnit.SlugPerCubicMeter);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="DensityUnit.SlugPerCubicMillimeter"/>
        /// </summary>
        public QuantityValue SlugsPerCubicMillimeter
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(DensityUnit.SlugPerCubicMillimeter);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="DensityUnit.TonnePerCubicCentimeter"/>
        /// </summary>
        public QuantityValue TonnesPerCubicCentimeter
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(DensityUnit.TonnePerCubicCentimeter);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="DensityUnit.TonnePerCubicFoot"/>
        /// </summary>
        public QuantityValue TonnesPerCubicFoot
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(DensityUnit.TonnePerCubicFoot);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="DensityUnit.TonnePerCubicInch"/>
        /// </summary>
        public QuantityValue TonnesPerCubicInch
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(DensityUnit.TonnePerCubicInch);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="DensityUnit.TonnePerCubicMeter"/>
        /// </summary>
        public QuantityValue TonnesPerCubicMeter
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(DensityUnit.TonnePerCubicMeter);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="DensityUnit.TonnePerCubicMillimeter"/>
        /// </summary>
        public QuantityValue TonnesPerCubicMillimeter
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(DensityUnit.TonnePerCubicMillimeter);
        }

        #endregion

        #region Static Methods

        /// <summary>
        ///     Get unit abbreviation string.
        /// </summary>
        /// <param name="unit">Unit to get abbreviation for.</param>
        /// <returns>Unit abbreviation string.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static string GetAbbreviation(DensityUnit unit)
            => GetAbbreviation(unit, null);

        /// <summary>
        ///     Get unit abbreviation string.
        /// </summary>
        /// <param name="unit">Unit to get abbreviation for.</param>
        /// <returns>Unit abbreviation string.</returns>
        /// <param name="provider">Format to use for localization. Defaults to <see cref="CultureInfo.CurrentCulture" /> if null.</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static string GetAbbreviation(DensityUnit unit, IFormatProvider? provider)
            => UnitsNetSetup.Default.UnitAbbreviations.GetDefaultAbbreviation(unit, provider);

        #endregion

        #region Static Factory Methods

        /// <summary>
        ///     Creates a <see cref="Density"/> from <see cref="DensityUnit.CentigramPerDeciliter"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Density FromCentigramsPerDeciliter(QuantityValue value)
            => new(value, DensityUnit.CentigramPerDeciliter);

        /// <summary>
        ///     Creates a <see cref="Density"/> from <see cref="DensityUnit.CentigramPerLiter"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Density FromCentigramsPerLiter(QuantityValue value)
            => new(value, DensityUnit.CentigramPerLiter);

        /// <summary>
        ///     Creates a <see cref="Density"/> from <see cref="DensityUnit.CentigramPerMilliliter"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Density FromCentigramsPerMilliliter(QuantityValue value)
            => new(value, DensityUnit.CentigramPerMilliliter);

        /// <summary>
        ///     Creates a <see cref="Density"/> from <see cref="DensityUnit.DecigramPerDeciliter"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Density FromDecigramsPerDeciliter(QuantityValue value)
            => new(value, DensityUnit.DecigramPerDeciliter);

        /// <summary>
        ///     Creates a <see cref="Density"/> from <see cref="DensityUnit.DecigramPerLiter"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Density FromDecigramsPerLiter(QuantityValue value)
            => new(value, DensityUnit.DecigramPerLiter);

        /// <summary>
        ///     Creates a <see cref="Density"/> from <see cref="DensityUnit.DecigramPerMilliliter"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Density FromDecigramsPerMilliliter(QuantityValue value)
            => new(value, DensityUnit.DecigramPerMilliliter);

        /// <summary>
        ///     Creates a <see cref="Density"/> from <see cref="DensityUnit.FemtogramPerDeciliter"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Density FromFemtogramsPerDeciliter(QuantityValue value)
            => new(value, DensityUnit.FemtogramPerDeciliter);

        /// <summary>
        ///     Creates a <see cref="Density"/> from <see cref="DensityUnit.FemtogramPerLiter"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Density FromFemtogramsPerLiter(QuantityValue value)
            => new(value, DensityUnit.FemtogramPerLiter);

        /// <summary>
        ///     Creates a <see cref="Density"/> from <see cref="DensityUnit.FemtogramPerMilliliter"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Density FromFemtogramsPerMilliliter(QuantityValue value)
            => new(value, DensityUnit.FemtogramPerMilliliter);

        /// <summary>
        ///     Creates a <see cref="Density"/> from <see cref="DensityUnit.GramPerCubicCentimeter"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Density FromGramsPerCubicCentimeter(QuantityValue value)
            => new(value, DensityUnit.GramPerCubicCentimeter);

        /// <summary>
        ///     Creates a <see cref="Density"/> from <see cref="DensityUnit.GramPerCubicFoot"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Density FromGramsPerCubicFoot(QuantityValue value)
            => new(value, DensityUnit.GramPerCubicFoot);

        /// <summary>
        ///     Creates a <see cref="Density"/> from <see cref="DensityUnit.GramPerCubicInch"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Density FromGramsPerCubicInch(QuantityValue value)
            => new(value, DensityUnit.GramPerCubicInch);

        /// <summary>
        ///     Creates a <see cref="Density"/> from <see cref="DensityUnit.GramPerCubicMeter"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Density FromGramsPerCubicMeter(QuantityValue value)
            => new(value, DensityUnit.GramPerCubicMeter);

        /// <summary>
        ///     Creates a <see cref="Density"/> from <see cref="DensityUnit.GramPerCubicMillimeter"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Density FromGramsPerCubicMillimeter(QuantityValue value)
            => new(value, DensityUnit.GramPerCubicMillimeter);

        /// <summary>
        ///     Creates a <see cref="Density"/> from <see cref="DensityUnit.GramPerDeciliter"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Density FromGramsPerDeciliter(QuantityValue value)
            => new(value, DensityUnit.GramPerDeciliter);

        /// <summary>
        ///     Creates a <see cref="Density"/> from <see cref="DensityUnit.GramPerLiter"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Density FromGramsPerLiter(QuantityValue value)
            => new(value, DensityUnit.GramPerLiter);

        /// <summary>
        ///     Creates a <see cref="Density"/> from <see cref="DensityUnit.GramPerMilliliter"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Density FromGramsPerMilliliter(QuantityValue value)
            => new(value, DensityUnit.GramPerMilliliter);

        /// <summary>
        ///     Creates a <see cref="Density"/> from <see cref="DensityUnit.KilogramPerCubicCentimeter"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Density FromKilogramsPerCubicCentimeter(QuantityValue value)
            => new(value, DensityUnit.KilogramPerCubicCentimeter);

        /// <summary>
        ///     Creates a <see cref="Density"/> from <see cref="DensityUnit.KilogramPerCubicMeter"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Density FromKilogramsPerCubicMeter(QuantityValue value)
            => new(value, DensityUnit.KilogramPerCubicMeter);

        /// <summary>
        ///     Creates a <see cref="Density"/> from <see cref="DensityUnit.KilogramPerCubicMillimeter"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Density FromKilogramsPerCubicMillimeter(QuantityValue value)
            => new(value, DensityUnit.KilogramPerCubicMillimeter);

        /// <summary>
        ///     Creates a <see cref="Density"/> from <see cref="DensityUnit.KilogramPerLiter"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Density FromKilogramsPerLiter(QuantityValue value)
            => new(value, DensityUnit.KilogramPerLiter);

        /// <summary>
        ///     Creates a <see cref="Density"/> from <see cref="DensityUnit.KilopoundPerCubicFoot"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Density FromKilopoundsPerCubicFoot(QuantityValue value)
            => new(value, DensityUnit.KilopoundPerCubicFoot);

        /// <summary>
        ///     Creates a <see cref="Density"/> from <see cref="DensityUnit.KilopoundPerCubicInch"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Density FromKilopoundsPerCubicInch(QuantityValue value)
            => new(value, DensityUnit.KilopoundPerCubicInch);

        /// <summary>
        ///     Creates a <see cref="Density"/> from <see cref="DensityUnit.KilopoundPerCubicYard"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Density FromKilopoundsPerCubicYard(QuantityValue value)
            => new(value, DensityUnit.KilopoundPerCubicYard);

        /// <summary>
        ///     Creates a <see cref="Density"/> from <see cref="DensityUnit.MicrogramPerCubicMeter"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Density FromMicrogramsPerCubicMeter(QuantityValue value)
            => new(value, DensityUnit.MicrogramPerCubicMeter);

        /// <summary>
        ///     Creates a <see cref="Density"/> from <see cref="DensityUnit.MicrogramPerDeciliter"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Density FromMicrogramsPerDeciliter(QuantityValue value)
            => new(value, DensityUnit.MicrogramPerDeciliter);

        /// <summary>
        ///     Creates a <see cref="Density"/> from <see cref="DensityUnit.MicrogramPerLiter"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Density FromMicrogramsPerLiter(QuantityValue value)
            => new(value, DensityUnit.MicrogramPerLiter);

        /// <summary>
        ///     Creates a <see cref="Density"/> from <see cref="DensityUnit.MicrogramPerMilliliter"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Density FromMicrogramsPerMilliliter(QuantityValue value)
            => new(value, DensityUnit.MicrogramPerMilliliter);

        /// <summary>
        ///     Creates a <see cref="Density"/> from <see cref="DensityUnit.MilligramPerCubicMeter"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Density FromMilligramsPerCubicMeter(QuantityValue value)
            => new(value, DensityUnit.MilligramPerCubicMeter);

        /// <summary>
        ///     Creates a <see cref="Density"/> from <see cref="DensityUnit.MilligramPerDeciliter"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Density FromMilligramsPerDeciliter(QuantityValue value)
            => new(value, DensityUnit.MilligramPerDeciliter);

        /// <summary>
        ///     Creates a <see cref="Density"/> from <see cref="DensityUnit.MilligramPerLiter"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Density FromMilligramsPerLiter(QuantityValue value)
            => new(value, DensityUnit.MilligramPerLiter);

        /// <summary>
        ///     Creates a <see cref="Density"/> from <see cref="DensityUnit.MilligramPerMilliliter"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Density FromMilligramsPerMilliliter(QuantityValue value)
            => new(value, DensityUnit.MilligramPerMilliliter);

        /// <summary>
        ///     Creates a <see cref="Density"/> from <see cref="DensityUnit.NanogramPerDeciliter"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Density FromNanogramsPerDeciliter(QuantityValue value)
            => new(value, DensityUnit.NanogramPerDeciliter);

        /// <summary>
        ///     Creates a <see cref="Density"/> from <see cref="DensityUnit.NanogramPerLiter"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Density FromNanogramsPerLiter(QuantityValue value)
            => new(value, DensityUnit.NanogramPerLiter);

        /// <summary>
        ///     Creates a <see cref="Density"/> from <see cref="DensityUnit.NanogramPerMilliliter"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Density FromNanogramsPerMilliliter(QuantityValue value)
            => new(value, DensityUnit.NanogramPerMilliliter);

        /// <summary>
        ///     Creates a <see cref="Density"/> from <see cref="DensityUnit.PicogramPerDeciliter"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Density FromPicogramsPerDeciliter(QuantityValue value)
            => new(value, DensityUnit.PicogramPerDeciliter);

        /// <summary>
        ///     Creates a <see cref="Density"/> from <see cref="DensityUnit.PicogramPerLiter"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Density FromPicogramsPerLiter(QuantityValue value)
            => new(value, DensityUnit.PicogramPerLiter);

        /// <summary>
        ///     Creates a <see cref="Density"/> from <see cref="DensityUnit.PicogramPerMilliliter"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Density FromPicogramsPerMilliliter(QuantityValue value)
            => new(value, DensityUnit.PicogramPerMilliliter);

        /// <summary>
        ///     Creates a <see cref="Density"/> from <see cref="DensityUnit.PoundPerCubicCentimeter"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Density FromPoundsPerCubicCentimeter(QuantityValue value)
            => new(value, DensityUnit.PoundPerCubicCentimeter);

        /// <summary>
        ///     Creates a <see cref="Density"/> from <see cref="DensityUnit.PoundPerCubicFoot"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Density FromPoundsPerCubicFoot(QuantityValue value)
            => new(value, DensityUnit.PoundPerCubicFoot);

        /// <summary>
        ///     Creates a <see cref="Density"/> from <see cref="DensityUnit.PoundPerCubicInch"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Density FromPoundsPerCubicInch(QuantityValue value)
            => new(value, DensityUnit.PoundPerCubicInch);

        /// <summary>
        ///     Creates a <see cref="Density"/> from <see cref="DensityUnit.PoundPerCubicMeter"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Density FromPoundsPerCubicMeter(QuantityValue value)
            => new(value, DensityUnit.PoundPerCubicMeter);

        /// <summary>
        ///     Creates a <see cref="Density"/> from <see cref="DensityUnit.PoundPerCubicMillimeter"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Density FromPoundsPerCubicMillimeter(QuantityValue value)
            => new(value, DensityUnit.PoundPerCubicMillimeter);

        /// <summary>
        ///     Creates a <see cref="Density"/> from <see cref="DensityUnit.PoundPerCubicYard"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Density FromPoundsPerCubicYard(QuantityValue value)
            => new(value, DensityUnit.PoundPerCubicYard);

        /// <summary>
        ///     Creates a <see cref="Density"/> from <see cref="DensityUnit.PoundPerImperialGallon"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Density FromPoundsPerImperialGallon(QuantityValue value)
            => new(value, DensityUnit.PoundPerImperialGallon);

        /// <summary>
        ///     Creates a <see cref="Density"/> from <see cref="DensityUnit.PoundPerUSGallon"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Density FromPoundsPerUSGallon(QuantityValue value)
            => new(value, DensityUnit.PoundPerUSGallon);

        /// <summary>
        ///     Creates a <see cref="Density"/> from <see cref="DensityUnit.SlugPerCubicCentimeter"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Density FromSlugsPerCubicCentimeter(QuantityValue value)
            => new(value, DensityUnit.SlugPerCubicCentimeter);

        /// <summary>
        ///     Creates a <see cref="Density"/> from <see cref="DensityUnit.SlugPerCubicFoot"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Density FromSlugsPerCubicFoot(QuantityValue value)
            => new(value, DensityUnit.SlugPerCubicFoot);

        /// <summary>
        ///     Creates a <see cref="Density"/> from <see cref="DensityUnit.SlugPerCubicInch"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Density FromSlugsPerCubicInch(QuantityValue value)
            => new(value, DensityUnit.SlugPerCubicInch);

        /// <summary>
        ///     Creates a <see cref="Density"/> from <see cref="DensityUnit.SlugPerCubicMeter"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Density FromSlugsPerCubicMeter(QuantityValue value)
            => new(value, DensityUnit.SlugPerCubicMeter);

        /// <summary>
        ///     Creates a <see cref="Density"/> from <see cref="DensityUnit.SlugPerCubicMillimeter"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Density FromSlugsPerCubicMillimeter(QuantityValue value)
            => new(value, DensityUnit.SlugPerCubicMillimeter);

        /// <summary>
        ///     Creates a <see cref="Density"/> from <see cref="DensityUnit.TonnePerCubicCentimeter"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Density FromTonnesPerCubicCentimeter(QuantityValue value)
            => new(value, DensityUnit.TonnePerCubicCentimeter);

        /// <summary>
        ///     Creates a <see cref="Density"/> from <see cref="DensityUnit.TonnePerCubicFoot"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Density FromTonnesPerCubicFoot(QuantityValue value)
            => new(value, DensityUnit.TonnePerCubicFoot);

        /// <summary>
        ///     Creates a <see cref="Density"/> from <see cref="DensityUnit.TonnePerCubicInch"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Density FromTonnesPerCubicInch(QuantityValue value)
            => new(value, DensityUnit.TonnePerCubicInch);

        /// <summary>
        ///     Creates a <see cref="Density"/> from <see cref="DensityUnit.TonnePerCubicMeter"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Density FromTonnesPerCubicMeter(QuantityValue value)
            => new(value, DensityUnit.TonnePerCubicMeter);

        /// <summary>
        ///     Creates a <see cref="Density"/> from <see cref="DensityUnit.TonnePerCubicMillimeter"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Density FromTonnesPerCubicMillimeter(QuantityValue value)
            => new(value, DensityUnit.TonnePerCubicMillimeter);

        /// <summary>
        ///     Dynamically convert from value and unit enum <see cref="DensityUnit" /> to <see cref="Density" />.
        /// </summary>
        /// <param name="value">Value to convert from.</param>
        /// <param name="fromUnit">Unit to convert from.</param>
        /// <returns>Density unit value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Density From(QuantityValue value, DensityUnit fromUnit)
            => new(value, fromUnit);

        #endregion

        #region Static Parse Methods

        /// <summary>
        ///     Parse a string with one or two quantities of the format "&lt;quantity&gt; &lt;unit&gt;".
        /// </summary>
        /// <param name="str">String to parse. Typically in the form: {number} {unit}</param>
        /// <example>
        ///     Length.Parse("5.5 m", CultureInfo.GetCultureInfo("en-US"));
        /// </example>
        /// <exception cref="ArgumentNullException">The value of 'str' cannot be null. </exception>
        /// <exception cref="ArgumentException">
        ///     Expected string to have one or two pairs of quantity and unit in the format
        ///     "&lt;quantity&gt; &lt;unit&gt;". Eg. "5.5 m" or "1ft 2in"
        /// </exception>
        /// <exception cref="AmbiguousUnitParseException">
        ///     More than one unit is represented by the specified unit abbreviation.
        ///     Example: Volume.Parse("1 cup") will throw, because it can refer to any of
        ///     <see cref="VolumeUnit.MetricCup" />, <see cref="VolumeUnit.UsLegalCup" /> and <see cref="VolumeUnit.UsCustomaryCup" />.
        /// </exception>
        /// <exception cref="UnitsNetException">
        ///     If anything else goes wrong, typically due to a bug or unhandled case.
        ///     We wrap exceptions in <see cref="UnitsNetException" /> to allow you to distinguish
        ///     Units.NET exceptions from other exceptions.
        /// </exception>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Density Parse(string str)
            => Parse(str, null);

        /// <summary>
        ///     Parse a string with one or two quantities of the format "&lt;quantity&gt; &lt;unit&gt;".
        /// </summary>
        /// <param name="str">String to parse. Typically in the form: {number} {unit}</param>
        /// <example>
        ///     Length.Parse("5.5 m", CultureInfo.GetCultureInfo("en-US"));
        /// </example>
        /// <exception cref="ArgumentNullException">The value of 'str' cannot be null. </exception>
        /// <exception cref="ArgumentException">
        ///     Expected string to have one or two pairs of quantity and unit in the format
        ///     "&lt;quantity&gt; &lt;unit&gt;". Eg. "5.5 m" or "1ft 2in"
        /// </exception>
        /// <exception cref="AmbiguousUnitParseException">
        ///     More than one unit is represented by the specified unit abbreviation.
        ///     Example: Volume.Parse("1 cup") will throw, because it can refer to any of
        ///     <see cref="VolumeUnit.MetricCup" />, <see cref="VolumeUnit.UsLegalCup" /> and <see cref="VolumeUnit.UsCustomaryCup" />.
        /// </exception>
        /// <exception cref="UnitsNetException">
        ///     If anything else goes wrong, typically due to a bug or unhandled case.
        ///     We wrap exceptions in <see cref="UnitsNetException" /> to allow you to distinguish
        ///     Units.NET exceptions from other exceptions.
        /// </exception>
        /// <param name="provider">Format to use when parsing number and unit. Defaults to <see cref="CultureInfo.CurrentCulture" /> if null.</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Density Parse(string str, IFormatProvider? provider)
            => QuantityParser.Default.Parse<Density, DensityUnit>(str, provider, From);

        /// <summary>
        ///     Try to parse a string with one or two quantities of the format "&lt;quantity&gt; &lt;unit&gt;".
        /// </summary>
        /// <param name="str">String to parse. Typically in the form: {number} {unit}</param>
        /// <param name="result">Resulting unit quantity if successful.</param>
        /// <example>
        ///     Length.Parse("5.5 m", CultureInfo.GetCultureInfo("en-US"));
        /// </example>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool TryParse([NotNullWhen(true)]string? str, out Density result)
            => TryParse(str, null, out result);

        /// <summary>
        ///     Try to parse a string with one or two quantities of the format "&lt;quantity&gt; &lt;unit&gt;".
        /// </summary>
        /// <param name="str">String to parse. Typically in the form: {number} {unit}</param>
        /// <param name="result">Resulting unit quantity if successful.</param>
        /// <returns>True if successful, otherwise false.</returns>
        /// <example>
        ///     Length.Parse("5.5 m", CultureInfo.GetCultureInfo("en-US"));
        /// </example>
        /// <param name="provider">Format to use when parsing number and unit. Defaults to <see cref="CultureInfo.CurrentCulture" /> if null.</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool TryParse([NotNullWhen(true)]string? str, IFormatProvider? provider, out Density result)
            => QuantityParser.Default.TryParse<Density, DensityUnit>(str, provider, From, out result);

        /// <summary>
        ///     Parse a unit string.
        /// </summary>
        /// <param name="str">String to parse. Typically in the form: {number} {unit}</param>
        /// <example>
        ///     Length.ParseUnit("m", CultureInfo.GetCultureInfo("en-US"));
        /// </example>
        /// <exception cref="ArgumentNullException">The value of 'str' cannot be null. </exception>
        /// <exception cref="UnitsNetException">Error parsing string.</exception>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static DensityUnit ParseUnit(string str)
            => ParseUnit(str, null);

        /// <summary>
        ///     Parse a unit string.
        /// </summary>
        /// <param name="str">String to parse. Typically in the form: {number} {unit}</param>
        /// <param name="provider">Format to use when parsing the unit. Defaults to <see cref="CultureInfo.CurrentCulture" /> if null.</param>
        /// <example>
        ///     Length.ParseUnit("m", CultureInfo.GetCultureInfo("en-US"));
        /// </example>
        /// <exception cref="ArgumentNullException">The value of 'str' cannot be null. </exception>
        /// <exception cref="UnitsNetException">Error parsing string.</exception>
        public static DensityUnit ParseUnit(string str, IFormatProvider? provider)
            => UnitParser.Default.Parse(str, Info.UnitInfos, provider).Value;

        /// <inheritdoc cref="TryParseUnit(string,IFormatProvider?,out UnitsNet.Units.DensityUnit)"/>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool TryParseUnit([NotNullWhen(true)]string? str, out DensityUnit unit)
            => TryParseUnit(str, null, out unit);

        /// <summary>
        ///     Parse a unit string.
        /// </summary>
        /// <param name="str">String to parse. Typically in the form: {number} {unit}</param>
        /// <param name="unit">The parsed unit if successful.</param>
        /// <returns>True if successful, otherwise false.</returns>
        /// <example>
        ///     Length.TryParseUnit("m", CultureInfo.GetCultureInfo("en-US"));
        /// </example>
        /// <param name="provider">Format to use when parsing the unit. Defaults to <see cref="CultureInfo.CurrentCulture" /> if null.</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool TryParseUnit([NotNullWhen(true)]string? str, IFormatProvider? provider, out DensityUnit unit)
            => UnitParser.Default.TryParse(str, Info, provider, out unit);

        #endregion

        #region Arithmetic Operators

        /// <summary>Negate the value.</summary>
        public static Density operator -(Density right)
            => new(-right.Value, right.Unit);

        /// <summary>Get <see cref="Density"/> from adding two <see cref="Density"/>.</summary>
        public static Density operator +(Density left, Density right)
            => new(left.Value + right.As(left.Unit), left.Unit);

        /// <summary>Get <see cref="Density"/> from subtracting two <see cref="Density"/>.</summary>
        public static Density operator -(Density left, Density right)
            => new(left.Value - right.As(left.Unit), left.Unit);

        /// <summary>Get <see cref="Density"/> from multiplying value and <see cref="Density"/>.</summary>
        public static Density operator *(QuantityValue left, Density right)
            => new(left * right.Value, right.Unit);

        /// <summary>Get <see cref="Density"/> from multiplying value and <see cref="Density"/>.</summary>
        public static Density operator *(Density left, QuantityValue right)
            => new(left.Value * right, left.Unit);

        /// <summary>Get <see cref="Density"/> from dividing <see cref="Density"/> by value.</summary>
        public static Density operator /(Density left, QuantityValue right)
            => new(left.Value / right, left.Unit);

        /// <summary>Get ratio value from dividing <see cref="Density"/> by <see cref="Density"/>.</summary>
        public static QuantityValue operator /(Density left, Density right)
            => left.KilogramsPerCubicMeter / right.KilogramsPerCubicMeter;

        #endregion

        #region Relational Operators

        /// <summary>Calculates the inverse of this quantity.</summary>
        /// <returns>The corresponding inverse quantity, <see cref="SpecificVolume"/>.</returns>
        public SpecificVolume Inverse()
            => UnitConverter.Default.ConvertTo(Value, Unit, SpecificVolume.Info);

        /// <summary>Get <see cref="AreaDensity"/> from <see cref="Density"/> * <see cref="Length"/>.</summary>
        public static AreaDensity operator *(Density density, Length length)
            => AreaDensity.FromKilogramsPerSquareMeter(density.KilogramsPerCubicMeter * length.Meters);

        /// <summary>Get <see cref="DynamicViscosity"/> from <see cref="Density"/> * <see cref="KinematicViscosity"/>.</summary>
        public static DynamicViscosity operator *(Density density, KinematicViscosity kinematicViscosity)
            => DynamicViscosity.FromNewtonSecondsPerMeterSquared(density.KilogramsPerCubicMeter * kinematicViscosity.SquareMetersPerSecond);

        /// <summary>Get <see cref="LinearDensity"/> from <see cref="Density"/> * <see cref="Area"/>.</summary>
        public static LinearDensity operator *(Density density, Area area)
            => LinearDensity.FromKilogramsPerMeter(density.KilogramsPerCubicMeter * area.SquareMeters);

        /// <summary>Get <see cref="Mass"/> from <see cref="Density"/> * <see cref="Volume"/>.</summary>
        public static Mass operator *(Density density, Volume volume)
            => Mass.FromKilograms(density.KilogramsPerCubicMeter * volume.CubicMeters);

        /// <summary>Get <see cref="MassConcentration"/> from <see cref="Density"/> * <see cref="VolumeConcentration"/>.</summary>
        public static MassConcentration operator *(Density density, VolumeConcentration volumeConcentration)
            => MassConcentration.FromKilogramsPerCubicMeter(density.KilogramsPerCubicMeter * volumeConcentration.DecimalFractions);

        /// <summary>Get <see cref="MassFlow"/> from <see cref="Density"/> * <see cref="VolumeFlow"/>.</summary>
        public static MassFlow operator *(Density density, VolumeFlow volumeFlow)
            => MassFlow.FromKilogramsPerSecond(density.KilogramsPerCubicMeter * volumeFlow.CubicMetersPerSecond);

        /// <summary>Get <see cref="MassFlux"/> from <see cref="Density"/> * <see cref="Speed"/>.</summary>
        public static MassFlux operator *(Density density, Speed speed)
            => MassFlux.FromKilogramsPerSecondPerSquareMeter(density.KilogramsPerCubicMeter * speed.MetersPerSecond);

        /// <summary>Get <see cref="SpecificWeight"/> from <see cref="Density"/> * <see cref="Acceleration"/>.</summary>
        public static SpecificWeight operator *(Density density, Acceleration acceleration)
            => SpecificWeight.FromNewtonsPerCubicMeter(density.KilogramsPerCubicMeter * acceleration.MetersPerSecondSquared);

        #endregion

        #region Equality / IComparable

        /// <summary>Returns true if less or equal to.</summary>
        public static bool operator <=(Density left, Density right)
            => left.Value <= right.As(left.Unit);

        /// <summary>Returns true if greater than or equal to.</summary>
        public static bool operator >=(Density left, Density right)
            => left.Value >= right.As(left.Unit);

        /// <summary>Returns true if less than.</summary>
        public static bool operator <(Density left, Density right)
            => left.Value < right.As(left.Unit);

        /// <summary>Returns true if greater than.</summary>
        public static bool operator >(Density left, Density right)
            => left.Value > right.As(left.Unit);

        /// <summary>
        ///     Determines whether two <see cref="Density"/> instances are equal.
        /// </summary>
        /// <remarks>
        ///     Equality is evaluated in a unit-aware manner. The right-hand operand is converted to the unit of the left-hand
        ///     operand and then the underlying numeric values are compared.
        ///     This means two quantities with numerically equal values but different units will be considered equal.
        ///     The operator delegates to <see cref="Equals(Density)"/>, which implements this conversion-and-compare logic.
        /// </remarks>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool operator ==(Density left, Density right)
            => left.Equals(right);

        /// <summary>
        ///     Determines whether two <see cref="Density"/> instances are not equal.
        /// </summary>
        /// <remarks>
        ///     This operator is the logical negation of <see cref="operator ==(Density,Density)"/>.
        ///     See that operator (and <see cref="Equals(Density)"/>) for details on how equality is evaluated
        ///     (i.e., by converting one operand to the other's unit and comparing their numeric values).
        /// </remarks>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool operator !=(Density left, Density right)
            => !(left == right);

        /// <inheritdoc />
        /// <summary>
        ///     Determines whether the specified object is equal to the current <see cref="Density"/> instance.
        /// </summary>
        /// <remarks>
        ///     Returns <c>false</c> if <paramref name="obj"/> is <c>null</c> or not a <see cref="Density"/>.
        ///     When <paramref name="obj"/> is a <see cref="Density"/>, this method delegates to
        ///     <see cref="Equals(Density)"/>, which performs a unit-aware comparison by converting the other
        ///     instance to this instance's unit before comparing numeric values.
        /// </remarks>
        public override bool Equals(object? obj)
            => obj is Density otherQuantity && Equals(otherQuantity);

        /// <inheritdoc />
        /// <summary>
        ///     Determines whether the current instance is equal to another <see cref="Density"/> instance.
        /// </summary>
        /// <remarks>
        ///     Comparison is performed by converting <paramref name="other"/> to this instance's unit and then comparing the underlying numeric values.
        ///     This makes two quantities equal even when their units differ, provided the converted numeric values are equal.
        /// </remarks>
        public bool Equals(Density other)
            => _value.Equals(other.As(Unit));

        /// <summary>
        ///     Returns the hash code for this instance.
        /// </summary>
        /// <returns>A hash code for the current Density.</returns>
        public override int GetHashCode()
            => Comparison.GetHashCode(typeof(Density), this.As(BaseUnit));

        /// <inheritdoc  cref="CompareTo(Density)" />
        /// <param name="obj">An object to compare with this instance.</param>
        /// <exception cref="T:System.ArgumentException">
        ///    <paramref name="obj" /> is not the same type as this instance.
        /// </exception>
        public int CompareTo(object? obj)
        {
            if (obj is not Density otherQuantity)
                throw obj is null ? new ArgumentNullException(nameof(obj)) : ExceptionHelper.CreateArgumentException<Density>(obj, nameof(obj));

            return CompareTo(otherQuantity);
        }

        /// <summary>
        ///     Compares the current <see cref="Density"/> with another <see cref="Density"/> and returns an integer that indicates
        ///     whether the current instance precedes, follows, or occurs in the same position in the sort order as the other quantity, when converted to the same unit.
        /// </summary>
        /// <param name="other">A quantity to compare with this instance.</param>
        /// <returns>A value that indicates the relative order of the quantities being compared. The return value has these meanings:
        ///     <list type="table">
        ///         <listheader><term> Value</term><description> Meaning</description></listheader>
        ///         <item><term> Less than zero</term><description> This instance precedes <paramref name="other" /> in the sort order.</description></item>
        ///         <item><term> Zero</term><description> This instance occurs in the same position in the sort order as <paramref name="other" />.</description></item>
        ///         <item><term> Greater than zero</term><description> This instance follows <paramref name="other" /> in the sort order.</description></item>
        ///     </list>
        /// </returns>
        public int CompareTo(Density other)
            => _value.CompareTo(other.As(Unit));

        #endregion

        #region ToString Methods

        /// <summary>
        ///     Gets the default string representation of value and unit.
        /// </summary>
        /// <returns>String representation.</returns>
        public override string ToString()
            => ToString(null, null);

        /// <inheritdoc cref="QuantityFormatter.Format{TQuantity}(TQuantity, string, IFormatProvider)"/>
        /// <summary>
        /// Gets the string representation of this instance in the specified format string using the specified format provider, or <see cref="CultureInfo.CurrentCulture" /> if null.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public string ToString(
            [StringSyntax(StringSyntaxAttribute.NumericFormat)] string? format,
            IFormatProvider? provider)
            => QuantityFormatter.Default.Format(this, format, provider);

        #endregion

    }
}
