//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

using System.Globalization;
using System.Resources;
using System.Runtime.Serialization;
using UnitsNet.Debug;
using System.Runtime.CompilerServices;

#nullable enable

// ReSharper disable once CheckNamespace

namespace UnitsNet
{
    /// <inheritdoc />
    /// <summary>
    ///     Electrical susceptance is the imaginary part of admittance, where the real part is conductance.
    /// </summary>
    /// <remarks>
    ///     https://en.wikipedia.org/wiki/Electrical_susceptance
    /// </remarks>
    [DataContract]
    [DebuggerDisplay(QuantityDebugProxy.DisplayFormat)]
    [DebuggerTypeProxy(typeof(QuantityDebugProxy))]
    public readonly partial struct ElectricSusceptance :
        ILinearQuantity<ElectricSusceptance, ElectricSusceptanceUnit>,
#if NET7_0_OR_GREATER
        IDivisionOperators<ElectricSusceptance, ElectricSusceptance, QuantityValue>,
        IComparisonOperators<ElectricSusceptance, ElectricSusceptance, bool>,
        IParsable<ElectricSusceptance>,
#endif
        IComparable,
        IComparable<ElectricSusceptance>,
        IEquatable<ElectricSusceptance>,
        IFormattable
    {
        /// <summary>
        ///     The numeric value this quantity was constructed with.
        /// </summary>
        [DataMember(Name = "Value", Order = 1)]
        private readonly QuantityValue _value;

        /// <summary>
        ///     The unit this quantity was constructed with.
        /// </summary>
        [DataMember(Name = "Unit", Order = 2)]
        private readonly ElectricSusceptanceUnit? _unit;

        /// <summary>
        ///     Provides detailed information about the <see cref="ElectricSusceptance"/> quantity, including its name, base unit, unit mappings, base dimensions, and conversion functions.
        /// </summary>
        public sealed class ElectricSusceptanceInfo : QuantityInfo<ElectricSusceptance, ElectricSusceptanceUnit>
        {
            /// <inheritdoc />
            public ElectricSusceptanceInfo(string name, ElectricSusceptanceUnit baseUnit, ElectricSusceptanceUnit siBaseUnit, IEnumerable<IUnitDefinition<ElectricSusceptanceUnit>> unitMappings, ElectricSusceptance zero, BaseDimensions baseDimensions,
                QuantityFromDelegate<ElectricSusceptance, ElectricSusceptanceUnit> fromDelegate, ResourceManager? unitAbbreviations)
                : base(name, baseUnit, siBaseUnit, unitMappings, zero, baseDimensions, fromDelegate, unitAbbreviations)
            {
            }

            /// <inheritdoc />
            public ElectricSusceptanceInfo(string name, ElectricSusceptanceUnit baseUnit, ElectricSusceptanceUnit siBaseUnit, IEnumerable<IUnitDefinition<ElectricSusceptanceUnit>> unitMappings, ElectricSusceptance zero, BaseDimensions baseDimensions)
                : this(name, baseUnit, siBaseUnit, unitMappings, zero, baseDimensions, ElectricSusceptance.From, new ResourceManager("UnitsNet.GeneratedCode.Resources.ElectricSusceptance", typeof(ElectricSusceptance).Assembly))
            {
            }

            /// <summary>
            ///     Creates a new instance of the <see cref="ElectricSusceptanceInfo"/> class with the default settings for the ElectricSusceptance quantity.
            /// </summary>
            /// <returns>A new instance of the <see cref="ElectricSusceptanceInfo"/> class with the default settings.</returns>
            public static ElectricSusceptanceInfo CreateDefault()
                => new(nameof(ElectricSusceptance), DefaultBaseUnit, DefaultSiBaseUnit, GetDefaultMappings(), new(0, DefaultBaseUnit), DefaultBaseDimensions);

            /// <summary>
            ///     Creates a new instance of the <see cref="ElectricSusceptanceInfo"/> class with the default settings for the ElectricSusceptance quantity and a callback for customizing the default unit mappings.
            /// </summary>
            /// <param name="customizeUnits">
            ///     A callback function for customizing the default unit mappings.
            /// </param>
            /// <returns>
            ///     A new instance of the <see cref="ElectricSusceptanceInfo"/> class with the default settings.
            /// </returns>
            public static ElectricSusceptanceInfo CreateDefault(Func<IEnumerable<UnitDefinition<ElectricSusceptanceUnit>>, IEnumerable<IUnitDefinition<ElectricSusceptanceUnit>>> customizeUnits)
                => new(nameof(ElectricSusceptance), DefaultBaseUnit, DefaultSiBaseUnit, customizeUnits(GetDefaultMappings()), new(0, DefaultBaseUnit), DefaultBaseDimensions);

            /// <summary>
            ///     The <see cref="BaseDimensions" /> for <see cref="ElectricSusceptance"/> is T^3L^-2M^-1I^2.
            /// </summary>
            public static BaseDimensions DefaultBaseDimensions
            {
                [MethodImpl(MethodImplOptions.AggressiveInlining)]
                get;
            } = new BaseDimensions(-2, -1, 3, 2, 0, 0, 0);

            /// <summary>
            ///     The default base unit of ElectricSusceptance is Siemens. All conversions, as defined in the <see cref="GetDefaultMappings"/>, go via this value.
            /// </summary>
            public static ElectricSusceptanceUnit DefaultBaseUnit
            {
                [MethodImpl(MethodImplOptions.AggressiveInlining)]
                get;
            } = ElectricSusceptanceUnit.Siemens;

            /// <summary>
            ///     The default base unit of ElectricSusceptance is Siemens.
            /// </summary>
            public static ElectricSusceptanceUnit DefaultSiBaseUnit
            {
                [MethodImpl(MethodImplOptions.AggressiveInlining)]
                get;
            } = ElectricSusceptanceUnit.Siemens;

            /// <summary>
            ///     Retrieves the default mappings for <see cref="ElectricSusceptanceUnit"/>.
            /// </summary>
            /// <returns>An <see cref="IEnumerable{T}"/> of <see cref="UnitDefinition{ElectricSusceptanceUnit}"/> representing the default unit mappings for ElectricSusceptance.</returns>
            public static IEnumerable<UnitDefinition<ElectricSusceptanceUnit>> GetDefaultMappings()
            {
                yield return new (ElectricSusceptanceUnit.Gigamho, "Gigamho", "Gigamhos", BaseUnits.Undefined,
                     new QuantityValue(1, 1000000000)
                );
                yield return new (ElectricSusceptanceUnit.Gigasiemens, "Gigasiemens", "Gigasiemens", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Microgram, time: DurationUnit.Second, current: ElectricCurrentUnit.Ampere),
                     new QuantityValue(1, 1000000000)
                );
                yield return new (ElectricSusceptanceUnit.Kilomho, "Kilomho", "Kilomhos", BaseUnits.Undefined,
                     new QuantityValue(1, 1000)
                );
                yield return new (ElectricSusceptanceUnit.Kilosiemens, "Kilosiemens", "Kilosiemens", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Gram, time: DurationUnit.Second, current: ElectricCurrentUnit.Ampere),
                     new QuantityValue(1, 1000)
                );
                yield return new (ElectricSusceptanceUnit.Megamho, "Megamho", "Megamhos", BaseUnits.Undefined,
                     new QuantityValue(1, 1000000)
                );
                yield return new (ElectricSusceptanceUnit.Megasiemens, "Megasiemens", "Megasiemens", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Milligram, time: DurationUnit.Second, current: ElectricCurrentUnit.Ampere),
                     new QuantityValue(1, 1000000)
                );
                yield return new (ElectricSusceptanceUnit.Mho, "Mho", "Mhos", BaseUnits.Undefined,
                     1
                );
                yield return new (ElectricSusceptanceUnit.Micromho, "Micromho", "Micromhos", BaseUnits.Undefined,
                     1000000
                );
                yield return new (ElectricSusceptanceUnit.Microsiemens, "Microsiemens", "Microsiemens", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Kilogram, time: DurationUnit.Second, current: ElectricCurrentUnit.Milliampere),
                     1000000
                );
                yield return new (ElectricSusceptanceUnit.Millimho, "Millimho", "Millimhos", BaseUnits.Undefined,
                     1000
                );
                yield return new (ElectricSusceptanceUnit.Millisiemens, "Millisiemens", "Millisiemens", BaseUnits.Undefined,
                     1000
                );
                yield return new (ElectricSusceptanceUnit.Nanomho, "Nanomho", "Nanomhos", BaseUnits.Undefined,
                     1000000000
                );
                yield return new (ElectricSusceptanceUnit.Nanosiemens, "Nanosiemens", "Nanosiemens", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Kilogram, time: DurationUnit.Millisecond, current: ElectricCurrentUnit.Ampere),
                     1000000000
                );
                yield return new (ElectricSusceptanceUnit.Siemens, "Siemens", "Siemens", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Kilogram, time: DurationUnit.Second, current: ElectricCurrentUnit.Ampere));
                yield return new (ElectricSusceptanceUnit.Teramho, "Teramho", "Teramhos", BaseUnits.Undefined,
                     new QuantityValue(1, 1000000000000)
                );
                yield return new (ElectricSusceptanceUnit.Terasiemens, "Terasiemens", "Terasiemens", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Nanogram, time: DurationUnit.Second, current: ElectricCurrentUnit.Ampere),
                     new QuantityValue(1, 1000000000000)
                );
            }
        }

        static ElectricSusceptance()
        {
            Info = UnitsNetSetup.CreateQuantityInfo(ElectricSusceptanceInfo.CreateDefault);
        }

        /// <summary>
        ///     Creates the quantity with the given numeric value and unit.
        /// </summary>
        /// <param name="value">The numeric value to construct this quantity with.</param>
        /// <param name="unit">The unit representation to construct this quantity with.</param>
        public ElectricSusceptance(QuantityValue value, ElectricSusceptanceUnit unit)
        {
            _value = value;
            _unit = unit;
        }

        /// <summary>
        /// Creates an instance of the quantity with the given numeric value in units compatible with the given <see cref="UnitSystem"/>.
        /// If multiple compatible units were found, the first match is used.
        /// </summary>
        /// <param name="value">The numeric value to construct this quantity with.</param>
        /// <param name="unitSystem">The unit system to create the quantity with.</param>
        /// <exception cref="ArgumentNullException">The given <see cref="UnitSystem"/> is null.</exception>
        /// <exception cref="ArgumentException">No unit was found for the given <see cref="UnitSystem"/>.</exception>
        public ElectricSusceptance(QuantityValue value, UnitSystem unitSystem)
        {
            _value = value;
            _unit = Info.GetDefaultUnit(unitSystem);
        }

        #region Static Properties

        /// <summary>
        ///     The <see cref="UnitConverter" /> containing the default generated conversion functions for <see cref="ElectricSusceptance" /> instances.
        /// </summary>
        [Obsolete("Replaced by UnitConverter.Default")]
        public static UnitConverter DefaultConversionFunctions
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => UnitConverter.Default;
        }

        /// <inheritdoc cref="IQuantity.QuantityInfo"/>
        public static QuantityInfo<ElectricSusceptance, ElectricSusceptanceUnit> Info { get; }

        /// <summary>
        ///     The <see cref="BaseDimensions" /> of this quantity.
        /// </summary>
        public static BaseDimensions BaseDimensions
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => Info.BaseDimensions;
        }

        /// <summary>
        ///     The base unit of ElectricSusceptance, which is Siemens. All conversions go via this value.
        /// </summary>
        public static ElectricSusceptanceUnit BaseUnit
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => Info.BaseUnitInfo.Value;
        }

        /// <summary>
        ///     The SI base unit of ElectricSusceptance, which is Siemens.
        /// </summary>
        public static ElectricSusceptanceUnit SiBaseUnit
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => ElectricSusceptanceUnit.Siemens;
        }

        /// <summary>
        ///     All units of measurement for the ElectricSusceptance quantity.
        /// </summary>
        public static IReadOnlyCollection<ElectricSusceptanceUnit> Units
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => Info.Units;
        }

        /// <summary>
        ///     Gets an instance of this quantity with a value of 0 in the base unit Siemens.
        /// </summary>
        public static ElectricSusceptance Zero
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => Info.Zero;
        }

        #endregion

        #region Properties

        /// <inheritdoc />
        public QuantityValue Value
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => _value;
        }

        /// <inheritdoc />
        public ElectricSusceptanceUnit Unit
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => _unit.GetValueOrDefault(BaseUnit);
        }

        /// <inheritdoc />
        public QuantityInfo<ElectricSusceptance, ElectricSusceptanceUnit> QuantityInfo
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => Info;
        }

        #region Explicit implementations

        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        UnitKey IQuantity.UnitKey
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => UnitKey.ForUnit(Unit);
        }

#if NETSTANDARD2_0
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        IQuantityInstanceInfo<ElectricSusceptance> IQuantityOfType<ElectricSusceptance>.QuantityInfo
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => Info;
        }

        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        QuantityInfo<ElectricSusceptanceUnit> IQuantity<ElectricSusceptanceUnit>.QuantityInfo
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => Info;
        }

        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        QuantityInfo IQuantity.QuantityInfo
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => Info;
        }

        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        Enum IQuantity.Unit
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => Unit;
        }
#endif

        #endregion

        #endregion

        #region Conversion Properties

        /// <inheritdoc cref="IQuantity{ElectricSusceptance,ElectricSusceptanceUnit}.AsBaseQuantity"/>
        /// <returns><see cref="ElectricSusceptanceUnit.Siemens"/></returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public ElectricSusceptance AsBaseQuantity()
            => new(this.As(BaseUnit), BaseUnit);

        /// <inheritdoc cref="IQuantity{ElectricSusceptance,ElectricSusceptanceUnit}.AsBaseValue"/>
        /// <returns><see cref="ElectricSusceptanceUnit.Siemens"/></returns>
        [Obsolete("Yields unpredictable results with non bare SI based units")]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public QuantityValue AsBaseValue()
            => this.As(BaseUnit);

        /// <inheritdoc cref="IQuantity{ElectricSusceptance,ElectricSusceptanceUnit}.AsBaseQuantity"/>
        /// <returns><see cref="ElectricSusceptanceUnit.Siemens"/></returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public ElectricSusceptance AsSiBaseQuantity()
            => new(this.As(SiBaseUnit), SiBaseUnit);

        /// <inheritdoc cref="IQuantity{ElectricSusceptance,ElectricSusceptanceUnit}.AsBaseValue"/>
        /// <returns><see cref="ElectricSusceptanceUnit.Siemens"/></returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public QuantityValue AsSiBaseValue()
            => this.As(SiBaseUnit);

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="ElectricSusceptanceUnit.Gigamho"/>
        /// </summary>
        public QuantityValue Gigamhos
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(ElectricSusceptanceUnit.Gigamho);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="ElectricSusceptanceUnit.Gigasiemens"/>
        /// </summary>
        public QuantityValue Gigasiemens
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(ElectricSusceptanceUnit.Gigasiemens);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="ElectricSusceptanceUnit.Kilomho"/>
        /// </summary>
        public QuantityValue Kilomhos
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(ElectricSusceptanceUnit.Kilomho);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="ElectricSusceptanceUnit.Kilosiemens"/>
        /// </summary>
        public QuantityValue Kilosiemens
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(ElectricSusceptanceUnit.Kilosiemens);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="ElectricSusceptanceUnit.Megamho"/>
        /// </summary>
        public QuantityValue Megamhos
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(ElectricSusceptanceUnit.Megamho);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="ElectricSusceptanceUnit.Megasiemens"/>
        /// </summary>
        public QuantityValue Megasiemens
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(ElectricSusceptanceUnit.Megasiemens);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="ElectricSusceptanceUnit.Mho"/>
        /// </summary>
        public QuantityValue Mhos
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(ElectricSusceptanceUnit.Mho);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="ElectricSusceptanceUnit.Micromho"/>
        /// </summary>
        public QuantityValue Micromhos
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(ElectricSusceptanceUnit.Micromho);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="ElectricSusceptanceUnit.Microsiemens"/>
        /// </summary>
        public QuantityValue Microsiemens
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(ElectricSusceptanceUnit.Microsiemens);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="ElectricSusceptanceUnit.Millimho"/>
        /// </summary>
        public QuantityValue Millimhos
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(ElectricSusceptanceUnit.Millimho);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="ElectricSusceptanceUnit.Millisiemens"/>
        /// </summary>
        public QuantityValue Millisiemens
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(ElectricSusceptanceUnit.Millisiemens);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="ElectricSusceptanceUnit.Nanomho"/>
        /// </summary>
        public QuantityValue Nanomhos
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(ElectricSusceptanceUnit.Nanomho);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="ElectricSusceptanceUnit.Nanosiemens"/>
        /// </summary>
        public QuantityValue Nanosiemens
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(ElectricSusceptanceUnit.Nanosiemens);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="ElectricSusceptanceUnit.Siemens"/>
        /// </summary>
        public QuantityValue Siemens
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(ElectricSusceptanceUnit.Siemens);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="ElectricSusceptanceUnit.Teramho"/>
        /// </summary>
        public QuantityValue Teramhos
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(ElectricSusceptanceUnit.Teramho);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="ElectricSusceptanceUnit.Terasiemens"/>
        /// </summary>
        public QuantityValue Terasiemens
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(ElectricSusceptanceUnit.Terasiemens);
        }

        #endregion

        #region Static Methods

        /// <summary>
        ///     Get unit abbreviation string.
        /// </summary>
        /// <param name="unit">Unit to get abbreviation for.</param>
        /// <returns>Unit abbreviation string.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static string GetAbbreviation(ElectricSusceptanceUnit unit)
            => GetAbbreviation(unit, null);

        /// <summary>
        ///     Get unit abbreviation string.
        /// </summary>
        /// <param name="unit">Unit to get abbreviation for.</param>
        /// <returns>Unit abbreviation string.</returns>
        /// <param name="provider">Format to use for localization. Defaults to <see cref="CultureInfo.CurrentCulture" /> if null.</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static string GetAbbreviation(ElectricSusceptanceUnit unit, IFormatProvider? provider)
            => UnitsNetSetup.Default.UnitAbbreviations.GetDefaultAbbreviation(unit, provider);

        #endregion

        #region Static Factory Methods

        /// <summary>
        ///     Convert to base unit quantity of Siemens.
        /// </summary>
        public ElectricSusceptance SiemensToBaseElectricSusceptance()
            => new(this.As(BaseUnit), BaseUnit);

        /// <summary>
        ///     Convert to base unit quantity of Siemens.
        /// </summary>
        public ElectricSusceptance SiemensToSiBaseElectricSusceptance()
            => new(this.As(SiBaseUnit), SiBaseUnit);

        /// <summary>
        ///     Creates a <see cref="ElectricSusceptance"/> from <see cref="ElectricSusceptanceUnit.Gigamho"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ElectricSusceptance FromGigamhos(QuantityValue value)
            => new(value, ElectricSusceptanceUnit.Gigamho);

        /// <summary>
        ///     Creates a <see cref="ElectricSusceptance"/> from <see cref="ElectricSusceptanceUnit.Gigasiemens"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ElectricSusceptance FromGigasiemens(QuantityValue value)
            => new(value, ElectricSusceptanceUnit.Gigasiemens);

        /// <summary>
        ///     Creates a <see cref="ElectricSusceptance"/> from <see cref="ElectricSusceptanceUnit.Kilomho"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ElectricSusceptance FromKilomhos(QuantityValue value)
            => new(value, ElectricSusceptanceUnit.Kilomho);

        /// <summary>
        ///     Creates a <see cref="ElectricSusceptance"/> from <see cref="ElectricSusceptanceUnit.Kilosiemens"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ElectricSusceptance FromKilosiemens(QuantityValue value)
            => new(value, ElectricSusceptanceUnit.Kilosiemens);

        /// <summary>
        ///     Creates a <see cref="ElectricSusceptance"/> from <see cref="ElectricSusceptanceUnit.Megamho"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ElectricSusceptance FromMegamhos(QuantityValue value)
            => new(value, ElectricSusceptanceUnit.Megamho);

        /// <summary>
        ///     Creates a <see cref="ElectricSusceptance"/> from <see cref="ElectricSusceptanceUnit.Megasiemens"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ElectricSusceptance FromMegasiemens(QuantityValue value)
            => new(value, ElectricSusceptanceUnit.Megasiemens);

        /// <summary>
        ///     Creates a <see cref="ElectricSusceptance"/> from <see cref="ElectricSusceptanceUnit.Mho"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ElectricSusceptance FromMhos(QuantityValue value)
            => new(value, ElectricSusceptanceUnit.Mho);

        /// <summary>
        ///     Creates a <see cref="ElectricSusceptance"/> from <see cref="ElectricSusceptanceUnit.Micromho"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ElectricSusceptance FromMicromhos(QuantityValue value)
            => new(value, ElectricSusceptanceUnit.Micromho);

        /// <summary>
        ///     Creates a <see cref="ElectricSusceptance"/> from <see cref="ElectricSusceptanceUnit.Microsiemens"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ElectricSusceptance FromMicrosiemens(QuantityValue value)
            => new(value, ElectricSusceptanceUnit.Microsiemens);

        /// <summary>
        ///     Creates a <see cref="ElectricSusceptance"/> from <see cref="ElectricSusceptanceUnit.Millimho"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ElectricSusceptance FromMillimhos(QuantityValue value)
            => new(value, ElectricSusceptanceUnit.Millimho);

        /// <summary>
        ///     Creates a <see cref="ElectricSusceptance"/> from <see cref="ElectricSusceptanceUnit.Millisiemens"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ElectricSusceptance FromMillisiemens(QuantityValue value)
            => new(value, ElectricSusceptanceUnit.Millisiemens);

        /// <summary>
        ///     Creates a <see cref="ElectricSusceptance"/> from <see cref="ElectricSusceptanceUnit.Nanomho"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ElectricSusceptance FromNanomhos(QuantityValue value)
            => new(value, ElectricSusceptanceUnit.Nanomho);

        /// <summary>
        ///     Creates a <see cref="ElectricSusceptance"/> from <see cref="ElectricSusceptanceUnit.Nanosiemens"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ElectricSusceptance FromNanosiemens(QuantityValue value)
            => new(value, ElectricSusceptanceUnit.Nanosiemens);

        /// <summary>
        ///     Creates a <see cref="ElectricSusceptance"/> from <see cref="ElectricSusceptanceUnit.Siemens"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ElectricSusceptance FromSiemens(QuantityValue value)
            => new(value, ElectricSusceptanceUnit.Siemens);

        /// <summary>
        ///     Creates a <see cref="ElectricSusceptance"/> from <see cref="ElectricSusceptanceUnit.Teramho"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ElectricSusceptance FromTeramhos(QuantityValue value)
            => new(value, ElectricSusceptanceUnit.Teramho);

        /// <summary>
        ///     Creates a <see cref="ElectricSusceptance"/> from <see cref="ElectricSusceptanceUnit.Terasiemens"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ElectricSusceptance FromTerasiemens(QuantityValue value)
            => new(value, ElectricSusceptanceUnit.Terasiemens);

        /// <summary>
        ///     Dynamically convert from value and unit enum <see cref="ElectricSusceptanceUnit" /> to <see cref="ElectricSusceptance" />.
        /// </summary>
        /// <param name="value">Value to convert from.</param>
        /// <param name="fromUnit">Unit to convert from.</param>
        /// <returns>ElectricSusceptance unit value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ElectricSusceptance From(QuantityValue value, ElectricSusceptanceUnit fromUnit)
            => new(value, fromUnit);

        #endregion

        #region Static Parse Methods

        /// <summary>
        ///     Parse a string with one or two quantities of the format "&lt;quantity&gt; &lt;unit&gt;".
        /// </summary>
        /// <param name="str">String to parse. Typically in the form: {number} {unit}</param>
        /// <example>
        ///     Length.Parse("5.5 m", CultureInfo.GetCultureInfo("en-US"));
        /// </example>
        /// <exception cref="ArgumentNullException">The value of 'str' cannot be null. </exception>
        /// <exception cref="ArgumentException">
        ///     Expected string to have one or two pairs of quantity and unit in the format
        ///     "&lt;quantity&gt; &lt;unit&gt;". Eg. "5.5 m" or "1ft 2in"
        /// </exception>
        /// <exception cref="AmbiguousUnitParseException">
        ///     More than one unit is represented by the specified unit abbreviation.
        ///     Example: Volume.Parse("1 cup") will throw, because it can refer to any of
        ///     <see cref="VolumeUnit.MetricCup" />, <see cref="VolumeUnit.UsLegalCup" /> and <see cref="VolumeUnit.UsCustomaryCup" />.
        /// </exception>
        /// <exception cref="UnitsNetException">
        ///     If anything else goes wrong, typically due to a bug or unhandled case.
        ///     We wrap exceptions in <see cref="UnitsNetException" /> to allow you to distinguish
        ///     Units.NET exceptions from other exceptions.
        /// </exception>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ElectricSusceptance Parse(string str)
            => Parse(str, null);

        /// <summary>
        ///     Parse a string with one or two quantities of the format "&lt;quantity&gt; &lt;unit&gt;".
        /// </summary>
        /// <param name="str">String to parse. Typically in the form: {number} {unit}</param>
        /// <example>
        ///     Length.Parse("5.5 m", CultureInfo.GetCultureInfo("en-US"));
        /// </example>
        /// <exception cref="ArgumentNullException">The value of 'str' cannot be null. </exception>
        /// <exception cref="ArgumentException">
        ///     Expected string to have one or two pairs of quantity and unit in the format
        ///     "&lt;quantity&gt; &lt;unit&gt;". Eg. "5.5 m" or "1ft 2in"
        /// </exception>
        /// <exception cref="AmbiguousUnitParseException">
        ///     More than one unit is represented by the specified unit abbreviation.
        ///     Example: Volume.Parse("1 cup") will throw, because it can refer to any of
        ///     <see cref="VolumeUnit.MetricCup" />, <see cref="VolumeUnit.UsLegalCup" /> and <see cref="VolumeUnit.UsCustomaryCup" />.
        /// </exception>
        /// <exception cref="UnitsNetException">
        ///     If anything else goes wrong, typically due to a bug or unhandled case.
        ///     We wrap exceptions in <see cref="UnitsNetException" /> to allow you to distinguish
        ///     Units.NET exceptions from other exceptions.
        /// </exception>
        /// <param name="provider">Format to use when parsing number and unit. Defaults to <see cref="CultureInfo.CurrentCulture" /> if null.</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ElectricSusceptance Parse(string str, IFormatProvider? provider)
            => QuantityParser.Default.Parse<ElectricSusceptance, ElectricSusceptanceUnit>(str, provider, From);

        /// <summary>
        ///     Try to parse a string with one or two quantities of the format "&lt;quantity&gt; &lt;unit&gt;".
        /// </summary>
        /// <param name="str">String to parse. Typically in the form: {number} {unit}</param>
        /// <param name="result">Resulting unit quantity if successful.</param>
        /// <example>
        ///     Length.Parse("5.5 m", CultureInfo.GetCultureInfo("en-US"));
        /// </example>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool TryParse([NotNullWhen(true)]string? str, out ElectricSusceptance result)
            => TryParse(str, null, out result);

        /// <summary>
        ///     Try to parse a string with one or two quantities of the format "&lt;quantity&gt; &lt;unit&gt;".
        /// </summary>
        /// <param name="str">String to parse. Typically in the form: {number} {unit}</param>
        /// <param name="result">Resulting unit quantity if successful.</param>
        /// <returns>True if successful, otherwise false.</returns>
        /// <example>
        ///     Length.Parse("5.5 m", CultureInfo.GetCultureInfo("en-US"));
        /// </example>
        /// <param name="provider">Format to use when parsing number and unit. Defaults to <see cref="CultureInfo.CurrentCulture" /> if null.</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool TryParse([NotNullWhen(true)]string? str, IFormatProvider? provider, out ElectricSusceptance result)
            => QuantityParser.Default.TryParse<ElectricSusceptance, ElectricSusceptanceUnit>(str, provider, From, out result);

        /// <summary>
        ///     Parse a unit string.
        /// </summary>
        /// <param name="str">String to parse. Typically in the form: {number} {unit}</param>
        /// <example>
        ///     Length.ParseUnit("m", CultureInfo.GetCultureInfo("en-US"));
        /// </example>
        /// <exception cref="ArgumentNullException">The value of 'str' cannot be null. </exception>
        /// <exception cref="UnitsNetException">Error parsing string.</exception>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ElectricSusceptanceUnit ParseUnit(string str)
            => ParseUnit(str, null);

        /// <summary>
        ///     Parse a unit string.
        /// </summary>
        /// <param name="str">String to parse. Typically in the form: {number} {unit}</param>
        /// <param name="provider">Format to use when parsing the unit. Defaults to <see cref="CultureInfo.CurrentCulture" /> if null.</param>
        /// <example>
        ///     Length.ParseUnit("m", CultureInfo.GetCultureInfo("en-US"));
        /// </example>
        /// <exception cref="ArgumentNullException">The value of 'str' cannot be null. </exception>
        /// <exception cref="UnitsNetException">Error parsing string.</exception>
        public static ElectricSusceptanceUnit ParseUnit(string str, IFormatProvider? provider)
            => UnitParser.Default.Parse(str, Info.UnitInfos, provider).Value;

        /// <inheritdoc cref="TryParseUnit(string,IFormatProvider?,out UnitsNet.Units.ElectricSusceptanceUnit)"/>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool TryParseUnit([NotNullWhen(true)]string? str, out ElectricSusceptanceUnit unit)
            => TryParseUnit(str, null, out unit);

        /// <summary>
        ///     Parse a unit string.
        /// </summary>
        /// <param name="str">String to parse. Typically in the form: {number} {unit}</param>
        /// <param name="unit">The parsed unit if successful.</param>
        /// <returns>True if successful, otherwise false.</returns>
        /// <example>
        ///     Length.TryParseUnit("m", CultureInfo.GetCultureInfo("en-US"));
        /// </example>
        /// <param name="provider">Format to use when parsing the unit. Defaults to <see cref="CultureInfo.CurrentCulture" /> if null.</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool TryParseUnit([NotNullWhen(true)]string? str, IFormatProvider? provider, out ElectricSusceptanceUnit unit)
            => UnitParser.Default.TryParse(str, Info, provider, out unit);

        #endregion

        /// <summary>
        /// Gets value of base unit.
        /// </summary>
        /// <param name="d"></param>
        [Obsolete("Gets value of base unit. Use factory methods instead to specify unit conversion.")]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator QuantityValue(ElectricSusceptance d) => d.As(BaseUnit);

        /// <summary>
        /// Gets quantity of base unit.
        /// </summary>
        /// <param name="d"></param>
        [Obsolete("Gets value of base unit. Use factory methods instead to specify unit conversion.")]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator ElectricSusceptance(QuantityValue d) => new(d, BaseUnit);

        /// <summary>
        /// Gets value of base unit.
        /// </summary>
        /// <param name="d"></param>
        [Obsolete("Gets value of base unit. Use factory methods instead to specify unit conversion.")]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static explicit operator double(ElectricSusceptance d) => d.As(BaseUnit);

        /// <summary>
        /// Gets quantity of base unit.
        /// </summary>
        /// <param name="d"></param>
        [Obsolete("Gets value of base unit. Use factory methods instead to specify unit conversion.")]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static explicit operator ElectricSusceptance(double d) => new(d, BaseUnit);

        #region Arithmetic Operators

        /// <summary>Negate the value.</summary>
        public static ElectricSusceptance operator -(ElectricSusceptance right)
            => new(-right.Value, right.Unit);

        /// <summary>Get <see cref="ElectricSusceptance"/> from adding two <see cref="ElectricSusceptance"/>.</summary>
        public static ElectricSusceptance operator +(ElectricSusceptance left, ElectricSusceptance right)
            => new(left.Value + right.As(left.Unit), left.Unit);

        /// <summary>Get <see cref="ElectricSusceptance"/> from subtracting two <see cref="ElectricSusceptance"/>.</summary>
        public static ElectricSusceptance operator -(ElectricSusceptance left, ElectricSusceptance right)
            => new(left.Value - right.As(left.Unit), left.Unit);

        /// <summary>Get <see cref="ElectricSusceptance"/> from multiplying value and <see cref="ElectricSusceptance"/>.</summary>
        public static ElectricSusceptance operator *(QuantityValue left, ElectricSusceptance right)
            => new(left * right.Value, right.Unit);

        /// <summary>Get <see cref="ElectricSusceptance"/> from multiplying value and <see cref="ElectricSusceptance"/>.</summary>
        public static ElectricSusceptance operator *(ElectricSusceptance left, QuantityValue right)
            => new(left.Value * right, left.Unit);

        /// <summary>Get <see cref="ElectricSusceptance"/> from dividing <see cref="ElectricSusceptance"/> by value.</summary>
        public static ElectricSusceptance operator /(ElectricSusceptance left, QuantityValue right)
            => new(left.Value / right, left.Unit);

        /// <summary>Get ratio value from dividing <see cref="ElectricSusceptance"/> by <see cref="ElectricSusceptance"/>.</summary>
        public static QuantityValue operator /(ElectricSusceptance left, ElectricSusceptance right)
            => left.Siemens / right.Siemens;

        #endregion

        #region Relational Operators

        /// <summary>Calculates the inverse of this quantity.</summary>
        /// <returns>The corresponding inverse quantity, <see cref="ElectricReactance"/>.</returns>
        public ElectricReactance Inverse()
            => UnitConverter.Default.ConvertTo(Value, Unit, ElectricReactance.Info);

        #endregion

        #region Equality / IComparable

        /// <summary>Returns true if less or equal to.</summary>
        public static bool operator <=(ElectricSusceptance left, ElectricSusceptance right)
            => left.Value <= right.As(left.Unit);

        /// <summary>Returns true if greater than or equal to.</summary>
        public static bool operator >=(ElectricSusceptance left, ElectricSusceptance right)
            => left.Value >= right.As(left.Unit);

        /// <summary>Returns true if less than.</summary>
        public static bool operator <(ElectricSusceptance left, ElectricSusceptance right)
            => left.Value < right.As(left.Unit);

        /// <summary>Returns true if greater than.</summary>
        public static bool operator >(ElectricSusceptance left, ElectricSusceptance right)
            => left.Value > right.As(left.Unit);

        /// <summary>
        ///     Determines whether two <see cref="ElectricSusceptance"/> instances are equal.
        /// </summary>
        /// <remarks>
        ///     Equality is evaluated in a unit-aware manner. The right-hand operand is converted to the unit of the left-hand
        ///     operand and then the underlying numeric values are compared.
        ///     This means two quantities with numerically equal values but different units will be considered equal.
        ///     The operator delegates to <see cref="Equals(ElectricSusceptance)"/>, which implements this conversion-and-compare logic.
        /// </remarks>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool operator ==(ElectricSusceptance left, ElectricSusceptance right)
            => left.Equals(right);

        /// <summary>
        ///     Determines whether two <see cref="ElectricSusceptance"/> instances are not equal.
        /// </summary>
        /// <remarks>
        ///     This operator is the logical negation of <see cref="operator ==(ElectricSusceptance,ElectricSusceptance)"/>.
        ///     See that operator (and <see cref="Equals(ElectricSusceptance)"/>) for details on how equality is evaluated
        ///     (i.e., by converting one operand to the other's unit and comparing their numeric values).
        /// </remarks>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool operator !=(ElectricSusceptance left, ElectricSusceptance right)
            => !(left == right);

        /// <inheritdoc />
        /// <summary>
        ///     Determines whether the specified object is equal to the current <see cref="ElectricSusceptance"/> instance.
        /// </summary>
        /// <remarks>
        ///     Returns <c>false</c> if <paramref name="obj"/> is <c>null</c> or not a <see cref="ElectricSusceptance"/>.
        ///     When <paramref name="obj"/> is a <see cref="ElectricSusceptance"/>, this method delegates to
        ///     <see cref="Equals(ElectricSusceptance)"/>, which performs a unit-aware comparison by converting the other
        ///     instance to this instance's unit before comparing numeric values.
        /// </remarks>
        public override bool Equals(object? obj)
            => obj is ElectricSusceptance otherQuantity && Equals(otherQuantity);

        /// <inheritdoc />
        /// <summary>
        ///     Determines whether the current instance is equal to another <see cref="ElectricSusceptance"/> instance.
        /// </summary>
        /// <remarks>
        ///     Comparison is performed by converting <paramref name="other"/> to this instance's unit and then comparing the underlying numeric values.
        ///     This makes two quantities equal even when their units differ, provided the converted numeric values are equal.
        /// </remarks>
        public bool Equals(ElectricSusceptance other)
            => _value.Equals(other.As(Unit));

        /// <summary>
        ///     Returns the hash code for this instance.
        /// </summary>
        /// <returns>A hash code for the current ElectricSusceptance.</returns>
        public override int GetHashCode()
            => Comparison.GetHashCode(typeof(ElectricSusceptance), this.As(BaseUnit));

        /// <inheritdoc  cref="CompareTo(ElectricSusceptance)" />
        /// <param name="obj">An object to compare with this instance.</param>
        /// <exception cref="T:System.ArgumentException">
        ///    <paramref name="obj" /> is not the same type as this instance.
        /// </exception>
        public int CompareTo(object? obj)
        {
            if (obj is not ElectricSusceptance otherQuantity)
                throw obj is null ? new ArgumentNullException(nameof(obj)) : ExceptionHelper.CreateArgumentException<ElectricSusceptance>(obj, nameof(obj));

            return CompareTo(otherQuantity);
        }

        /// <summary>
        ///     Compares the current <see cref="ElectricSusceptance"/> with another <see cref="ElectricSusceptance"/> and returns an integer that indicates
        ///     whether the current instance precedes, follows, or occurs in the same position in the sort order as the other quantity, when converted to the same unit.
        /// </summary>
        /// <param name="other">A quantity to compare with this instance.</param>
        /// <returns>A value that indicates the relative order of the quantities being compared. The return value has these meanings:
        ///     <list type="table">
        ///         <listheader><term> Value</term><description> Meaning</description></listheader>
        ///         <item><term> Less than zero</term><description> This instance precedes <paramref name="other" /> in the sort order.</description></item>
        ///         <item><term> Zero</term><description> This instance occurs in the same position in the sort order as <paramref name="other" />.</description></item>
        ///         <item><term> Greater than zero</term><description> This instance follows <paramref name="other" /> in the sort order.</description></item>
        ///     </list>
        /// </returns>
        public int CompareTo(ElectricSusceptance other)
            => _value.CompareTo(other.As(Unit));

        #endregion

        #region ToString Methods

        /// <summary>
        ///     Gets the default string representation of value and unit.
        /// </summary>
        /// <returns>String representation.</returns>
        public override string ToString()
            => ToString(null, null);

        /// <inheritdoc cref="QuantityFormatter.Format{TQuantity}(TQuantity, string, IFormatProvider)"/>
        /// <summary>
        /// Gets the string representation of this instance in the specified format string using the specified format provider, or <see cref="CultureInfo.CurrentCulture" /> if null.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public string ToString(
            [StringSyntax(StringSyntaxAttribute.NumericFormat)] string? format,
            IFormatProvider? provider)
            => QuantityFormatter.Default.Format(this, format, provider);

        #endregion

    }
}
