//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

using System.Globalization;
using System.Resources;
using System.Runtime.Serialization;
using UnitsNet.Debug;
using System.Runtime.CompilerServices;

#nullable enable

// ReSharper disable once CheckNamespace

namespace UnitsNet
{
    /// <inheritdoc />
    /// <summary>
    ///     Amount of ionizing radiation released when an element spontaneously emits energy as a result of the radioactive decay of an unstable atom per unit time.
    /// </summary>
    [DataContract]
    [DebuggerDisplay(QuantityDebugProxy.DisplayFormat)]
    [DebuggerTypeProxy(typeof(QuantityDebugProxy))]
    public readonly partial struct Radioactivity :
        ILinearQuantity<Radioactivity, RadioactivityUnit>,
#if NET7_0_OR_GREATER
        IDivisionOperators<Radioactivity, Radioactivity, QuantityValue>,
        IComparisonOperators<Radioactivity, Radioactivity, bool>,
        IParsable<Radioactivity>,
#endif
        IComparable,
        IComparable<Radioactivity>,
        IEquatable<Radioactivity>,
        IFormattable
    {
        /// <summary>
        ///     The numeric value this quantity was constructed with.
        /// </summary>
        [DataMember(Name = "Value", Order = 1)]
        private readonly QuantityValue _value;

        /// <summary>
        ///     The unit this quantity was constructed with.
        /// </summary>
        [DataMember(Name = "Unit", Order = 2)]
        private readonly RadioactivityUnit? _unit;

        /// <summary>
        ///     Provides detailed information about the <see cref="Radioactivity"/> quantity, including its name, base unit, unit mappings, base dimensions, and conversion functions.
        /// </summary>
        public sealed class RadioactivityInfo : QuantityInfo<Radioactivity, RadioactivityUnit>
        {
            /// <inheritdoc />
            public RadioactivityInfo(string name, RadioactivityUnit baseUnit, IEnumerable<IUnitDefinition<RadioactivityUnit>> unitMappings, Radioactivity zero, BaseDimensions baseDimensions,
                QuantityFromDelegate<Radioactivity, RadioactivityUnit> fromDelegate, ResourceManager? unitAbbreviations)
                : base(name, baseUnit, unitMappings, zero, baseDimensions, fromDelegate, unitAbbreviations)
            {
            }

            /// <inheritdoc />
            public RadioactivityInfo(string name, RadioactivityUnit baseUnit, IEnumerable<IUnitDefinition<RadioactivityUnit>> unitMappings, Radioactivity zero, BaseDimensions baseDimensions)
                : this(name, baseUnit, unitMappings, zero, baseDimensions, Radioactivity.From, new ResourceManager("UnitsNet.GeneratedCode.Resources.Radioactivity", typeof(Radioactivity).Assembly))
            {
            }

            /// <summary>
            ///     Creates a new instance of the <see cref="RadioactivityInfo"/> class with the default settings for the Radioactivity quantity.
            /// </summary>
            /// <returns>A new instance of the <see cref="RadioactivityInfo"/> class with the default settings.</returns>
            public static RadioactivityInfo CreateDefault()
                => new(nameof(Radioactivity), DefaultBaseUnit, GetDefaultMappings(), new(0, DefaultBaseUnit), DefaultBaseDimensions);

            /// <summary>
            ///     Creates a new instance of the <see cref="RadioactivityInfo"/> class with the default settings for the Radioactivity quantity and a callback for customizing the default unit mappings.
            /// </summary>
            /// <param name="customizeUnits">
            ///     A callback function for customizing the default unit mappings.
            /// </param>
            /// <returns>
            ///     A new instance of the <see cref="RadioactivityInfo"/> class with the default settings.
            /// </returns>
            public static RadioactivityInfo CreateDefault(Func<IEnumerable<UnitDefinition<RadioactivityUnit>>, IEnumerable<IUnitDefinition<RadioactivityUnit>>> customizeUnits)
                => new(nameof(Radioactivity), DefaultBaseUnit, customizeUnits(GetDefaultMappings()), new(0, DefaultBaseUnit), DefaultBaseDimensions);

            /// <summary>
            ///     The <see cref="BaseDimensions" /> for <see cref="Radioactivity"/> is T^-1.
            /// </summary>
            public static BaseDimensions DefaultBaseDimensions
            {
                [MethodImpl(MethodImplOptions.AggressiveInlining)]
                get;
            } = new BaseDimensions(0, 0, -1, 0, 0, 0, 0);

            /// <summary>
            ///     The default base unit of Radioactivity is Becquerel. All conversions, as defined in the <see cref="GetDefaultMappings"/>, go via this value.
            /// </summary>
            public static RadioactivityUnit DefaultBaseUnit
            {
                [MethodImpl(MethodImplOptions.AggressiveInlining)]
                get;
            } = RadioactivityUnit.Becquerel;

            /// <summary>
            ///     Retrieves the default mappings for <see cref="RadioactivityUnit"/>.
            /// </summary>
            /// <returns>An <see cref="IEnumerable{T}"/> of <see cref="UnitDefinition{RadioactivityUnit}"/> representing the default unit mappings for Radioactivity.</returns>
            public static IEnumerable<UnitDefinition<RadioactivityUnit>> GetDefaultMappings()
            {
                yield return new (RadioactivityUnit.Becquerel, "Becquerel", "Becquerels", new BaseUnits(time: DurationUnit.Second));
                yield return new (RadioactivityUnit.Curie, "Curie", "Curies", new BaseUnits(time: DurationUnit.Second),
                     new QuantityValue(1, 37000000000)
                );
                yield return new (RadioactivityUnit.Exabecquerel, "Exabecquerel", "Exabecquerels", BaseUnits.Undefined,
                     new QuantityValue(1, 1000000000000000000)
                );
                yield return new (RadioactivityUnit.Gigabecquerel, "Gigabecquerel", "Gigabecquerels", new BaseUnits(time: DurationUnit.Nanosecond),
                     new QuantityValue(1, 1000000000)
                );
                yield return new (RadioactivityUnit.Gigacurie, "Gigacurie", "Gigacuries", new BaseUnits(time: DurationUnit.Nanosecond),
                     new QuantityValue(1, new BigInteger(37) * QuantityValue.PowerOfTen(18))
                );
                yield return new (RadioactivityUnit.Gigarutherford, "Gigarutherford", "Gigarutherfords", new BaseUnits(time: DurationUnit.Nanosecond),
                     new QuantityValue(1, 1000000000000000)
                );
                yield return new (RadioactivityUnit.Kilobecquerel, "Kilobecquerel", "Kilobecquerels", new BaseUnits(time: DurationUnit.Millisecond),
                     new QuantityValue(1, 1000)
                );
                yield return new (RadioactivityUnit.Kilocurie, "Kilocurie", "Kilocuries", new BaseUnits(time: DurationUnit.Millisecond),
                     new QuantityValue(1, 37000000000000)
                );
                yield return new (RadioactivityUnit.Kilorutherford, "Kilorutherford", "Kilorutherfords", new BaseUnits(time: DurationUnit.Millisecond),
                     new QuantityValue(1, 1000000000)
                );
                yield return new (RadioactivityUnit.Megabecquerel, "Megabecquerel", "Megabecquerels", new BaseUnits(time: DurationUnit.Microsecond),
                     new QuantityValue(1, 1000000)
                );
                yield return new (RadioactivityUnit.Megacurie, "Megacurie", "Megacuries", new BaseUnits(time: DurationUnit.Microsecond),
                     new QuantityValue(1, 37000000000000000)
                );
                yield return new (RadioactivityUnit.Megarutherford, "Megarutherford", "Megarutherfords", new BaseUnits(time: DurationUnit.Microsecond),
                     new QuantityValue(1, 1000000000000)
                );
                yield return new (RadioactivityUnit.Microbecquerel, "Microbecquerel", "Microbecquerels", BaseUnits.Undefined,
                     1000000
                );
                yield return new (RadioactivityUnit.Microcurie, "Microcurie", "Microcuries", BaseUnits.Undefined,
                     new QuantityValue(1, 37000)
                );
                yield return new (RadioactivityUnit.Microrutherford, "Microrutherford", "Microrutherfords", BaseUnits.Undefined,
                     1
                );
                yield return new (RadioactivityUnit.Millibecquerel, "Millibecquerel", "Millibecquerels", BaseUnits.Undefined,
                     1000
                );
                yield return new (RadioactivityUnit.Millicurie, "Millicurie", "Millicuries", BaseUnits.Undefined,
                     new QuantityValue(1, 37000000)
                );
                yield return new (RadioactivityUnit.Millirutherford, "Millirutherford", "Millirutherfords", BaseUnits.Undefined,
                     new QuantityValue(1, 1000)
                );
                yield return new (RadioactivityUnit.Nanobecquerel, "Nanobecquerel", "Nanobecquerels", BaseUnits.Undefined,
                     1000000000
                );
                yield return new (RadioactivityUnit.Nanocurie, "Nanocurie", "Nanocuries", BaseUnits.Undefined,
                     new QuantityValue(1, 37)
                );
                yield return new (RadioactivityUnit.Nanorutherford, "Nanorutherford", "Nanorutherfords", BaseUnits.Undefined,
                     1000
                );
                yield return new (RadioactivityUnit.Petabecquerel, "Petabecquerel", "Petabecquerels", BaseUnits.Undefined,
                     new QuantityValue(1, 1000000000000000)
                );
                yield return new (RadioactivityUnit.Picobecquerel, "Picobecquerel", "Picobecquerels", BaseUnits.Undefined,
                     1000000000000
                );
                yield return new (RadioactivityUnit.Picocurie, "Picocurie", "Picocuries", BaseUnits.Undefined,
                     new QuantityValue(1000, 37)
                );
                yield return new (RadioactivityUnit.Picorutherford, "Picorutherford", "Picorutherfords", BaseUnits.Undefined,
                     1000000
                );
                yield return new (RadioactivityUnit.Rutherford, "Rutherford", "Rutherfords", new BaseUnits(time: DurationUnit.Second),
                     new QuantityValue(1, 1000000)
                );
                yield return new (RadioactivityUnit.Terabecquerel, "Terabecquerel", "Terabecquerels", new BaseUnits(time: DurationUnit.Picosecond),
                     new QuantityValue(1, 1000000000000)
                );
                yield return new (RadioactivityUnit.Teracurie, "Teracurie", "Teracuries", new BaseUnits(time: DurationUnit.Picosecond),
                     new QuantityValue(1, new BigInteger(37) * QuantityValue.PowerOfTen(21))
                );
                yield return new (RadioactivityUnit.Terarutherford, "Terarutherford", "Terarutherfords", new BaseUnits(time: DurationUnit.Picosecond),
                     new QuantityValue(1, 1000000000000000000)
                );
            }
        }

        static Radioactivity()
        {
            Info = UnitsNetSetup.CreateQuantityInfo(RadioactivityInfo.CreateDefault);
        }

        /// <summary>
        ///     Creates the quantity with the given numeric value and unit.
        /// </summary>
        /// <param name="value">The numeric value to construct this quantity with.</param>
        /// <param name="unit">The unit representation to construct this quantity with.</param>
        public Radioactivity(QuantityValue value, RadioactivityUnit unit)
        {
            _value = value;
            _unit = unit;
        }

        /// <summary>
        /// Creates an instance of the quantity with the given numeric value in units compatible with the given <see cref="UnitSystem"/>.
        /// If multiple compatible units were found, the first match is used.
        /// </summary>
        /// <param name="value">The numeric value to construct this quantity with.</param>
        /// <param name="unitSystem">The unit system to create the quantity with.</param>
        /// <exception cref="ArgumentNullException">The given <see cref="UnitSystem"/> is null.</exception>
        /// <exception cref="ArgumentException">No unit was found for the given <see cref="UnitSystem"/>.</exception>
        public Radioactivity(QuantityValue value, UnitSystem unitSystem)
        {
            _value = value;
            _unit = Info.GetDefaultUnit(unitSystem);
        }

        #region Static Properties

        /// <summary>
        ///     The <see cref="UnitConverter" /> containing the default generated conversion functions for <see cref="Radioactivity" /> instances.
        /// </summary>
        [Obsolete("Replaced by UnitConverter.Default")]
        public static UnitConverter DefaultConversionFunctions
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => UnitConverter.Default;
        }

        /// <inheritdoc cref="IQuantity.QuantityInfo"/>
        public static QuantityInfo<Radioactivity, RadioactivityUnit> Info { get; }

        /// <summary>
        ///     The <see cref="BaseDimensions" /> of this quantity.
        /// </summary>
        public static BaseDimensions BaseDimensions
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => Info.BaseDimensions;
        }

        /// <summary>
        ///     The base unit of Radioactivity, which is Becquerel. All conversions go via this value.
        /// </summary>
        public static RadioactivityUnit BaseUnit
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => Info.BaseUnitInfo.Value;
        }

        /// <summary>
        ///     All units of measurement for the Radioactivity quantity.
        /// </summary>
        public static IReadOnlyCollection<RadioactivityUnit> Units
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => Info.Units;
        }

        /// <summary>
        ///     Gets an instance of this quantity with a value of 0 in the base unit Becquerel.
        /// </summary>
        public static Radioactivity Zero
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => Info.Zero;
        }

        #endregion

        #region Properties

        /// <inheritdoc />
        public QuantityValue Value
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => _value;
        }

        /// <inheritdoc />
        public RadioactivityUnit Unit
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => _unit.GetValueOrDefault(BaseUnit);
        }

        /// <inheritdoc />
        public QuantityInfo<Radioactivity, RadioactivityUnit> QuantityInfo
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => Info;
        }

        #region Explicit implementations

        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        UnitKey IQuantity.UnitKey
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => UnitKey.ForUnit(Unit);
        }

#if NETSTANDARD2_0
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        IQuantityInstanceInfo<Radioactivity> IQuantityOfType<Radioactivity>.QuantityInfo
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => Info;
        }

        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        QuantityInfo<RadioactivityUnit> IQuantity<RadioactivityUnit>.QuantityInfo
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => Info;
        }

        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        QuantityInfo IQuantity.QuantityInfo
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => Info;
        }

        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        Enum IQuantity.Unit
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => Unit;
        }
#endif

        #endregion

        #endregion

        #region Conversion Properties

        /// <inheritdoc cref="IQuantity{Radioactivity,RadioactivityUnit}.AsBaseQuantity"/>
        /// <returns><see cref="RadioactivityUnit.Becquerel"/></returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Radioactivity AsBaseQuantity()
            => new(this.As(BaseUnit), BaseUnit);

        /// <inheritdoc cref="IQuantity{Radioactivity,RadioactivityUnit}.AsBaseValue"/>
        /// <returns><see cref="RadioactivityUnit.Becquerel"/></returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public QuantityValue AsBaseValue()
            => this.As(BaseUnit);

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="RadioactivityUnit.Becquerel"/>
        /// </summary>
        public QuantityValue Becquerels
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(RadioactivityUnit.Becquerel);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="RadioactivityUnit.Curie"/>
        /// </summary>
        public QuantityValue Curies
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(RadioactivityUnit.Curie);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="RadioactivityUnit.Exabecquerel"/>
        /// </summary>
        public QuantityValue Exabecquerels
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(RadioactivityUnit.Exabecquerel);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="RadioactivityUnit.Gigabecquerel"/>
        /// </summary>
        public QuantityValue Gigabecquerels
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(RadioactivityUnit.Gigabecquerel);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="RadioactivityUnit.Gigacurie"/>
        /// </summary>
        public QuantityValue Gigacuries
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(RadioactivityUnit.Gigacurie);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="RadioactivityUnit.Gigarutherford"/>
        /// </summary>
        public QuantityValue Gigarutherfords
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(RadioactivityUnit.Gigarutherford);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="RadioactivityUnit.Kilobecquerel"/>
        /// </summary>
        public QuantityValue Kilobecquerels
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(RadioactivityUnit.Kilobecquerel);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="RadioactivityUnit.Kilocurie"/>
        /// </summary>
        public QuantityValue Kilocuries
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(RadioactivityUnit.Kilocurie);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="RadioactivityUnit.Kilorutherford"/>
        /// </summary>
        public QuantityValue Kilorutherfords
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(RadioactivityUnit.Kilorutherford);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="RadioactivityUnit.Megabecquerel"/>
        /// </summary>
        public QuantityValue Megabecquerels
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(RadioactivityUnit.Megabecquerel);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="RadioactivityUnit.Megacurie"/>
        /// </summary>
        public QuantityValue Megacuries
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(RadioactivityUnit.Megacurie);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="RadioactivityUnit.Megarutherford"/>
        /// </summary>
        public QuantityValue Megarutherfords
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(RadioactivityUnit.Megarutherford);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="RadioactivityUnit.Microbecquerel"/>
        /// </summary>
        public QuantityValue Microbecquerels
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(RadioactivityUnit.Microbecquerel);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="RadioactivityUnit.Microcurie"/>
        /// </summary>
        public QuantityValue Microcuries
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(RadioactivityUnit.Microcurie);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="RadioactivityUnit.Microrutherford"/>
        /// </summary>
        public QuantityValue Microrutherfords
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(RadioactivityUnit.Microrutherford);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="RadioactivityUnit.Millibecquerel"/>
        /// </summary>
        public QuantityValue Millibecquerels
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(RadioactivityUnit.Millibecquerel);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="RadioactivityUnit.Millicurie"/>
        /// </summary>
        public QuantityValue Millicuries
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(RadioactivityUnit.Millicurie);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="RadioactivityUnit.Millirutherford"/>
        /// </summary>
        public QuantityValue Millirutherfords
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(RadioactivityUnit.Millirutherford);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="RadioactivityUnit.Nanobecquerel"/>
        /// </summary>
        public QuantityValue Nanobecquerels
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(RadioactivityUnit.Nanobecquerel);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="RadioactivityUnit.Nanocurie"/>
        /// </summary>
        public QuantityValue Nanocuries
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(RadioactivityUnit.Nanocurie);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="RadioactivityUnit.Nanorutherford"/>
        /// </summary>
        public QuantityValue Nanorutherfords
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(RadioactivityUnit.Nanorutherford);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="RadioactivityUnit.Petabecquerel"/>
        /// </summary>
        public QuantityValue Petabecquerels
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(RadioactivityUnit.Petabecquerel);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="RadioactivityUnit.Picobecquerel"/>
        /// </summary>
        public QuantityValue Picobecquerels
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(RadioactivityUnit.Picobecquerel);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="RadioactivityUnit.Picocurie"/>
        /// </summary>
        public QuantityValue Picocuries
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(RadioactivityUnit.Picocurie);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="RadioactivityUnit.Picorutherford"/>
        /// </summary>
        public QuantityValue Picorutherfords
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(RadioactivityUnit.Picorutherford);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="RadioactivityUnit.Rutherford"/>
        /// </summary>
        public QuantityValue Rutherfords
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(RadioactivityUnit.Rutherford);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="RadioactivityUnit.Terabecquerel"/>
        /// </summary>
        public QuantityValue Terabecquerels
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(RadioactivityUnit.Terabecquerel);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="RadioactivityUnit.Teracurie"/>
        /// </summary>
        public QuantityValue Teracuries
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(RadioactivityUnit.Teracurie);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="RadioactivityUnit.Terarutherford"/>
        /// </summary>
        public QuantityValue Terarutherfords
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(RadioactivityUnit.Terarutherford);
        }

        #endregion

        #region Static Methods

        /// <summary>
        ///     Get unit abbreviation string.
        /// </summary>
        /// <param name="unit">Unit to get abbreviation for.</param>
        /// <returns>Unit abbreviation string.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static string GetAbbreviation(RadioactivityUnit unit)
            => GetAbbreviation(unit, null);

        /// <summary>
        ///     Get unit abbreviation string.
        /// </summary>
        /// <param name="unit">Unit to get abbreviation for.</param>
        /// <returns>Unit abbreviation string.</returns>
        /// <param name="provider">Format to use for localization. Defaults to <see cref="CultureInfo.CurrentCulture" /> if null.</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static string GetAbbreviation(RadioactivityUnit unit, IFormatProvider? provider)
            => UnitsNetSetup.Default.UnitAbbreviations.GetDefaultAbbreviation(unit, provider);

        #endregion

        #region Static Factory Methods

        /// <summary>
        ///     Convert to base unit quantity of Becquerel.
        /// </summary>
        public Radioactivity BecquerelsToRadioactivity()
            => new(this.As(BaseUnit), BaseUnit);

        /// <summary>
        ///     Creates a <see cref="Radioactivity"/> from <see cref="RadioactivityUnit.Becquerel"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Radioactivity FromBecquerels(QuantityValue value)
            => new(value, RadioactivityUnit.Becquerel);

        /// <summary>
        ///     Creates a <see cref="Radioactivity"/> from <see cref="RadioactivityUnit.Curie"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Radioactivity FromCuries(QuantityValue value)
            => new(value, RadioactivityUnit.Curie);

        /// <summary>
        ///     Creates a <see cref="Radioactivity"/> from <see cref="RadioactivityUnit.Exabecquerel"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Radioactivity FromExabecquerels(QuantityValue value)
            => new(value, RadioactivityUnit.Exabecquerel);

        /// <summary>
        ///     Creates a <see cref="Radioactivity"/> from <see cref="RadioactivityUnit.Gigabecquerel"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Radioactivity FromGigabecquerels(QuantityValue value)
            => new(value, RadioactivityUnit.Gigabecquerel);

        /// <summary>
        ///     Creates a <see cref="Radioactivity"/> from <see cref="RadioactivityUnit.Gigacurie"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Radioactivity FromGigacuries(QuantityValue value)
            => new(value, RadioactivityUnit.Gigacurie);

        /// <summary>
        ///     Creates a <see cref="Radioactivity"/> from <see cref="RadioactivityUnit.Gigarutherford"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Radioactivity FromGigarutherfords(QuantityValue value)
            => new(value, RadioactivityUnit.Gigarutherford);

        /// <summary>
        ///     Creates a <see cref="Radioactivity"/> from <see cref="RadioactivityUnit.Kilobecquerel"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Radioactivity FromKilobecquerels(QuantityValue value)
            => new(value, RadioactivityUnit.Kilobecquerel);

        /// <summary>
        ///     Creates a <see cref="Radioactivity"/> from <see cref="RadioactivityUnit.Kilocurie"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Radioactivity FromKilocuries(QuantityValue value)
            => new(value, RadioactivityUnit.Kilocurie);

        /// <summary>
        ///     Creates a <see cref="Radioactivity"/> from <see cref="RadioactivityUnit.Kilorutherford"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Radioactivity FromKilorutherfords(QuantityValue value)
            => new(value, RadioactivityUnit.Kilorutherford);

        /// <summary>
        ///     Creates a <see cref="Radioactivity"/> from <see cref="RadioactivityUnit.Megabecquerel"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Radioactivity FromMegabecquerels(QuantityValue value)
            => new(value, RadioactivityUnit.Megabecquerel);

        /// <summary>
        ///     Creates a <see cref="Radioactivity"/> from <see cref="RadioactivityUnit.Megacurie"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Radioactivity FromMegacuries(QuantityValue value)
            => new(value, RadioactivityUnit.Megacurie);

        /// <summary>
        ///     Creates a <see cref="Radioactivity"/> from <see cref="RadioactivityUnit.Megarutherford"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Radioactivity FromMegarutherfords(QuantityValue value)
            => new(value, RadioactivityUnit.Megarutherford);

        /// <summary>
        ///     Creates a <see cref="Radioactivity"/> from <see cref="RadioactivityUnit.Microbecquerel"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Radioactivity FromMicrobecquerels(QuantityValue value)
            => new(value, RadioactivityUnit.Microbecquerel);

        /// <summary>
        ///     Creates a <see cref="Radioactivity"/> from <see cref="RadioactivityUnit.Microcurie"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Radioactivity FromMicrocuries(QuantityValue value)
            => new(value, RadioactivityUnit.Microcurie);

        /// <summary>
        ///     Creates a <see cref="Radioactivity"/> from <see cref="RadioactivityUnit.Microrutherford"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Radioactivity FromMicrorutherfords(QuantityValue value)
            => new(value, RadioactivityUnit.Microrutherford);

        /// <summary>
        ///     Creates a <see cref="Radioactivity"/> from <see cref="RadioactivityUnit.Millibecquerel"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Radioactivity FromMillibecquerels(QuantityValue value)
            => new(value, RadioactivityUnit.Millibecquerel);

        /// <summary>
        ///     Creates a <see cref="Radioactivity"/> from <see cref="RadioactivityUnit.Millicurie"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Radioactivity FromMillicuries(QuantityValue value)
            => new(value, RadioactivityUnit.Millicurie);

        /// <summary>
        ///     Creates a <see cref="Radioactivity"/> from <see cref="RadioactivityUnit.Millirutherford"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Radioactivity FromMillirutherfords(QuantityValue value)
            => new(value, RadioactivityUnit.Millirutherford);

        /// <summary>
        ///     Creates a <see cref="Radioactivity"/> from <see cref="RadioactivityUnit.Nanobecquerel"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Radioactivity FromNanobecquerels(QuantityValue value)
            => new(value, RadioactivityUnit.Nanobecquerel);

        /// <summary>
        ///     Creates a <see cref="Radioactivity"/> from <see cref="RadioactivityUnit.Nanocurie"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Radioactivity FromNanocuries(QuantityValue value)
            => new(value, RadioactivityUnit.Nanocurie);

        /// <summary>
        ///     Creates a <see cref="Radioactivity"/> from <see cref="RadioactivityUnit.Nanorutherford"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Radioactivity FromNanorutherfords(QuantityValue value)
            => new(value, RadioactivityUnit.Nanorutherford);

        /// <summary>
        ///     Creates a <see cref="Radioactivity"/> from <see cref="RadioactivityUnit.Petabecquerel"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Radioactivity FromPetabecquerels(QuantityValue value)
            => new(value, RadioactivityUnit.Petabecquerel);

        /// <summary>
        ///     Creates a <see cref="Radioactivity"/> from <see cref="RadioactivityUnit.Picobecquerel"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Radioactivity FromPicobecquerels(QuantityValue value)
            => new(value, RadioactivityUnit.Picobecquerel);

        /// <summary>
        ///     Creates a <see cref="Radioactivity"/> from <see cref="RadioactivityUnit.Picocurie"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Radioactivity FromPicocuries(QuantityValue value)
            => new(value, RadioactivityUnit.Picocurie);

        /// <summary>
        ///     Creates a <see cref="Radioactivity"/> from <see cref="RadioactivityUnit.Picorutherford"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Radioactivity FromPicorutherfords(QuantityValue value)
            => new(value, RadioactivityUnit.Picorutherford);

        /// <summary>
        ///     Creates a <see cref="Radioactivity"/> from <see cref="RadioactivityUnit.Rutherford"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Radioactivity FromRutherfords(QuantityValue value)
            => new(value, RadioactivityUnit.Rutherford);

        /// <summary>
        ///     Creates a <see cref="Radioactivity"/> from <see cref="RadioactivityUnit.Terabecquerel"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Radioactivity FromTerabecquerels(QuantityValue value)
            => new(value, RadioactivityUnit.Terabecquerel);

        /// <summary>
        ///     Creates a <see cref="Radioactivity"/> from <see cref="RadioactivityUnit.Teracurie"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Radioactivity FromTeracuries(QuantityValue value)
            => new(value, RadioactivityUnit.Teracurie);

        /// <summary>
        ///     Creates a <see cref="Radioactivity"/> from <see cref="RadioactivityUnit.Terarutherford"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Radioactivity FromTerarutherfords(QuantityValue value)
            => new(value, RadioactivityUnit.Terarutherford);

        /// <summary>
        ///     Dynamically convert from value and unit enum <see cref="RadioactivityUnit" /> to <see cref="Radioactivity" />.
        /// </summary>
        /// <param name="value">Value to convert from.</param>
        /// <param name="fromUnit">Unit to convert from.</param>
        /// <returns>Radioactivity unit value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Radioactivity From(QuantityValue value, RadioactivityUnit fromUnit)
            => new(value, fromUnit);

        #endregion

        #region Static Parse Methods

        /// <summary>
        ///     Parse a string with one or two quantities of the format "&lt;quantity&gt; &lt;unit&gt;".
        /// </summary>
        /// <param name="str">String to parse. Typically in the form: {number} {unit}</param>
        /// <example>
        ///     Length.Parse("5.5 m", CultureInfo.GetCultureInfo("en-US"));
        /// </example>
        /// <exception cref="ArgumentNullException">The value of 'str' cannot be null. </exception>
        /// <exception cref="ArgumentException">
        ///     Expected string to have one or two pairs of quantity and unit in the format
        ///     "&lt;quantity&gt; &lt;unit&gt;". Eg. "5.5 m" or "1ft 2in"
        /// </exception>
        /// <exception cref="AmbiguousUnitParseException">
        ///     More than one unit is represented by the specified unit abbreviation.
        ///     Example: Volume.Parse("1 cup") will throw, because it can refer to any of
        ///     <see cref="VolumeUnit.MetricCup" />, <see cref="VolumeUnit.UsLegalCup" /> and <see cref="VolumeUnit.UsCustomaryCup" />.
        /// </exception>
        /// <exception cref="UnitsNetException">
        ///     If anything else goes wrong, typically due to a bug or unhandled case.
        ///     We wrap exceptions in <see cref="UnitsNetException" /> to allow you to distinguish
        ///     Units.NET exceptions from other exceptions.
        /// </exception>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Radioactivity Parse(string str)
            => Parse(str, null);

        /// <summary>
        ///     Parse a string with one or two quantities of the format "&lt;quantity&gt; &lt;unit&gt;".
        /// </summary>
        /// <param name="str">String to parse. Typically in the form: {number} {unit}</param>
        /// <example>
        ///     Length.Parse("5.5 m", CultureInfo.GetCultureInfo("en-US"));
        /// </example>
        /// <exception cref="ArgumentNullException">The value of 'str' cannot be null. </exception>
        /// <exception cref="ArgumentException">
        ///     Expected string to have one or two pairs of quantity and unit in the format
        ///     "&lt;quantity&gt; &lt;unit&gt;". Eg. "5.5 m" or "1ft 2in"
        /// </exception>
        /// <exception cref="AmbiguousUnitParseException">
        ///     More than one unit is represented by the specified unit abbreviation.
        ///     Example: Volume.Parse("1 cup") will throw, because it can refer to any of
        ///     <see cref="VolumeUnit.MetricCup" />, <see cref="VolumeUnit.UsLegalCup" /> and <see cref="VolumeUnit.UsCustomaryCup" />.
        /// </exception>
        /// <exception cref="UnitsNetException">
        ///     If anything else goes wrong, typically due to a bug or unhandled case.
        ///     We wrap exceptions in <see cref="UnitsNetException" /> to allow you to distinguish
        ///     Units.NET exceptions from other exceptions.
        /// </exception>
        /// <param name="provider">Format to use when parsing number and unit. Defaults to <see cref="CultureInfo.CurrentCulture" /> if null.</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Radioactivity Parse(string str, IFormatProvider? provider)
            => QuantityParser.Default.Parse<Radioactivity, RadioactivityUnit>(str, provider, From);

        /// <summary>
        ///     Try to parse a string with one or two quantities of the format "&lt;quantity&gt; &lt;unit&gt;".
        /// </summary>
        /// <param name="str">String to parse. Typically in the form: {number} {unit}</param>
        /// <param name="result">Resulting unit quantity if successful.</param>
        /// <example>
        ///     Length.Parse("5.5 m", CultureInfo.GetCultureInfo("en-US"));
        /// </example>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool TryParse([NotNullWhen(true)]string? str, out Radioactivity result)
            => TryParse(str, null, out result);

        /// <summary>
        ///     Try to parse a string with one or two quantities of the format "&lt;quantity&gt; &lt;unit&gt;".
        /// </summary>
        /// <param name="str">String to parse. Typically in the form: {number} {unit}</param>
        /// <param name="result">Resulting unit quantity if successful.</param>
        /// <returns>True if successful, otherwise false.</returns>
        /// <example>
        ///     Length.Parse("5.5 m", CultureInfo.GetCultureInfo("en-US"));
        /// </example>
        /// <param name="provider">Format to use when parsing number and unit. Defaults to <see cref="CultureInfo.CurrentCulture" /> if null.</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool TryParse([NotNullWhen(true)]string? str, IFormatProvider? provider, out Radioactivity result)
            => QuantityParser.Default.TryParse<Radioactivity, RadioactivityUnit>(str, provider, From, out result);

        /// <summary>
        ///     Parse a unit string.
        /// </summary>
        /// <param name="str">String to parse. Typically in the form: {number} {unit}</param>
        /// <example>
        ///     Length.ParseUnit("m", CultureInfo.GetCultureInfo("en-US"));
        /// </example>
        /// <exception cref="ArgumentNullException">The value of 'str' cannot be null. </exception>
        /// <exception cref="UnitsNetException">Error parsing string.</exception>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static RadioactivityUnit ParseUnit(string str)
            => ParseUnit(str, null);

        /// <summary>
        ///     Parse a unit string.
        /// </summary>
        /// <param name="str">String to parse. Typically in the form: {number} {unit}</param>
        /// <param name="provider">Format to use when parsing the unit. Defaults to <see cref="CultureInfo.CurrentCulture" /> if null.</param>
        /// <example>
        ///     Length.ParseUnit("m", CultureInfo.GetCultureInfo("en-US"));
        /// </example>
        /// <exception cref="ArgumentNullException">The value of 'str' cannot be null. </exception>
        /// <exception cref="UnitsNetException">Error parsing string.</exception>
        public static RadioactivityUnit ParseUnit(string str, IFormatProvider? provider)
            => UnitParser.Default.Parse(str, Info.UnitInfos, provider).Value;

        /// <inheritdoc cref="TryParseUnit(string,IFormatProvider?,out UnitsNet.Units.RadioactivityUnit)"/>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool TryParseUnit([NotNullWhen(true)]string? str, out RadioactivityUnit unit)
            => TryParseUnit(str, null, out unit);

        /// <summary>
        ///     Parse a unit string.
        /// </summary>
        /// <param name="str">String to parse. Typically in the form: {number} {unit}</param>
        /// <param name="unit">The parsed unit if successful.</param>
        /// <returns>True if successful, otherwise false.</returns>
        /// <example>
        ///     Length.TryParseUnit("m", CultureInfo.GetCultureInfo("en-US"));
        /// </example>
        /// <param name="provider">Format to use when parsing the unit. Defaults to <see cref="CultureInfo.CurrentCulture" /> if null.</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool TryParseUnit([NotNullWhen(true)]string? str, IFormatProvider? provider, out RadioactivityUnit unit)
            => UnitParser.Default.TryParse(str, Info, provider, out unit);

        #endregion

        /// <summary>
        /// Gets value of base unit.
        /// </summary>
        /// <param name="d"></param>
        [Obsolete("Gets value of base unit. Use factory methods instead to specify unit conversion.")]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator QuantityValue(Radioactivity d) => d.As(BaseUnit);

        /// <summary>
        /// Gets quantity of base unit.
        /// </summary>
        /// <param name="d"></param>
        [Obsolete("Gets value of base unit. Use factory methods instead to specify unit conversion.")]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator Radioactivity(QuantityValue d) => new(d, BaseUnit);

        /// <summary>
        /// Gets value of base unit.
        /// </summary>
        /// <param name="d"></param>
        [Obsolete("Gets value of base unit. Use factory methods instead to specify unit conversion.")]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static explicit operator double(Radioactivity d) => d.As(BaseUnit);

        /// <summary>
        /// Gets quantity of base unit.
        /// </summary>
        /// <param name="d"></param>
        [Obsolete("Gets value of base unit. Use factory methods instead to specify unit conversion.")]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static explicit operator Radioactivity(double d) => new(d, BaseUnit);

        #region Arithmetic Operators

        /// <summary>Negate the value.</summary>
        public static Radioactivity operator -(Radioactivity right)
            => new(-right.Value, right.Unit);

        /// <summary>Get <see cref="Radioactivity"/> from adding two <see cref="Radioactivity"/>.</summary>
        public static Radioactivity operator +(Radioactivity left, Radioactivity right)
            => new(left.Value + right.As(left.Unit), left.Unit);

        /// <summary>Get <see cref="Radioactivity"/> from subtracting two <see cref="Radioactivity"/>.</summary>
        public static Radioactivity operator -(Radioactivity left, Radioactivity right)
            => new(left.Value - right.As(left.Unit), left.Unit);

        /// <summary>Get <see cref="Radioactivity"/> from multiplying value and <see cref="Radioactivity"/>.</summary>
        public static Radioactivity operator *(QuantityValue left, Radioactivity right)
            => new(left * right.Value, right.Unit);

        /// <summary>Get <see cref="Radioactivity"/> from multiplying value and <see cref="Radioactivity"/>.</summary>
        public static Radioactivity operator *(Radioactivity left, QuantityValue right)
            => new(left.Value * right, left.Unit);

        /// <summary>Get <see cref="Radioactivity"/> from dividing <see cref="Radioactivity"/> by value.</summary>
        public static Radioactivity operator /(Radioactivity left, QuantityValue right)
            => new(left.Value / right, left.Unit);

        /// <summary>Get ratio value from dividing <see cref="Radioactivity"/> by <see cref="Radioactivity"/>.</summary>
        public static QuantityValue operator /(Radioactivity left, Radioactivity right)
            => left.Becquerels / right.Becquerels;

        #endregion

        #region Equality / IComparable

        /// <summary>Returns true if less or equal to.</summary>
        public static bool operator <=(Radioactivity left, Radioactivity right)
            => left.Value <= right.As(left.Unit);

        /// <summary>Returns true if greater than or equal to.</summary>
        public static bool operator >=(Radioactivity left, Radioactivity right)
            => left.Value >= right.As(left.Unit);

        /// <summary>Returns true if less than.</summary>
        public static bool operator <(Radioactivity left, Radioactivity right)
            => left.Value < right.As(left.Unit);

        /// <summary>Returns true if greater than.</summary>
        public static bool operator >(Radioactivity left, Radioactivity right)
            => left.Value > right.As(left.Unit);

        /// <summary>
        ///     Determines whether two <see cref="Radioactivity"/> instances are equal.
        /// </summary>
        /// <remarks>
        ///     Equality is evaluated in a unit-aware manner. The right-hand operand is converted to the unit of the left-hand
        ///     operand and then the underlying numeric values are compared.
        ///     This means two quantities with numerically equal values but different units will be considered equal.
        ///     The operator delegates to <see cref="Equals(Radioactivity)"/>, which implements this conversion-and-compare logic.
        /// </remarks>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool operator ==(Radioactivity left, Radioactivity right)
            => left.Equals(right);

        /// <summary>
        ///     Determines whether two <see cref="Radioactivity"/> instances are not equal.
        /// </summary>
        /// <remarks>
        ///     This operator is the logical negation of <see cref="operator ==(Radioactivity,Radioactivity)"/>.
        ///     See that operator (and <see cref="Equals(Radioactivity)"/>) for details on how equality is evaluated
        ///     (i.e., by converting one operand to the other's unit and comparing their numeric values).
        /// </remarks>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool operator !=(Radioactivity left, Radioactivity right)
            => !(left == right);

        /// <inheritdoc />
        /// <summary>
        ///     Determines whether the specified object is equal to the current <see cref="Radioactivity"/> instance.
        /// </summary>
        /// <remarks>
        ///     Returns <c>false</c> if <paramref name="obj"/> is <c>null</c> or not a <see cref="Radioactivity"/>.
        ///     When <paramref name="obj"/> is a <see cref="Radioactivity"/>, this method delegates to
        ///     <see cref="Equals(Radioactivity)"/>, which performs a unit-aware comparison by converting the other
        ///     instance to this instance's unit before comparing numeric values.
        /// </remarks>
        public override bool Equals(object? obj)
            => obj is Radioactivity otherQuantity && Equals(otherQuantity);

        /// <inheritdoc />
        /// <summary>
        ///     Determines whether the current instance is equal to another <see cref="Radioactivity"/> instance.
        /// </summary>
        /// <remarks>
        ///     Comparison is performed by converting <paramref name="other"/> to this instance's unit and then comparing the underlying numeric values.
        ///     This makes two quantities equal even when their units differ, provided the converted numeric values are equal.
        /// </remarks>
        public bool Equals(Radioactivity other)
            => _value.Equals(other.As(Unit));

        /// <summary>
        ///     Returns the hash code for this instance.
        /// </summary>
        /// <returns>A hash code for the current Radioactivity.</returns>
        public override int GetHashCode()
            => Comparison.GetHashCode(typeof(Radioactivity), this.As(BaseUnit));

        /// <inheritdoc  cref="CompareTo(Radioactivity)" />
        /// <param name="obj">An object to compare with this instance.</param>
        /// <exception cref="T:System.ArgumentException">
        ///    <paramref name="obj" /> is not the same type as this instance.
        /// </exception>
        public int CompareTo(object? obj)
        {
            if (obj is not Radioactivity otherQuantity)
                throw obj is null ? new ArgumentNullException(nameof(obj)) : ExceptionHelper.CreateArgumentException<Radioactivity>(obj, nameof(obj));

            return CompareTo(otherQuantity);
        }

        /// <summary>
        ///     Compares the current <see cref="Radioactivity"/> with another <see cref="Radioactivity"/> and returns an integer that indicates
        ///     whether the current instance precedes, follows, or occurs in the same position in the sort order as the other quantity, when converted to the same unit.
        /// </summary>
        /// <param name="other">A quantity to compare with this instance.</param>
        /// <returns>A value that indicates the relative order of the quantities being compared. The return value has these meanings:
        ///     <list type="table">
        ///         <listheader><term> Value</term><description> Meaning</description></listheader>
        ///         <item><term> Less than zero</term><description> This instance precedes <paramref name="other" /> in the sort order.</description></item>
        ///         <item><term> Zero</term><description> This instance occurs in the same position in the sort order as <paramref name="other" />.</description></item>
        ///         <item><term> Greater than zero</term><description> This instance follows <paramref name="other" /> in the sort order.</description></item>
        ///     </list>
        /// </returns>
        public int CompareTo(Radioactivity other)
            => _value.CompareTo(other.As(Unit));

        #endregion

        #region ToString Methods

        /// <summary>
        ///     Gets the default string representation of value and unit.
        /// </summary>
        /// <returns>String representation.</returns>
        public override string ToString()
            => ToString(null, null);

        /// <inheritdoc cref="QuantityFormatter.Format{TQuantity}(TQuantity, string, IFormatProvider)"/>
        /// <summary>
        /// Gets the string representation of this instance in the specified format string using the specified format provider, or <see cref="CultureInfo.CurrentCulture" /> if null.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public string ToString(
            [StringSyntax(StringSyntaxAttribute.NumericFormat)] string? format,
            IFormatProvider? provider)
            => QuantityFormatter.Default.Format(this, format, provider);

        #endregion

    }
}
