//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

using System.Globalization;
using System.Resources;
using System.Runtime.Serialization;
using UnitsNet.Debug;

#nullable enable

// ReSharper disable once CheckNamespace

namespace UnitsNet
{
    /// <inheritdoc />
    /// <summary>
    ///     Thermal resistivity is the property of a material to resist heat.
    /// </summary>
    /// <remarks>
    ///     https://en.wikipedia.org/wiki/Thermal_conductivity_and_resistivity
    /// </remarks>
    [DataContract]
    [DebuggerDisplay(QuantityDebugProxy.DisplayFormat)]
    [DebuggerTypeProxy(typeof(QuantityDebugProxy))]
    public readonly partial struct ThermalResistivity :
        ILinearQuantity<ThermalResistivity, ThermalResistivityUnit>,
#if NET7_0_OR_GREATER
        IDivisionOperators<ThermalResistivity, ThermalResistivity, QuantityValue>,
        IComparisonOperators<ThermalResistivity, ThermalResistivity, bool>,
        IParsable<ThermalResistivity>,
#endif
        IComparable,
        IComparable<ThermalResistivity>,
        IEquatable<ThermalResistivity>,
        IFormattable
    {
        /// <summary>
        ///     The numeric value this quantity was constructed with.
        /// </summary>
        [DataMember(Name = "Value", Order = 1)]
        private readonly QuantityValue _value;

        /// <summary>
        ///     The unit this quantity was constructed with.
        /// </summary>
        [DataMember(Name = "Unit", Order = 2)]
        private readonly ThermalResistivityUnit? _unit;

        /// <summary>
        ///     Provides detailed information about the <see cref="ThermalResistivity"/> quantity, including its name, base unit, unit mappings, base dimensions, and conversion functions.
        /// </summary>
        public sealed class ThermalResistivityInfo: QuantityInfo<ThermalResistivity, ThermalResistivityUnit>
        {
            /// <inheritdoc />
            public ThermalResistivityInfo(string name, ThermalResistivityUnit baseUnit, IEnumerable<IUnitDefinition<ThermalResistivityUnit>> unitMappings, ThermalResistivity zero, BaseDimensions baseDimensions,
                QuantityFromDelegate<ThermalResistivity, ThermalResistivityUnit> fromDelegate, ResourceManager? unitAbbreviations)
                : base(name, baseUnit, unitMappings, zero, baseDimensions, fromDelegate, unitAbbreviations)
            {
            }

            /// <inheritdoc />
            public ThermalResistivityInfo(string name, ThermalResistivityUnit baseUnit, IEnumerable<IUnitDefinition<ThermalResistivityUnit>> unitMappings, ThermalResistivity zero, BaseDimensions baseDimensions)
                : this(name, baseUnit, unitMappings, zero, baseDimensions, ThermalResistivity.From, new ResourceManager("UnitsNet.GeneratedCode.Resources.ThermalResistivity", typeof(ThermalResistivity).Assembly))
            {
            }

            /// <summary>
            ///     Creates a new instance of the <see cref="ThermalResistivityInfo"/> class with the default settings for the ThermalResistivity quantity.
            /// </summary>
            /// <returns>A new instance of the <see cref="ThermalResistivityInfo"/> class with the default settings.</returns>
            public static ThermalResistivityInfo CreateDefault()
            {
                return new ThermalResistivityInfo(nameof(ThermalResistivity), DefaultBaseUnit, GetDefaultMappings(), new ThermalResistivity(0, DefaultBaseUnit), DefaultBaseDimensions);
            }

            /// <summary>
            ///     Creates a new instance of the <see cref="ThermalResistivityInfo"/> class with the default settings for the ThermalResistivity quantity and a callback for customizing the default unit mappings.
            /// </summary>
            /// <param name="customizeUnits">
            ///     A callback function for customizing the default unit mappings.
            /// </param>
            /// <returns>
            ///     A new instance of the <see cref="ThermalResistivityInfo"/> class with the default settings.
            /// </returns>
            public static ThermalResistivityInfo CreateDefault(Func<IEnumerable<UnitDefinition<ThermalResistivityUnit>>, IEnumerable<IUnitDefinition<ThermalResistivityUnit>>> customizeUnits)
            {
                return new ThermalResistivityInfo(nameof(ThermalResistivity), DefaultBaseUnit, customizeUnits(GetDefaultMappings()), new ThermalResistivity(0, DefaultBaseUnit), DefaultBaseDimensions);
            }

            /// <summary>
            ///     The <see cref="BaseDimensions" /> for <see cref="ThermalResistivity"/> is T^3L^-1M^-1Θ.
            /// </summary>
            public static BaseDimensions DefaultBaseDimensions { get; } = new BaseDimensions(-1, -1, 3, 0, 1, 0, 0);

            /// <summary>
            ///     The default base unit of ThermalResistivity is KelvinMeterPerWatt. All conversions, as defined in the <see cref="GetDefaultMappings"/>, go via this value.
            /// </summary>
            public static ThermalResistivityUnit DefaultBaseUnit { get; } = ThermalResistivityUnit.KelvinMeterPerWatt;

            /// <summary>
            ///     Retrieves the default mappings for <see cref="ThermalResistivityUnit"/>.
            /// </summary>
            /// <returns>An <see cref="IEnumerable{T}"/> of <see cref="UnitDefinition{ThermalResistivityUnit}"/> representing the default unit mappings for ThermalResistivity.</returns>
            public static IEnumerable<UnitDefinition<ThermalResistivityUnit>> GetDefaultMappings()
            {
                yield return new (ThermalResistivityUnit.HourFootFahrenheitPerBtu, "HourFootFahrenheitPerBtu", "HourFeetFahrenheitPerBtu", BaseUnits.Undefined,
                     new QuantityValue(52752792631, 30480000000)
                );
                yield return new (ThermalResistivityUnit.KelvinMeterPerWatt, "KelvinMeterPerWatt", "KelvinMetersPerWatt", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Kilogram, time: DurationUnit.Second, temperature: TemperatureUnit.Kelvin));
                yield return new (ThermalResistivityUnit.SecondInchFahrenheitPerBtu, "SecondInchFahrenheitPerBtu", "SecondInchesFahrenheitPerBtu", BaseUnits.Undefined,
                     new QuantityValue(474775133679, 6350000)
                );
            }
        }

        static ThermalResistivity()
        {
            Info = UnitsNetSetup.CreateQuantityInfo(ThermalResistivityInfo.CreateDefault);
        }

        /// <summary>
        ///     Creates the quantity with the given numeric value and unit.
        /// </summary>
        /// <param name="value">The numeric value to construct this quantity with.</param>
        /// <param name="unit">The unit representation to construct this quantity with.</param>
        public ThermalResistivity(QuantityValue value, ThermalResistivityUnit unit)
        {
            _value = value;
            _unit = unit;
        }

        /// <summary>
        /// Creates an instance of the quantity with the given numeric value in units compatible with the given <see cref="UnitSystem"/>.
        /// If multiple compatible units were found, the first match is used.
        /// </summary>
        /// <param name="value">The numeric value to construct this quantity with.</param>
        /// <param name="unitSystem">The unit system to create the quantity with.</param>
        /// <exception cref="ArgumentNullException">The given <see cref="UnitSystem"/> is null.</exception>
        /// <exception cref="ArgumentException">No unit was found for the given <see cref="UnitSystem"/>.</exception>
        public ThermalResistivity(QuantityValue value, UnitSystem unitSystem)
        {
            _value = value;
            _unit = Info.GetDefaultUnit(unitSystem);
        }

        #region Static Properties

        /// <summary>
        ///     The <see cref="UnitConverter" /> containing the default generated conversion functions for <see cref="ThermalResistivity" /> instances.
        /// </summary>
        [Obsolete("Replaced by UnitConverter.Default")]
        public static UnitConverter DefaultConversionFunctions => UnitConverter.Default;

        /// <inheritdoc cref="IQuantity.QuantityInfo"/>
        public static QuantityInfo<ThermalResistivity, ThermalResistivityUnit> Info { get; }

        /// <summary>
        ///     The <see cref="BaseDimensions" /> of this quantity.
        /// </summary>
        public static BaseDimensions BaseDimensions => Info.BaseDimensions;

        /// <summary>
        ///     The base unit of ThermalResistivity, which is KelvinMeterPerWatt. All conversions go via this value.
        /// </summary>
        public static ThermalResistivityUnit BaseUnit => Info.BaseUnitInfo.Value;

        /// <summary>
        ///     All units of measurement for the ThermalResistivity quantity.
        /// </summary>
        public static IReadOnlyCollection<ThermalResistivityUnit> Units => Info.Units;

        /// <summary>
        ///     Gets an instance of this quantity with a value of 0 in the base unit KelvinMeterPerWatt.
        /// </summary>
        public static ThermalResistivity Zero => Info.Zero;

        #endregion

        #region Properties

        /// <inheritdoc />
        public QuantityValue Value => _value;

        /// <inheritdoc />
        public ThermalResistivityUnit Unit => _unit.GetValueOrDefault(BaseUnit);

        /// <inheritdoc />
        public QuantityInfo<ThermalResistivity, ThermalResistivityUnit> QuantityInfo => Info;

        #region Explicit implementations

        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        UnitKey IQuantity.UnitKey => UnitKey.ForUnit(Unit);

#if NETSTANDARD2_0
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        IQuantityInstanceInfo<ThermalResistivity> IQuantityOfType<ThermalResistivity>.QuantityInfo => Info;

        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        QuantityInfo<ThermalResistivityUnit> IQuantity<ThermalResistivityUnit>.QuantityInfo => Info;

        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        QuantityInfo IQuantity.QuantityInfo => Info;

        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        Enum IQuantity.Unit => Unit;
#endif

        #endregion

        #endregion

        #region Conversion Properties

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="ThermalResistivityUnit.HourFootFahrenheitPerBtu"/>
        /// </summary>
        public QuantityValue HourFeetFahrenheitPerBtu => this.As(ThermalResistivityUnit.HourFootFahrenheitPerBtu);

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="ThermalResistivityUnit.KelvinMeterPerWatt"/>
        /// </summary>
        public QuantityValue KelvinMetersPerWatt => this.As(ThermalResistivityUnit.KelvinMeterPerWatt);

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="ThermalResistivityUnit.SecondInchFahrenheitPerBtu"/>
        /// </summary>
        public QuantityValue SecondInchesFahrenheitPerBtu => this.As(ThermalResistivityUnit.SecondInchFahrenheitPerBtu);

        #endregion

        #region Static Methods

        /// <summary>
        ///     Get unit abbreviation string.
        /// </summary>
        /// <param name="unit">Unit to get abbreviation for.</param>
        /// <returns>Unit abbreviation string.</returns>
        public static string GetAbbreviation(ThermalResistivityUnit unit)
        {
            return GetAbbreviation(unit, null);
        }

        /// <summary>
        ///     Get unit abbreviation string.
        /// </summary>
        /// <param name="unit">Unit to get abbreviation for.</param>
        /// <returns>Unit abbreviation string.</returns>
        /// <param name="provider">Format to use for localization. Defaults to <see cref="CultureInfo.CurrentCulture" /> if null.</param>
        public static string GetAbbreviation(ThermalResistivityUnit unit, IFormatProvider? provider)
        {
            return UnitsNetSetup.Default.UnitAbbreviations.GetDefaultAbbreviation(unit, provider);
        }

        #endregion

        #region Static Factory Methods

        /// <summary>
        ///     Creates a <see cref="ThermalResistivity"/> from <see cref="ThermalResistivityUnit.HourFootFahrenheitPerBtu"/>.
        /// </summary>
        public static ThermalResistivity FromHourFeetFahrenheitPerBtu(QuantityValue value)
        {
            return new ThermalResistivity(value, ThermalResistivityUnit.HourFootFahrenheitPerBtu);
        }

        /// <summary>
        ///     Creates a <see cref="ThermalResistivity"/> from <see cref="ThermalResistivityUnit.KelvinMeterPerWatt"/>.
        /// </summary>
        public static ThermalResistivity FromKelvinMetersPerWatt(QuantityValue value)
        {
            return new ThermalResistivity(value, ThermalResistivityUnit.KelvinMeterPerWatt);
        }

        /// <summary>
        ///     Creates a <see cref="ThermalResistivity"/> from <see cref="ThermalResistivityUnit.SecondInchFahrenheitPerBtu"/>.
        /// </summary>
        public static ThermalResistivity FromSecondInchesFahrenheitPerBtu(QuantityValue value)
        {
            return new ThermalResistivity(value, ThermalResistivityUnit.SecondInchFahrenheitPerBtu);
        }

        /// <summary>
        ///     Dynamically convert from value and unit enum <see cref="ThermalResistivityUnit" /> to <see cref="ThermalResistivity" />.
        /// </summary>
        /// <param name="value">Value to convert from.</param>
        /// <param name="fromUnit">Unit to convert from.</param>
        /// <returns>ThermalResistivity unit value.</returns>
        public static ThermalResistivity From(QuantityValue value, ThermalResistivityUnit fromUnit)
        {
            return new ThermalResistivity(value, fromUnit);
        }

        #endregion

        #region Static Parse Methods

        /// <summary>
        ///     Parse a string with one or two quantities of the format "&lt;quantity&gt; &lt;unit&gt;".
        /// </summary>
        /// <param name="str">String to parse. Typically in the form: {number} {unit}</param>
        /// <example>
        ///     Length.Parse("5.5 m", CultureInfo.GetCultureInfo("en-US"));
        /// </example>
        /// <exception cref="ArgumentNullException">The value of 'str' cannot be null. </exception>
        /// <exception cref="ArgumentException">
        ///     Expected string to have one or two pairs of quantity and unit in the format
        ///     "&lt;quantity&gt; &lt;unit&gt;". Eg. "5.5 m" or "1ft 2in"
        /// </exception>
        /// <exception cref="AmbiguousUnitParseException">
        ///     More than one unit is represented by the specified unit abbreviation.
        ///     Example: Volume.Parse("1 cup") will throw, because it can refer to any of
        ///     <see cref="VolumeUnit.MetricCup" />, <see cref="VolumeUnit.UsLegalCup" /> and <see cref="VolumeUnit.UsCustomaryCup" />.
        /// </exception>
        /// <exception cref="UnitsNetException">
        ///     If anything else goes wrong, typically due to a bug or unhandled case.
        ///     We wrap exceptions in <see cref="UnitsNetException" /> to allow you to distinguish
        ///     Units.NET exceptions from other exceptions.
        /// </exception>
        public static ThermalResistivity Parse(string str)
        {
            return Parse(str, null);
        }

        /// <summary>
        ///     Parse a string with one or two quantities of the format "&lt;quantity&gt; &lt;unit&gt;".
        /// </summary>
        /// <param name="str">String to parse. Typically in the form: {number} {unit}</param>
        /// <example>
        ///     Length.Parse("5.5 m", CultureInfo.GetCultureInfo("en-US"));
        /// </example>
        /// <exception cref="ArgumentNullException">The value of 'str' cannot be null. </exception>
        /// <exception cref="ArgumentException">
        ///     Expected string to have one or two pairs of quantity and unit in the format
        ///     "&lt;quantity&gt; &lt;unit&gt;". Eg. "5.5 m" or "1ft 2in"
        /// </exception>
        /// <exception cref="AmbiguousUnitParseException">
        ///     More than one unit is represented by the specified unit abbreviation.
        ///     Example: Volume.Parse("1 cup") will throw, because it can refer to any of
        ///     <see cref="VolumeUnit.MetricCup" />, <see cref="VolumeUnit.UsLegalCup" /> and <see cref="VolumeUnit.UsCustomaryCup" />.
        /// </exception>
        /// <exception cref="UnitsNetException">
        ///     If anything else goes wrong, typically due to a bug or unhandled case.
        ///     We wrap exceptions in <see cref="UnitsNetException" /> to allow you to distinguish
        ///     Units.NET exceptions from other exceptions.
        /// </exception>
        /// <param name="provider">Format to use when parsing number and unit. Defaults to <see cref="CultureInfo.CurrentCulture" /> if null.</param>
        public static ThermalResistivity Parse(string str, IFormatProvider? provider)
        {
            return QuantityParser.Default.Parse<ThermalResistivity, ThermalResistivityUnit>(str, provider, From);
        }

        /// <summary>
        ///     Try to parse a string with one or two quantities of the format "&lt;quantity&gt; &lt;unit&gt;".
        /// </summary>
        /// <param name="str">String to parse. Typically in the form: {number} {unit}</param>
        /// <param name="result">Resulting unit quantity if successful.</param>
        /// <example>
        ///     Length.Parse("5.5 m", CultureInfo.GetCultureInfo("en-US"));
        /// </example>
        public static bool TryParse([NotNullWhen(true)]string? str, out ThermalResistivity result)
        {
            return TryParse(str, null, out result);
        }

        /// <summary>
        ///     Try to parse a string with one or two quantities of the format "&lt;quantity&gt; &lt;unit&gt;".
        /// </summary>
        /// <param name="str">String to parse. Typically in the form: {number} {unit}</param>
        /// <param name="result">Resulting unit quantity if successful.</param>
        /// <returns>True if successful, otherwise false.</returns>
        /// <example>
        ///     Length.Parse("5.5 m", CultureInfo.GetCultureInfo("en-US"));
        /// </example>
        /// <param name="provider">Format to use when parsing number and unit. Defaults to <see cref="CultureInfo.CurrentCulture" /> if null.</param>
        public static bool TryParse([NotNullWhen(true)]string? str, IFormatProvider? provider, out ThermalResistivity result)
        {
            return QuantityParser.Default.TryParse<ThermalResistivity, ThermalResistivityUnit>(str, provider, From, out result);
        }

        /// <summary>
        ///     Parse a unit string.
        /// </summary>
        /// <param name="str">String to parse. Typically in the form: {number} {unit}</param>
        /// <example>
        ///     Length.ParseUnit("m", CultureInfo.GetCultureInfo("en-US"));
        /// </example>
        /// <exception cref="ArgumentNullException">The value of 'str' cannot be null. </exception>
        /// <exception cref="UnitsNetException">Error parsing string.</exception>
        public static ThermalResistivityUnit ParseUnit(string str)
        {
            return ParseUnit(str, null);
        }

        /// <summary>
        ///     Parse a unit string.
        /// </summary>
        /// <param name="str">String to parse. Typically in the form: {number} {unit}</param>
        /// <param name="provider">Format to use when parsing the unit. Defaults to <see cref="CultureInfo.CurrentCulture" /> if null.</param>
        /// <example>
        ///     Length.ParseUnit("m", CultureInfo.GetCultureInfo("en-US"));
        /// </example>
        /// <exception cref="ArgumentNullException">The value of 'str' cannot be null. </exception>
        /// <exception cref="UnitsNetException">Error parsing string.</exception>
        public static ThermalResistivityUnit ParseUnit(string str, IFormatProvider? provider)
        {
            return UnitParser.Default.Parse(str, Info.UnitInfos, provider).Value;
        }

        /// <inheritdoc cref="TryParseUnit(string,IFormatProvider?,out UnitsNet.Units.ThermalResistivityUnit)"/>
        public static bool TryParseUnit([NotNullWhen(true)]string? str, out ThermalResistivityUnit unit)
        {
            return TryParseUnit(str, null, out unit);
        }

        /// <summary>
        ///     Parse a unit string.
        /// </summary>
        /// <param name="str">String to parse. Typically in the form: {number} {unit}</param>
        /// <param name="unit">The parsed unit if successful.</param>
        /// <returns>True if successful, otherwise false.</returns>
        /// <example>
        ///     Length.TryParseUnit("m", CultureInfo.GetCultureInfo("en-US"));
        /// </example>
        /// <param name="provider">Format to use when parsing the unit. Defaults to <see cref="CultureInfo.CurrentCulture" /> if null.</param>
        public static bool TryParseUnit([NotNullWhen(true)]string? str, IFormatProvider? provider, out ThermalResistivityUnit unit)
        {
            return UnitParser.Default.TryParse(str, Info, provider, out unit);
        }

        #endregion

        #region Arithmetic Operators

        /// <summary>Negate the value.</summary>
        public static ThermalResistivity operator -(ThermalResistivity right)
        {
            return new ThermalResistivity(-right.Value, right.Unit);
        }

        /// <summary>Get <see cref="ThermalResistivity"/> from adding two <see cref="ThermalResistivity"/>.</summary>
        public static ThermalResistivity operator +(ThermalResistivity left, ThermalResistivity right)
        {
            return new ThermalResistivity(left.Value + right.As(left.Unit), left.Unit);
        }

        /// <summary>Get <see cref="ThermalResistivity"/> from subtracting two <see cref="ThermalResistivity"/>.</summary>
        public static ThermalResistivity operator -(ThermalResistivity left, ThermalResistivity right)
        {
            return new ThermalResistivity(left.Value - right.As(left.Unit), left.Unit);
        }

        /// <summary>Get <see cref="ThermalResistivity"/> from multiplying value and <see cref="ThermalResistivity"/>.</summary>
        public static ThermalResistivity operator *(QuantityValue left, ThermalResistivity right)
        {
            return new ThermalResistivity(left * right.Value, right.Unit);
        }

        /// <summary>Get <see cref="ThermalResistivity"/> from multiplying value and <see cref="ThermalResistivity"/>.</summary>
        public static ThermalResistivity operator *(ThermalResistivity left, QuantityValue right)
        {
            return new ThermalResistivity(left.Value * right, left.Unit);
        }

        /// <summary>Get <see cref="ThermalResistivity"/> from dividing <see cref="ThermalResistivity"/> by value.</summary>
        public static ThermalResistivity operator /(ThermalResistivity left, QuantityValue right)
        {
            return new ThermalResistivity(left.Value / right, left.Unit);
        }

        /// <summary>Get ratio value from dividing <see cref="ThermalResistivity"/> by <see cref="ThermalResistivity"/>.</summary>
        public static QuantityValue operator /(ThermalResistivity left, ThermalResistivity right)
        {
            return left.KelvinMetersPerWatt / right.KelvinMetersPerWatt;
        }

        #endregion

        #region Relational Operators

        /// <summary>Calculates the inverse of this quantity.</summary>
        /// <returns>The corresponding inverse quantity, <see cref="ThermalConductivity"/>.</returns>
        public ThermalConductivity Inverse()
        {
            return UnitConverter.Default.ConvertTo(Value, Unit, ThermalConductivity.Info);
        }

        #endregion

        #region Equality / IComparable

        /// <summary>Returns true if less or equal to.</summary>
        public static bool operator <=(ThermalResistivity left, ThermalResistivity right)
        {
            return left.Value <= right.As(left.Unit);
        }

        /// <summary>Returns true if greater than or equal to.</summary>
        public static bool operator >=(ThermalResistivity left, ThermalResistivity right)
        {
            return left.Value >= right.As(left.Unit);
        }

        /// <summary>Returns true if less than.</summary>
        public static bool operator <(ThermalResistivity left, ThermalResistivity right)
        {
            return left.Value < right.As(left.Unit);
        }

        /// <summary>Returns true if greater than.</summary>
        public static bool operator >(ThermalResistivity left, ThermalResistivity right)
        {
            return left.Value > right.As(left.Unit);
        }

        /// <summary>
        ///     Determines whether two <see cref="ThermalResistivity"/> instances are equal.
        /// </summary>
        /// <remarks>
        ///     Equality is evaluated in a unit-aware manner. The right-hand operand is converted to the unit of the left-hand
        ///     operand and then the underlying numeric values are compared.
        ///     This means two quantities with numerically equal values but different units will be considered equal.
        ///     The operator delegates to <see cref="Equals(ThermalResistivity)"/>, which implements this conversion-and-compare logic.
        /// </remarks>
        public static bool operator ==(ThermalResistivity left, ThermalResistivity right)
        {
            return left.Equals(right);
        }

        /// <summary>
        ///     Determines whether two <see cref="ThermalResistivity"/> instances are not equal.
        /// </summary>
        /// <remarks>
        ///     This operator is the logical negation of <see cref="operator ==(ThermalResistivity,ThermalResistivity)"/>.
        ///     See that operator (and <see cref="Equals(ThermalResistivity)"/>) for details on how equality is evaluated
        ///     (i.e., by converting one operand to the other's unit and comparing their numeric values).
        /// </remarks>
        public static bool operator !=(ThermalResistivity left, ThermalResistivity right)
        {
            return !(left == right);
        }

        /// <inheritdoc />
        /// <summary>
        ///     Determines whether the specified object is equal to the current <see cref="ThermalResistivity"/> instance.
        /// </summary>
        /// <remarks>
        ///     Returns <c>false</c> if <paramref name="obj"/> is <c>null</c> or not a <see cref="ThermalResistivity"/>.
        ///     When <paramref name="obj"/> is a <see cref="ThermalResistivity"/>, this method delegates to
        ///     <see cref="Equals(ThermalResistivity)"/>, which performs a unit-aware comparison by converting the other
        ///     instance to this instance's unit before comparing numeric values.
        /// </remarks>
        public override bool Equals(object? obj)
        {
            if (obj is not ThermalResistivity otherQuantity)
                return false;

            return Equals(otherQuantity);
        }

        /// <inheritdoc />
        /// <summary>
        ///     Determines whether the current instance is equal to another <see cref="ThermalResistivity"/> instance.
        /// </summary>
        /// <remarks>
        ///     Comparison is performed by converting <paramref name="other"/> to this instance's unit and then comparing the underlying numeric values.
        ///     This makes two quantities equal even when their units differ, provided the converted numeric values are equal.
        /// </remarks>
        public bool Equals(ThermalResistivity other)
        {
            return _value.Equals(other.As(this.Unit));
        }

        /// <summary>
        ///     Returns the hash code for this instance.
        /// </summary>
        /// <returns>A hash code for the current ThermalResistivity.</returns>
        public override int GetHashCode()
        {
            return Comparison.GetHashCode(typeof(ThermalResistivity), this.As(BaseUnit));
        }

        /// <inheritdoc  cref="CompareTo(ThermalResistivity)" />
        /// <param name="obj">An object to compare with this instance.</param>
        /// <exception cref="T:System.ArgumentException">
        ///    <paramref name="obj" /> is not the same type as this instance.
        /// </exception>
        public int CompareTo(object? obj)
        {
            if (obj is not ThermalResistivity otherQuantity)
                throw obj is null ? new ArgumentNullException(nameof(obj)) : ExceptionHelper.CreateArgumentException<ThermalResistivity>(obj, nameof(obj));

            return CompareTo(otherQuantity);
        }

        /// <summary>
        ///     Compares the current <see cref="ThermalResistivity"/> with another <see cref="ThermalResistivity"/> and returns an integer that indicates
        ///     whether the current instance precedes, follows, or occurs in the same position in the sort order as the other quantity, when converted to the same unit.
        /// </summary>
        /// <param name="other">A quantity to compare with this instance.</param>
        /// <returns>A value that indicates the relative order of the quantities being compared. The return value has these meanings:
        ///     <list type="table">
        ///         <listheader><term> Value</term><description> Meaning</description></listheader>
        ///         <item><term> Less than zero</term><description> This instance precedes <paramref name="other" /> in the sort order.</description></item>
        ///         <item><term> Zero</term><description> This instance occurs in the same position in the sort order as <paramref name="other" />.</description></item>
        ///         <item><term> Greater than zero</term><description> This instance follows <paramref name="other" /> in the sort order.</description></item>
        ///     </list>
        /// </returns>
        public int CompareTo(ThermalResistivity other)
        {
            return _value.CompareTo(other.As(this.Unit));
        }

        #endregion

        #region ToString Methods

        /// <summary>
        ///     Gets the default string representation of value and unit.
        /// </summary>
        /// <returns>String representation.</returns>
        public override string ToString()
        {
            return ToString(null, null);
        }

        /// <inheritdoc cref="QuantityFormatter.Format{TQuantity}(TQuantity, string, IFormatProvider)"/>
        /// <summary>
        /// Gets the string representation of this instance in the specified format string using the specified format provider, or <see cref="CultureInfo.CurrentCulture" /> if null.
        /// </summary>
        public string ToString(
            [StringSyntax(StringSyntaxAttribute.NumericFormat)] string? format,
            IFormatProvider? provider)
        {
            return QuantityFormatter.Default.Format(this, format, provider);
        }

        #endregion

    }
}
