//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

using System.Globalization;
using System.Resources;
using System.Runtime.Serialization;
using UnitsNet.Debug;
using System.Runtime.CompilerServices;

#nullable enable

// ReSharper disable once CheckNamespace

namespace UnitsNet
{
    /// <inheritdoc />
    /// <summary>
    ///     Torque, moment or moment of force (see the terminology below), is the tendency of a force to rotate an object about an axis,[1] fulcrum, or pivot. Just as a force is a push or a pull, a torque can be thought of as a twist to an object. Mathematically, torque is defined as the cross product of the lever-arm distance and force, which tends to produce rotation. Loosely speaking, torque is a measure of the turning force on an object such as a bolt or a flywheel. For example, pushing or pulling the handle of a wrench connected to a nut or bolt produces a torque (turning force) that loosens or tightens the nut or bolt.
    /// </summary>
    [DataContract]
    [DebuggerDisplay(QuantityDebugProxy.DisplayFormat)]
    [DebuggerTypeProxy(typeof(QuantityDebugProxy))]
    public readonly partial struct Torque :
        ILinearQuantity<Torque, TorqueUnit>,
#if NET7_0_OR_GREATER
        IDivisionOperators<Torque, Torque, QuantityValue>,
        IDivisionOperators<Torque, RotationalStiffness, Angle>,
        IDivisionOperators<Torque, ForcePerLength, Area>,
        IDivisionOperators<Torque, Length, Force>,
        IDivisionOperators<Torque, Area, ForcePerLength>,
        IDivisionOperators<Torque, Force, Length>,
        IMultiplyOperators<Torque, RotationalSpeed, Power>,
        IDivisionOperators<Torque, Angle, RotationalStiffness>,
        IComparisonOperators<Torque, Torque, bool>,
        IParsable<Torque>,
#endif
        IComparable,
        IComparable<Torque>,
        IEquatable<Torque>,
        IFormattable
    {
        /// <summary>
        ///     The numeric value this quantity was constructed with.
        /// </summary>
        [DataMember(Name = "Value", Order = 1)]
        private readonly QuantityValue _value;

        /// <summary>
        ///     The unit this quantity was constructed with.
        /// </summary>
        [DataMember(Name = "Unit", Order = 2)]
        private readonly TorqueUnit? _unit;

        /// <summary>
        ///     Provides detailed information about the <see cref="Torque"/> quantity, including its name, base unit, unit mappings, base dimensions, and conversion functions.
        /// </summary>
        public sealed class TorqueInfo : QuantityInfo<Torque, TorqueUnit>
        {
            /// <inheritdoc />
            public TorqueInfo(string name, TorqueUnit baseUnit, IEnumerable<IUnitDefinition<TorqueUnit>> unitMappings, Torque zero, BaseDimensions baseDimensions,
                QuantityFromDelegate<Torque, TorqueUnit> fromDelegate, ResourceManager? unitAbbreviations)
                : base(name, baseUnit, unitMappings, zero, baseDimensions, fromDelegate, unitAbbreviations)
            {
            }

            /// <inheritdoc />
            public TorqueInfo(string name, TorqueUnit baseUnit, IEnumerable<IUnitDefinition<TorqueUnit>> unitMappings, Torque zero, BaseDimensions baseDimensions)
                : this(name, baseUnit, unitMappings, zero, baseDimensions, Torque.From, new ResourceManager("UnitsNet.GeneratedCode.Resources.Torque", typeof(Torque).Assembly))
            {
            }

            /// <summary>
            ///     Creates a new instance of the <see cref="TorqueInfo"/> class with the default settings for the Torque quantity.
            /// </summary>
            /// <returns>A new instance of the <see cref="TorqueInfo"/> class with the default settings.</returns>
            public static TorqueInfo CreateDefault()
                => new(nameof(Torque), DefaultBaseUnit, GetDefaultMappings(), new(0, DefaultBaseUnit), DefaultBaseDimensions);

            /// <summary>
            ///     Creates a new instance of the <see cref="TorqueInfo"/> class with the default settings for the Torque quantity and a callback for customizing the default unit mappings.
            /// </summary>
            /// <param name="customizeUnits">
            ///     A callback function for customizing the default unit mappings.
            /// </param>
            /// <returns>
            ///     A new instance of the <see cref="TorqueInfo"/> class with the default settings.
            /// </returns>
            public static TorqueInfo CreateDefault(Func<IEnumerable<UnitDefinition<TorqueUnit>>, IEnumerable<IUnitDefinition<TorqueUnit>>> customizeUnits)
                => new(nameof(Torque), DefaultBaseUnit, customizeUnits(GetDefaultMappings()), new(0, DefaultBaseUnit), DefaultBaseDimensions);

            /// <summary>
            ///     The <see cref="BaseDimensions" /> for <see cref="Torque"/> is T^-2L^2M.
            /// </summary>
            public static BaseDimensions DefaultBaseDimensions
            {
                [MethodImpl(MethodImplOptions.AggressiveInlining)]
                get;
            } = new BaseDimensions(2, 1, -2, 0, 0, 0, 0);

            /// <summary>
            ///     The default base unit of Torque is NewtonMeter. All conversions, as defined in the <see cref="GetDefaultMappings"/>, go via this value.
            /// </summary>
            public static TorqueUnit DefaultBaseUnit
            {
                [MethodImpl(MethodImplOptions.AggressiveInlining)]
                get;
            } = TorqueUnit.NewtonMeter;

            /// <summary>
            ///     Retrieves the default mappings for <see cref="TorqueUnit"/>.
            /// </summary>
            /// <returns>An <see cref="IEnumerable{T}"/> of <see cref="UnitDefinition{TorqueUnit}"/> representing the default unit mappings for Torque.</returns>
            public static IEnumerable<UnitDefinition<TorqueUnit>> GetDefaultMappings()
            {
                yield return new (TorqueUnit.GramForceCentimeter, "GramForceCentimeter", "GramForceCentimeters", BaseUnits.Undefined,
                     new QuantityValue(2000000000, 196133)
                );
                yield return new (TorqueUnit.GramForceMeter, "GramForceMeter", "GramForceMeters", BaseUnits.Undefined,
                     new QuantityValue(20000000, 196133)
                );
                yield return new (TorqueUnit.GramForceMillimeter, "GramForceMillimeter", "GramForceMillimeters", BaseUnits.Undefined,
                     new QuantityValue(20000000000, 196133)
                );
                yield return new (TorqueUnit.KilogramForceCentimeter, "KilogramForceCentimeter", "KilogramForceCentimeters", BaseUnits.Undefined,
                     new QuantityValue(2000000, 196133)
                );
                yield return new (TorqueUnit.KilogramForceMeter, "KilogramForceMeter", "KilogramForceMeters", BaseUnits.Undefined,
                     new QuantityValue(20000, 196133)
                );
                yield return new (TorqueUnit.KilogramForceMillimeter, "KilogramForceMillimeter", "KilogramForceMillimeters", BaseUnits.Undefined,
                     new QuantityValue(20000000, 196133)
                );
                yield return new (TorqueUnit.KilonewtonCentimeter, "KilonewtonCentimeter", "KilonewtonCentimeters", BaseUnits.Undefined,
                     new QuantityValue(1, 10)
                );
                yield return new (TorqueUnit.KilonewtonMeter, "KilonewtonMeter", "KilonewtonMeters", BaseUnits.Undefined,
                     new QuantityValue(1, 1000)
                );
                yield return new (TorqueUnit.KilonewtonMillimeter, "KilonewtonMillimeter", "KilonewtonMillimeters", BaseUnits.Undefined,
                     1
                );
                yield return new (TorqueUnit.KilopoundForceFoot, "KilopoundForceFoot", "KilopoundForceFeet", BaseUnits.Undefined,
                     new QuantityValue(2500000000000, 3389544870828501)
                );
                yield return new (TorqueUnit.KilopoundForceInch, "KilopoundForceInch", "KilopoundForceInches", BaseUnits.Undefined,
                     new QuantityValue(10000000000000, 1129848290276167)
                );
                yield return new (TorqueUnit.MeganewtonCentimeter, "MeganewtonCentimeter", "MeganewtonCentimeters", BaseUnits.Undefined,
                     new QuantityValue(1, 10000)
                );
                yield return new (TorqueUnit.MeganewtonMeter, "MeganewtonMeter", "MeganewtonMeters", new BaseUnits(length: LengthUnit.Kilometer, mass: MassUnit.Kilogram, time: DurationUnit.Second),
                     new QuantityValue(1, 1000000)
                );
                yield return new (TorqueUnit.MeganewtonMillimeter, "MeganewtonMillimeter", "MeganewtonMillimeters", BaseUnits.Undefined,
                     new QuantityValue(1, 1000)
                );
                yield return new (TorqueUnit.MegapoundForceFoot, "MegapoundForceFoot", "MegapoundForceFeet", BaseUnits.Undefined,
                     new QuantityValue(2500000000, 3389544870828501)
                );
                yield return new (TorqueUnit.MegapoundForceInch, "MegapoundForceInch", "MegapoundForceInches", BaseUnits.Undefined,
                     new QuantityValue(10000000000, 1129848290276167)
                );
                yield return new (TorqueUnit.NewtonCentimeter, "NewtonCentimeter", "NewtonCentimeters", BaseUnits.Undefined,
                     100
                );
                yield return new (TorqueUnit.NewtonMeter, "NewtonMeter", "NewtonMeters", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Kilogram, time: DurationUnit.Second));
                yield return new (TorqueUnit.NewtonMillimeter, "NewtonMillimeter", "NewtonMillimeters", BaseUnits.Undefined,
                     1000
                );
                yield return new (TorqueUnit.OunceForceFoot, "OunceForceFoot", "OunceForceFeet", BaseUnits.Undefined,
                     new QuantityValue(40000000000000000, 3389544870828501)
                );
                yield return new (TorqueUnit.OunceForceInch, "OunceForceInch", "OunceForceInches", BaseUnits.Undefined,
                     new QuantityValue(160000000000000000, 1129848290276167)
                );
                yield return new (TorqueUnit.PoundalFoot, "PoundalFoot", "PoundalFeet", BaseUnits.Undefined,
                     new QuantityValue(156250000000000, 6584392202157)
                );
                yield return new (TorqueUnit.PoundForceFoot, "PoundForceFoot", "PoundForceFeet", BaseUnits.Undefined,
                     new QuantityValue(2500000000000000, 3389544870828501)
                );
                yield return new (TorqueUnit.PoundForceInch, "PoundForceInch", "PoundForceInches", BaseUnits.Undefined,
                     new QuantityValue(10000000000000000, 1129848290276167)
                );
                yield return new (TorqueUnit.TonneForceCentimeter, "TonneForceCentimeter", "TonneForceCentimeters", BaseUnits.Undefined,
                     new QuantityValue(2000, 196133)
                );
                yield return new (TorqueUnit.TonneForceMeter, "TonneForceMeter", "TonneForceMeters", BaseUnits.Undefined,
                     new QuantityValue(20, 196133)
                );
                yield return new (TorqueUnit.TonneForceMillimeter, "TonneForceMillimeter", "TonneForceMillimeters", BaseUnits.Undefined,
                     new QuantityValue(20000, 196133)
                );
            }
        }

        static Torque()
        {
            Info = UnitsNetSetup.CreateQuantityInfo(TorqueInfo.CreateDefault);
        }

        /// <summary>
        ///     Creates the quantity with the given numeric value and unit.
        /// </summary>
        /// <param name="value">The numeric value to construct this quantity with.</param>
        /// <param name="unit">The unit representation to construct this quantity with.</param>
        public Torque(QuantityValue value, TorqueUnit unit)
        {
            _value = value;
            _unit = unit;
        }

        /// <summary>
        /// Creates an instance of the quantity with the given numeric value in units compatible with the given <see cref="UnitSystem"/>.
        /// If multiple compatible units were found, the first match is used.
        /// </summary>
        /// <param name="value">The numeric value to construct this quantity with.</param>
        /// <param name="unitSystem">The unit system to create the quantity with.</param>
        /// <exception cref="ArgumentNullException">The given <see cref="UnitSystem"/> is null.</exception>
        /// <exception cref="ArgumentException">No unit was found for the given <see cref="UnitSystem"/>.</exception>
        public Torque(QuantityValue value, UnitSystem unitSystem)
        {
            _value = value;
            _unit = Info.GetDefaultUnit(unitSystem);
        }

        #region Static Properties

        /// <summary>
        ///     The <see cref="UnitConverter" /> containing the default generated conversion functions for <see cref="Torque" /> instances.
        /// </summary>
        [Obsolete("Replaced by UnitConverter.Default")]
        public static UnitConverter DefaultConversionFunctions
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => UnitConverter.Default;
        }

        /// <inheritdoc cref="IQuantity.QuantityInfo"/>
        public static QuantityInfo<Torque, TorqueUnit> Info { get; }

        /// <summary>
        ///     The <see cref="BaseDimensions" /> of this quantity.
        /// </summary>
        public static BaseDimensions BaseDimensions
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => Info.BaseDimensions;
        }

        /// <summary>
        ///     The base unit of Torque, which is NewtonMeter. All conversions go via this value.
        /// </summary>
        public static TorqueUnit BaseUnit
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => Info.BaseUnitInfo.Value;
        }

        /// <summary>
        ///     All units of measurement for the Torque quantity.
        /// </summary>
        public static IReadOnlyCollection<TorqueUnit> Units
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => Info.Units;
        }

        /// <summary>
        ///     Gets an instance of this quantity with a value of 0 in the base unit NewtonMeter.
        /// </summary>
        public static Torque Zero
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => Info.Zero;
        }

        #endregion

        #region Properties

        /// <inheritdoc />
        public QuantityValue Value
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => _value;
        }

        /// <inheritdoc />
        public TorqueUnit Unit
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => _unit.GetValueOrDefault(BaseUnit);
        }

        /// <inheritdoc />
        public QuantityInfo<Torque, TorqueUnit> QuantityInfo
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => Info;
        }

        #region Explicit implementations

        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        UnitKey IQuantity.UnitKey
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => UnitKey.ForUnit(Unit);
        }

#if NETSTANDARD2_0
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        IQuantityInstanceInfo<Torque> IQuantityOfType<Torque>.QuantityInfo
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => Info;
        }

        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        QuantityInfo<TorqueUnit> IQuantity<TorqueUnit>.QuantityInfo
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => Info;
        }

        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        QuantityInfo IQuantity.QuantityInfo
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => Info;
        }

        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        Enum IQuantity.Unit
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => Unit;
        }
#endif

        #endregion

        #endregion

        #region Conversion Properties

        /// <inheritdoc cref="IQuantity{Torque,TorqueUnit}.AsBaseQuantity"/>
        /// <returns><see cref="TorqueUnit.NewtonMeter"/></returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Torque AsBaseQuantity()
            => new(this.As(BaseUnit), BaseUnit);

        /// <inheritdoc cref="IQuantity{Torque,TorqueUnit}.AsBaseValue"/>
        /// <returns><see cref="TorqueUnit.NewtonMeter"/></returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public QuantityValue AsBaseValue()
            => this.As(BaseUnit);

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="TorqueUnit.GramForceCentimeter"/>
        /// </summary>
        public QuantityValue GramForceCentimeters
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(TorqueUnit.GramForceCentimeter);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="TorqueUnit.GramForceMeter"/>
        /// </summary>
        public QuantityValue GramForceMeters
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(TorqueUnit.GramForceMeter);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="TorqueUnit.GramForceMillimeter"/>
        /// </summary>
        public QuantityValue GramForceMillimeters
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(TorqueUnit.GramForceMillimeter);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="TorqueUnit.KilogramForceCentimeter"/>
        /// </summary>
        public QuantityValue KilogramForceCentimeters
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(TorqueUnit.KilogramForceCentimeter);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="TorqueUnit.KilogramForceMeter"/>
        /// </summary>
        public QuantityValue KilogramForceMeters
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(TorqueUnit.KilogramForceMeter);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="TorqueUnit.KilogramForceMillimeter"/>
        /// </summary>
        public QuantityValue KilogramForceMillimeters
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(TorqueUnit.KilogramForceMillimeter);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="TorqueUnit.KilonewtonCentimeter"/>
        /// </summary>
        public QuantityValue KilonewtonCentimeters
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(TorqueUnit.KilonewtonCentimeter);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="TorqueUnit.KilonewtonMeter"/>
        /// </summary>
        public QuantityValue KilonewtonMeters
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(TorqueUnit.KilonewtonMeter);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="TorqueUnit.KilonewtonMillimeter"/>
        /// </summary>
        public QuantityValue KilonewtonMillimeters
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(TorqueUnit.KilonewtonMillimeter);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="TorqueUnit.KilopoundForceFoot"/>
        /// </summary>
        public QuantityValue KilopoundForceFeet
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(TorqueUnit.KilopoundForceFoot);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="TorqueUnit.KilopoundForceInch"/>
        /// </summary>
        public QuantityValue KilopoundForceInches
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(TorqueUnit.KilopoundForceInch);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="TorqueUnit.MeganewtonCentimeter"/>
        /// </summary>
        public QuantityValue MeganewtonCentimeters
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(TorqueUnit.MeganewtonCentimeter);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="TorqueUnit.MeganewtonMeter"/>
        /// </summary>
        public QuantityValue MeganewtonMeters
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(TorqueUnit.MeganewtonMeter);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="TorqueUnit.MeganewtonMillimeter"/>
        /// </summary>
        public QuantityValue MeganewtonMillimeters
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(TorqueUnit.MeganewtonMillimeter);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="TorqueUnit.MegapoundForceFoot"/>
        /// </summary>
        public QuantityValue MegapoundForceFeet
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(TorqueUnit.MegapoundForceFoot);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="TorqueUnit.MegapoundForceInch"/>
        /// </summary>
        public QuantityValue MegapoundForceInches
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(TorqueUnit.MegapoundForceInch);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="TorqueUnit.NewtonCentimeter"/>
        /// </summary>
        public QuantityValue NewtonCentimeters
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(TorqueUnit.NewtonCentimeter);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="TorqueUnit.NewtonMeter"/>
        /// </summary>
        public QuantityValue NewtonMeters
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(TorqueUnit.NewtonMeter);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="TorqueUnit.NewtonMillimeter"/>
        /// </summary>
        public QuantityValue NewtonMillimeters
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(TorqueUnit.NewtonMillimeter);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="TorqueUnit.OunceForceFoot"/>
        /// </summary>
        public QuantityValue OunceForceFeet
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(TorqueUnit.OunceForceFoot);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="TorqueUnit.OunceForceInch"/>
        /// </summary>
        public QuantityValue OunceForceInches
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(TorqueUnit.OunceForceInch);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="TorqueUnit.PoundalFoot"/>
        /// </summary>
        public QuantityValue PoundalFeet
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(TorqueUnit.PoundalFoot);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="TorqueUnit.PoundForceFoot"/>
        /// </summary>
        public QuantityValue PoundForceFeet
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(TorqueUnit.PoundForceFoot);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="TorqueUnit.PoundForceInch"/>
        /// </summary>
        public QuantityValue PoundForceInches
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(TorqueUnit.PoundForceInch);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="TorqueUnit.TonneForceCentimeter"/>
        /// </summary>
        public QuantityValue TonneForceCentimeters
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(TorqueUnit.TonneForceCentimeter);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="TorqueUnit.TonneForceMeter"/>
        /// </summary>
        public QuantityValue TonneForceMeters
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(TorqueUnit.TonneForceMeter);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="TorqueUnit.TonneForceMillimeter"/>
        /// </summary>
        public QuantityValue TonneForceMillimeters
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(TorqueUnit.TonneForceMillimeter);
        }

        #endregion

        #region Static Methods

        /// <summary>
        ///     Get unit abbreviation string.
        /// </summary>
        /// <param name="unit">Unit to get abbreviation for.</param>
        /// <returns>Unit abbreviation string.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static string GetAbbreviation(TorqueUnit unit)
            => GetAbbreviation(unit, null);

        /// <summary>
        ///     Get unit abbreviation string.
        /// </summary>
        /// <param name="unit">Unit to get abbreviation for.</param>
        /// <returns>Unit abbreviation string.</returns>
        /// <param name="provider">Format to use for localization. Defaults to <see cref="CultureInfo.CurrentCulture" /> if null.</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static string GetAbbreviation(TorqueUnit unit, IFormatProvider? provider)
            => UnitsNetSetup.Default.UnitAbbreviations.GetDefaultAbbreviation(unit, provider);

        #endregion

        #region Static Factory Methods

        /// <summary>
        ///     Convert to base unit quantity of NewtonMeter.
        /// </summary>
        public Torque NewtonMetersToTorque()
            => new(this.As(BaseUnit), BaseUnit);

        /// <summary>
        ///     Creates a <see cref="Torque"/> from <see cref="TorqueUnit.GramForceCentimeter"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Torque FromGramForceCentimeters(QuantityValue value)
            => new(value, TorqueUnit.GramForceCentimeter);

        /// <summary>
        ///     Creates a <see cref="Torque"/> from <see cref="TorqueUnit.GramForceMeter"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Torque FromGramForceMeters(QuantityValue value)
            => new(value, TorqueUnit.GramForceMeter);

        /// <summary>
        ///     Creates a <see cref="Torque"/> from <see cref="TorqueUnit.GramForceMillimeter"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Torque FromGramForceMillimeters(QuantityValue value)
            => new(value, TorqueUnit.GramForceMillimeter);

        /// <summary>
        ///     Creates a <see cref="Torque"/> from <see cref="TorqueUnit.KilogramForceCentimeter"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Torque FromKilogramForceCentimeters(QuantityValue value)
            => new(value, TorqueUnit.KilogramForceCentimeter);

        /// <summary>
        ///     Creates a <see cref="Torque"/> from <see cref="TorqueUnit.KilogramForceMeter"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Torque FromKilogramForceMeters(QuantityValue value)
            => new(value, TorqueUnit.KilogramForceMeter);

        /// <summary>
        ///     Creates a <see cref="Torque"/> from <see cref="TorqueUnit.KilogramForceMillimeter"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Torque FromKilogramForceMillimeters(QuantityValue value)
            => new(value, TorqueUnit.KilogramForceMillimeter);

        /// <summary>
        ///     Creates a <see cref="Torque"/> from <see cref="TorqueUnit.KilonewtonCentimeter"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Torque FromKilonewtonCentimeters(QuantityValue value)
            => new(value, TorqueUnit.KilonewtonCentimeter);

        /// <summary>
        ///     Creates a <see cref="Torque"/> from <see cref="TorqueUnit.KilonewtonMeter"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Torque FromKilonewtonMeters(QuantityValue value)
            => new(value, TorqueUnit.KilonewtonMeter);

        /// <summary>
        ///     Creates a <see cref="Torque"/> from <see cref="TorqueUnit.KilonewtonMillimeter"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Torque FromKilonewtonMillimeters(QuantityValue value)
            => new(value, TorqueUnit.KilonewtonMillimeter);

        /// <summary>
        ///     Creates a <see cref="Torque"/> from <see cref="TorqueUnit.KilopoundForceFoot"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Torque FromKilopoundForceFeet(QuantityValue value)
            => new(value, TorqueUnit.KilopoundForceFoot);

        /// <summary>
        ///     Creates a <see cref="Torque"/> from <see cref="TorqueUnit.KilopoundForceInch"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Torque FromKilopoundForceInches(QuantityValue value)
            => new(value, TorqueUnit.KilopoundForceInch);

        /// <summary>
        ///     Creates a <see cref="Torque"/> from <see cref="TorqueUnit.MeganewtonCentimeter"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Torque FromMeganewtonCentimeters(QuantityValue value)
            => new(value, TorqueUnit.MeganewtonCentimeter);

        /// <summary>
        ///     Creates a <see cref="Torque"/> from <see cref="TorqueUnit.MeganewtonMeter"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Torque FromMeganewtonMeters(QuantityValue value)
            => new(value, TorqueUnit.MeganewtonMeter);

        /// <summary>
        ///     Creates a <see cref="Torque"/> from <see cref="TorqueUnit.MeganewtonMillimeter"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Torque FromMeganewtonMillimeters(QuantityValue value)
            => new(value, TorqueUnit.MeganewtonMillimeter);

        /// <summary>
        ///     Creates a <see cref="Torque"/> from <see cref="TorqueUnit.MegapoundForceFoot"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Torque FromMegapoundForceFeet(QuantityValue value)
            => new(value, TorqueUnit.MegapoundForceFoot);

        /// <summary>
        ///     Creates a <see cref="Torque"/> from <see cref="TorqueUnit.MegapoundForceInch"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Torque FromMegapoundForceInches(QuantityValue value)
            => new(value, TorqueUnit.MegapoundForceInch);

        /// <summary>
        ///     Creates a <see cref="Torque"/> from <see cref="TorqueUnit.NewtonCentimeter"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Torque FromNewtonCentimeters(QuantityValue value)
            => new(value, TorqueUnit.NewtonCentimeter);

        /// <summary>
        ///     Creates a <see cref="Torque"/> from <see cref="TorqueUnit.NewtonMeter"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Torque FromNewtonMeters(QuantityValue value)
            => new(value, TorqueUnit.NewtonMeter);

        /// <summary>
        ///     Creates a <see cref="Torque"/> from <see cref="TorqueUnit.NewtonMillimeter"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Torque FromNewtonMillimeters(QuantityValue value)
            => new(value, TorqueUnit.NewtonMillimeter);

        /// <summary>
        ///     Creates a <see cref="Torque"/> from <see cref="TorqueUnit.OunceForceFoot"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Torque FromOunceForceFeet(QuantityValue value)
            => new(value, TorqueUnit.OunceForceFoot);

        /// <summary>
        ///     Creates a <see cref="Torque"/> from <see cref="TorqueUnit.OunceForceInch"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Torque FromOunceForceInches(QuantityValue value)
            => new(value, TorqueUnit.OunceForceInch);

        /// <summary>
        ///     Creates a <see cref="Torque"/> from <see cref="TorqueUnit.PoundalFoot"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Torque FromPoundalFeet(QuantityValue value)
            => new(value, TorqueUnit.PoundalFoot);

        /// <summary>
        ///     Creates a <see cref="Torque"/> from <see cref="TorqueUnit.PoundForceFoot"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Torque FromPoundForceFeet(QuantityValue value)
            => new(value, TorqueUnit.PoundForceFoot);

        /// <summary>
        ///     Creates a <see cref="Torque"/> from <see cref="TorqueUnit.PoundForceInch"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Torque FromPoundForceInches(QuantityValue value)
            => new(value, TorqueUnit.PoundForceInch);

        /// <summary>
        ///     Creates a <see cref="Torque"/> from <see cref="TorqueUnit.TonneForceCentimeter"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Torque FromTonneForceCentimeters(QuantityValue value)
            => new(value, TorqueUnit.TonneForceCentimeter);

        /// <summary>
        ///     Creates a <see cref="Torque"/> from <see cref="TorqueUnit.TonneForceMeter"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Torque FromTonneForceMeters(QuantityValue value)
            => new(value, TorqueUnit.TonneForceMeter);

        /// <summary>
        ///     Creates a <see cref="Torque"/> from <see cref="TorqueUnit.TonneForceMillimeter"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Torque FromTonneForceMillimeters(QuantityValue value)
            => new(value, TorqueUnit.TonneForceMillimeter);

        /// <summary>
        ///     Dynamically convert from value and unit enum <see cref="TorqueUnit" /> to <see cref="Torque" />.
        /// </summary>
        /// <param name="value">Value to convert from.</param>
        /// <param name="fromUnit">Unit to convert from.</param>
        /// <returns>Torque unit value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Torque From(QuantityValue value, TorqueUnit fromUnit)
            => new(value, fromUnit);

        #endregion

        #region Static Parse Methods

        /// <summary>
        ///     Parse a string with one or two quantities of the format "&lt;quantity&gt; &lt;unit&gt;".
        /// </summary>
        /// <param name="str">String to parse. Typically in the form: {number} {unit}</param>
        /// <example>
        ///     Length.Parse("5.5 m", CultureInfo.GetCultureInfo("en-US"));
        /// </example>
        /// <exception cref="ArgumentNullException">The value of 'str' cannot be null. </exception>
        /// <exception cref="ArgumentException">
        ///     Expected string to have one or two pairs of quantity and unit in the format
        ///     "&lt;quantity&gt; &lt;unit&gt;". Eg. "5.5 m" or "1ft 2in"
        /// </exception>
        /// <exception cref="AmbiguousUnitParseException">
        ///     More than one unit is represented by the specified unit abbreviation.
        ///     Example: Volume.Parse("1 cup") will throw, because it can refer to any of
        ///     <see cref="VolumeUnit.MetricCup" />, <see cref="VolumeUnit.UsLegalCup" /> and <see cref="VolumeUnit.UsCustomaryCup" />.
        /// </exception>
        /// <exception cref="UnitsNetException">
        ///     If anything else goes wrong, typically due to a bug or unhandled case.
        ///     We wrap exceptions in <see cref="UnitsNetException" /> to allow you to distinguish
        ///     Units.NET exceptions from other exceptions.
        /// </exception>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Torque Parse(string str)
            => Parse(str, null);

        /// <summary>
        ///     Parse a string with one or two quantities of the format "&lt;quantity&gt; &lt;unit&gt;".
        /// </summary>
        /// <param name="str">String to parse. Typically in the form: {number} {unit}</param>
        /// <example>
        ///     Length.Parse("5.5 m", CultureInfo.GetCultureInfo("en-US"));
        /// </example>
        /// <exception cref="ArgumentNullException">The value of 'str' cannot be null. </exception>
        /// <exception cref="ArgumentException">
        ///     Expected string to have one or two pairs of quantity and unit in the format
        ///     "&lt;quantity&gt; &lt;unit&gt;". Eg. "5.5 m" or "1ft 2in"
        /// </exception>
        /// <exception cref="AmbiguousUnitParseException">
        ///     More than one unit is represented by the specified unit abbreviation.
        ///     Example: Volume.Parse("1 cup") will throw, because it can refer to any of
        ///     <see cref="VolumeUnit.MetricCup" />, <see cref="VolumeUnit.UsLegalCup" /> and <see cref="VolumeUnit.UsCustomaryCup" />.
        /// </exception>
        /// <exception cref="UnitsNetException">
        ///     If anything else goes wrong, typically due to a bug or unhandled case.
        ///     We wrap exceptions in <see cref="UnitsNetException" /> to allow you to distinguish
        ///     Units.NET exceptions from other exceptions.
        /// </exception>
        /// <param name="provider">Format to use when parsing number and unit. Defaults to <see cref="CultureInfo.CurrentCulture" /> if null.</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Torque Parse(string str, IFormatProvider? provider)
            => QuantityParser.Default.Parse<Torque, TorqueUnit>(str, provider, From);

        /// <summary>
        ///     Try to parse a string with one or two quantities of the format "&lt;quantity&gt; &lt;unit&gt;".
        /// </summary>
        /// <param name="str">String to parse. Typically in the form: {number} {unit}</param>
        /// <param name="result">Resulting unit quantity if successful.</param>
        /// <example>
        ///     Length.Parse("5.5 m", CultureInfo.GetCultureInfo("en-US"));
        /// </example>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool TryParse([NotNullWhen(true)]string? str, out Torque result)
            => TryParse(str, null, out result);

        /// <summary>
        ///     Try to parse a string with one or two quantities of the format "&lt;quantity&gt; &lt;unit&gt;".
        /// </summary>
        /// <param name="str">String to parse. Typically in the form: {number} {unit}</param>
        /// <param name="result">Resulting unit quantity if successful.</param>
        /// <returns>True if successful, otherwise false.</returns>
        /// <example>
        ///     Length.Parse("5.5 m", CultureInfo.GetCultureInfo("en-US"));
        /// </example>
        /// <param name="provider">Format to use when parsing number and unit. Defaults to <see cref="CultureInfo.CurrentCulture" /> if null.</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool TryParse([NotNullWhen(true)]string? str, IFormatProvider? provider, out Torque result)
            => QuantityParser.Default.TryParse<Torque, TorqueUnit>(str, provider, From, out result);

        /// <summary>
        ///     Parse a unit string.
        /// </summary>
        /// <param name="str">String to parse. Typically in the form: {number} {unit}</param>
        /// <example>
        ///     Length.ParseUnit("m", CultureInfo.GetCultureInfo("en-US"));
        /// </example>
        /// <exception cref="ArgumentNullException">The value of 'str' cannot be null. </exception>
        /// <exception cref="UnitsNetException">Error parsing string.</exception>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static TorqueUnit ParseUnit(string str)
            => ParseUnit(str, null);

        /// <summary>
        ///     Parse a unit string.
        /// </summary>
        /// <param name="str">String to parse. Typically in the form: {number} {unit}</param>
        /// <param name="provider">Format to use when parsing the unit. Defaults to <see cref="CultureInfo.CurrentCulture" /> if null.</param>
        /// <example>
        ///     Length.ParseUnit("m", CultureInfo.GetCultureInfo("en-US"));
        /// </example>
        /// <exception cref="ArgumentNullException">The value of 'str' cannot be null. </exception>
        /// <exception cref="UnitsNetException">Error parsing string.</exception>
        public static TorqueUnit ParseUnit(string str, IFormatProvider? provider)
            => UnitParser.Default.Parse(str, Info.UnitInfos, provider).Value;

        /// <inheritdoc cref="TryParseUnit(string,IFormatProvider?,out UnitsNet.Units.TorqueUnit)"/>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool TryParseUnit([NotNullWhen(true)]string? str, out TorqueUnit unit)
            => TryParseUnit(str, null, out unit);

        /// <summary>
        ///     Parse a unit string.
        /// </summary>
        /// <param name="str">String to parse. Typically in the form: {number} {unit}</param>
        /// <param name="unit">The parsed unit if successful.</param>
        /// <returns>True if successful, otherwise false.</returns>
        /// <example>
        ///     Length.TryParseUnit("m", CultureInfo.GetCultureInfo("en-US"));
        /// </example>
        /// <param name="provider">Format to use when parsing the unit. Defaults to <see cref="CultureInfo.CurrentCulture" /> if null.</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool TryParseUnit([NotNullWhen(true)]string? str, IFormatProvider? provider, out TorqueUnit unit)
            => UnitParser.Default.TryParse(str, Info, provider, out unit);

        #endregion

        /// <summary>
        /// Gets value of base unit.
        /// </summary>
        /// <param name="d"></param>
        [Obsolete("Gets value of base unit. Use factory methods instead to specify unit conversion.")]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator QuantityValue(Torque d) => d.As(BaseUnit);

        /// <summary>
        /// Gets quantity of base unit.
        /// </summary>
        /// <param name="d"></param>
        [Obsolete("Gets value of base unit. Use factory methods instead to specify unit conversion.")]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator Torque(QuantityValue d) => new(d, BaseUnit);

        /// <summary>
        /// Gets value of base unit.
        /// </summary>
        /// <param name="d"></param>
        [Obsolete("Gets value of base unit. Use factory methods instead to specify unit conversion.")]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static explicit operator double(Torque d) => d.As(BaseUnit);

        /// <summary>
        /// Gets quantity of base unit.
        /// </summary>
        /// <param name="d"></param>
        [Obsolete("Gets value of base unit. Use factory methods instead to specify unit conversion.")]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static explicit operator Torque(double d) => new(d, BaseUnit);

        #region Arithmetic Operators

        /// <summary>Negate the value.</summary>
        public static Torque operator -(Torque right)
            => new(-right.Value, right.Unit);

        /// <summary>Get <see cref="Torque"/> from adding two <see cref="Torque"/>.</summary>
        public static Torque operator +(Torque left, Torque right)
            => new(left.Value + right.As(left.Unit), left.Unit);

        /// <summary>Get <see cref="Torque"/> from subtracting two <see cref="Torque"/>.</summary>
        public static Torque operator -(Torque left, Torque right)
            => new(left.Value - right.As(left.Unit), left.Unit);

        /// <summary>Get <see cref="Torque"/> from multiplying value and <see cref="Torque"/>.</summary>
        public static Torque operator *(QuantityValue left, Torque right)
            => new(left * right.Value, right.Unit);

        /// <summary>Get <see cref="Torque"/> from multiplying value and <see cref="Torque"/>.</summary>
        public static Torque operator *(Torque left, QuantityValue right)
            => new(left.Value * right, left.Unit);

        /// <summary>Get <see cref="Torque"/> from dividing <see cref="Torque"/> by value.</summary>
        public static Torque operator /(Torque left, QuantityValue right)
            => new(left.Value / right, left.Unit);

        /// <summary>Get ratio value from dividing <see cref="Torque"/> by <see cref="Torque"/>.</summary>
        public static QuantityValue operator /(Torque left, Torque right)
            => left.NewtonMeters / right.NewtonMeters;

        #endregion

        #region Relational Operators

        /// <summary>Get <see cref="Angle"/> from <see cref="Torque"/> / <see cref="RotationalStiffness"/>.</summary>
        public static Angle operator /(Torque torque, RotationalStiffness rotationalStiffness)
            => Angle.FromRadians(torque.NewtonMeters / rotationalStiffness.NewtonMetersPerRadian);

        /// <summary>Get <see cref="Area"/> from <see cref="Torque"/> / <see cref="ForcePerLength"/>.</summary>
        public static Area operator /(Torque torque, ForcePerLength forcePerLength)
            => Area.FromSquareMeters(torque.NewtonMeters / forcePerLength.NewtonsPerMeter);

        /// <summary>Get <see cref="Force"/> from <see cref="Torque"/> / <see cref="Length"/>.</summary>
        public static Force operator /(Torque torque, Length length)
            => Force.FromNewtons(torque.NewtonMeters / length.Meters);

        /// <summary>Get <see cref="ForcePerLength"/> from <see cref="Torque"/> / <see cref="Area"/>.</summary>
        public static ForcePerLength operator /(Torque torque, Area area)
            => ForcePerLength.FromNewtonsPerMeter(torque.NewtonMeters / area.SquareMeters);

        /// <summary>Get <see cref="Length"/> from <see cref="Torque"/> / <see cref="Force"/>.</summary>
        public static Length operator /(Torque torque, Force force)
            => Length.FromMeters(torque.NewtonMeters / force.Newtons);

        /// <summary>Get <see cref="Power"/> from <see cref="Torque"/> * <see cref="RotationalSpeed"/>.</summary>
        public static Power operator *(Torque torque, RotationalSpeed rotationalSpeed)
            => Power.FromWatts(torque.NewtonMeters * rotationalSpeed.RadiansPerSecond);

        /// <summary>Get <see cref="RotationalStiffness"/> from <see cref="Torque"/> / <see cref="Angle"/>.</summary>
        public static RotationalStiffness operator /(Torque torque, Angle angle)
            => RotationalStiffness.FromNewtonMetersPerRadian(torque.NewtonMeters / angle.Radians);

        #endregion

        #region Equality / IComparable

        /// <summary>Returns true if less or equal to.</summary>
        public static bool operator <=(Torque left, Torque right)
            => left.Value <= right.As(left.Unit);

        /// <summary>Returns true if greater than or equal to.</summary>
        public static bool operator >=(Torque left, Torque right)
            => left.Value >= right.As(left.Unit);

        /// <summary>Returns true if less than.</summary>
        public static bool operator <(Torque left, Torque right)
            => left.Value < right.As(left.Unit);

        /// <summary>Returns true if greater than.</summary>
        public static bool operator >(Torque left, Torque right)
            => left.Value > right.As(left.Unit);

        /// <summary>
        ///     Determines whether two <see cref="Torque"/> instances are equal.
        /// </summary>
        /// <remarks>
        ///     Equality is evaluated in a unit-aware manner. The right-hand operand is converted to the unit of the left-hand
        ///     operand and then the underlying numeric values are compared.
        ///     This means two quantities with numerically equal values but different units will be considered equal.
        ///     The operator delegates to <see cref="Equals(Torque)"/>, which implements this conversion-and-compare logic.
        /// </remarks>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool operator ==(Torque left, Torque right)
            => left.Equals(right);

        /// <summary>
        ///     Determines whether two <see cref="Torque"/> instances are not equal.
        /// </summary>
        /// <remarks>
        ///     This operator is the logical negation of <see cref="operator ==(Torque,Torque)"/>.
        ///     See that operator (and <see cref="Equals(Torque)"/>) for details on how equality is evaluated
        ///     (i.e., by converting one operand to the other's unit and comparing their numeric values).
        /// </remarks>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool operator !=(Torque left, Torque right)
            => !(left == right);

        /// <inheritdoc />
        /// <summary>
        ///     Determines whether the specified object is equal to the current <see cref="Torque"/> instance.
        /// </summary>
        /// <remarks>
        ///     Returns <c>false</c> if <paramref name="obj"/> is <c>null</c> or not a <see cref="Torque"/>.
        ///     When <paramref name="obj"/> is a <see cref="Torque"/>, this method delegates to
        ///     <see cref="Equals(Torque)"/>, which performs a unit-aware comparison by converting the other
        ///     instance to this instance's unit before comparing numeric values.
        /// </remarks>
        public override bool Equals(object? obj)
            => obj is Torque otherQuantity && Equals(otherQuantity);

        /// <inheritdoc />
        /// <summary>
        ///     Determines whether the current instance is equal to another <see cref="Torque"/> instance.
        /// </summary>
        /// <remarks>
        ///     Comparison is performed by converting <paramref name="other"/> to this instance's unit and then comparing the underlying numeric values.
        ///     This makes two quantities equal even when their units differ, provided the converted numeric values are equal.
        /// </remarks>
        public bool Equals(Torque other)
            => _value.Equals(other.As(Unit));

        /// <summary>
        ///     Returns the hash code for this instance.
        /// </summary>
        /// <returns>A hash code for the current Torque.</returns>
        public override int GetHashCode()
            => Comparison.GetHashCode(typeof(Torque), this.As(BaseUnit));

        /// <inheritdoc  cref="CompareTo(Torque)" />
        /// <param name="obj">An object to compare with this instance.</param>
        /// <exception cref="T:System.ArgumentException">
        ///    <paramref name="obj" /> is not the same type as this instance.
        /// </exception>
        public int CompareTo(object? obj)
        {
            if (obj is not Torque otherQuantity)
                throw obj is null ? new ArgumentNullException(nameof(obj)) : ExceptionHelper.CreateArgumentException<Torque>(obj, nameof(obj));

            return CompareTo(otherQuantity);
        }

        /// <summary>
        ///     Compares the current <see cref="Torque"/> with another <see cref="Torque"/> and returns an integer that indicates
        ///     whether the current instance precedes, follows, or occurs in the same position in the sort order as the other quantity, when converted to the same unit.
        /// </summary>
        /// <param name="other">A quantity to compare with this instance.</param>
        /// <returns>A value that indicates the relative order of the quantities being compared. The return value has these meanings:
        ///     <list type="table">
        ///         <listheader><term> Value</term><description> Meaning</description></listheader>
        ///         <item><term> Less than zero</term><description> This instance precedes <paramref name="other" /> in the sort order.</description></item>
        ///         <item><term> Zero</term><description> This instance occurs in the same position in the sort order as <paramref name="other" />.</description></item>
        ///         <item><term> Greater than zero</term><description> This instance follows <paramref name="other" /> in the sort order.</description></item>
        ///     </list>
        /// </returns>
        public int CompareTo(Torque other)
            => _value.CompareTo(other.As(Unit));

        #endregion

        #region ToString Methods

        /// <summary>
        ///     Gets the default string representation of value and unit.
        /// </summary>
        /// <returns>String representation.</returns>
        public override string ToString()
            => ToString(null, null);

        /// <inheritdoc cref="QuantityFormatter.Format{TQuantity}(TQuantity, string, IFormatProvider)"/>
        /// <summary>
        /// Gets the string representation of this instance in the specified format string using the specified format provider, or <see cref="CultureInfo.CurrentCulture" /> if null.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public string ToString(
            [StringSyntax(StringSyntaxAttribute.NumericFormat)] string? format,
            IFormatProvider? provider)
            => QuantityFormatter.Default.Format(this, format, provider);

        #endregion

    }
}
