//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

using System.Globalization;
using System.Resources;
using System.Runtime.Serialization;
using UnitsNet.Debug;
using System.Runtime.CompilerServices;

#nullable enable

// ReSharper disable once CheckNamespace

namespace UnitsNet
{
    /// <inheritdoc />
    /// <summary>
    ///     The volume concentration (not to be confused with volume fraction) is defined as the volume of a constituent divided by the total volume of the mixture.
    /// </summary>
    /// <remarks>
    ///     https://en.wikipedia.org/wiki/Concentration#Volume_concentration
    /// </remarks>
    [DataContract]
    [DebuggerDisplay(QuantityDebugProxy.DisplayFormat)]
    [DebuggerTypeProxy(typeof(QuantityDebugProxy))]
    public readonly partial struct VolumeConcentration :
        ILinearQuantity<VolumeConcentration, VolumeConcentrationUnit>,
#if NET7_0_OR_GREATER
        IDivisionOperators<VolumeConcentration, VolumeConcentration, QuantityValue>,
        IMultiplyOperators<VolumeConcentration, Density, MassConcentration>,
        IMultiplyOperators<VolumeConcentration, Molarity, Molarity>,
        IComparisonOperators<VolumeConcentration, VolumeConcentration, bool>,
        IParsable<VolumeConcentration>,
#endif
        IComparable,
        IComparable<VolumeConcentration>,
        IEquatable<VolumeConcentration>,
        IFormattable
    {
        /// <summary>
        ///     The numeric value this quantity was constructed with.
        /// </summary>
        [DataMember(Name = "Value", Order = 1)]
        private readonly QuantityValue _value;

        /// <summary>
        ///     The unit this quantity was constructed with.
        /// </summary>
        [DataMember(Name = "Unit", Order = 2)]
        private readonly VolumeConcentrationUnit? _unit;

        /// <summary>
        ///     Provides detailed information about the <see cref="VolumeConcentration"/> quantity, including its name, base unit, unit mappings, base dimensions, and conversion functions.
        /// </summary>
        public sealed class VolumeConcentrationInfo: QuantityInfo<VolumeConcentration, VolumeConcentrationUnit>
        {
            /// <inheritdoc />
            public VolumeConcentrationInfo(string name, VolumeConcentrationUnit baseUnit, IEnumerable<IUnitDefinition<VolumeConcentrationUnit>> unitMappings, VolumeConcentration zero, BaseDimensions baseDimensions,
                QuantityFromDelegate<VolumeConcentration, VolumeConcentrationUnit> fromDelegate, ResourceManager? unitAbbreviations)
                : base(name, baseUnit, unitMappings, zero, baseDimensions, fromDelegate, unitAbbreviations)
            {
            }

            /// <inheritdoc />
            public VolumeConcentrationInfo(string name, VolumeConcentrationUnit baseUnit, IEnumerable<IUnitDefinition<VolumeConcentrationUnit>> unitMappings, VolumeConcentration zero, BaseDimensions baseDimensions)
                : this(name, baseUnit, unitMappings, zero, baseDimensions, VolumeConcentration.From, new ResourceManager("UnitsNet.GeneratedCode.Resources.VolumeConcentration", typeof(VolumeConcentration).Assembly))
            {
            }

            /// <summary>
            ///     Creates a new instance of the <see cref="VolumeConcentrationInfo"/> class with the default settings for the VolumeConcentration quantity.
            /// </summary>
            /// <returns>A new instance of the <see cref="VolumeConcentrationInfo"/> class with the default settings.</returns>
            public static VolumeConcentrationInfo CreateDefault()
                => new(nameof(VolumeConcentration), DefaultBaseUnit, GetDefaultMappings(), new(0, DefaultBaseUnit), DefaultBaseDimensions);

            /// <summary>
            ///     Creates a new instance of the <see cref="VolumeConcentrationInfo"/> class with the default settings for the VolumeConcentration quantity and a callback for customizing the default unit mappings.
            /// </summary>
            /// <param name="customizeUnits">
            ///     A callback function for customizing the default unit mappings.
            /// </param>
            /// <returns>
            ///     A new instance of the <see cref="VolumeConcentrationInfo"/> class with the default settings.
            /// </returns>
            public static VolumeConcentrationInfo CreateDefault(Func<IEnumerable<UnitDefinition<VolumeConcentrationUnit>>, IEnumerable<IUnitDefinition<VolumeConcentrationUnit>>> customizeUnits)
                => new(nameof(VolumeConcentration), DefaultBaseUnit, customizeUnits(GetDefaultMappings()), new(0, DefaultBaseUnit), DefaultBaseDimensions);

            /// <summary>
            ///     The <see cref="BaseDimensions" /> for <see cref="VolumeConcentration"/> is .
            /// </summary>
            public static BaseDimensions DefaultBaseDimensions
            {
                [MethodImpl(MethodImplOptions.AggressiveInlining)]
                get;
            } = BaseDimensions.Dimensionless;

            /// <summary>
            ///     The default base unit of VolumeConcentration is DecimalFraction. All conversions, as defined in the <see cref="GetDefaultMappings"/>, go via this value.
            /// </summary>
            public static VolumeConcentrationUnit DefaultBaseUnit
            {
                [MethodImpl(MethodImplOptions.AggressiveInlining)]
                get;
            } = VolumeConcentrationUnit.DecimalFraction;

            /// <summary>
            ///     Retrieves the default mappings for <see cref="VolumeConcentrationUnit"/>.
            /// </summary>
            /// <returns>An <see cref="IEnumerable{T}"/> of <see cref="UnitDefinition{VolumeConcentrationUnit}"/> representing the default unit mappings for VolumeConcentration.</returns>
            public static IEnumerable<UnitDefinition<VolumeConcentrationUnit>> GetDefaultMappings()
            {
                yield return new (VolumeConcentrationUnit.CentiliterPerLiter, "CentiliterPerLiter", "CentilitersPerLiter", BaseUnits.Undefined,
                     100
                );
                yield return new (VolumeConcentrationUnit.CentiliterPerMilliliter, "CentiliterPerMilliliter", "CentilitersPerMilliliter", BaseUnits.Undefined,
                     new QuantityValue(1, 10)
                );
                yield return new (VolumeConcentrationUnit.DeciliterPerLiter, "DeciliterPerLiter", "DecilitersPerLiter", BaseUnits.Undefined,
                     10
                );
                yield return new (VolumeConcentrationUnit.DeciliterPerMilliliter, "DeciliterPerMilliliter", "DecilitersPerMilliliter", BaseUnits.Undefined,
                     new QuantityValue(1, 100)
                );
                yield return new (VolumeConcentrationUnit.DecimalFraction, "DecimalFraction", "DecimalFractions", BaseUnits.Undefined);
                yield return new (VolumeConcentrationUnit.LiterPerLiter, "LiterPerLiter", "LitersPerLiter", BaseUnits.Undefined,
                     1
                );
                yield return new (VolumeConcentrationUnit.LiterPerMilliliter, "LiterPerMilliliter", "LitersPerMilliliter", BaseUnits.Undefined,
                     new QuantityValue(1, 1000)
                );
                yield return new (VolumeConcentrationUnit.MicroliterPerLiter, "MicroliterPerLiter", "MicrolitersPerLiter", BaseUnits.Undefined,
                     1000000
                );
                yield return new (VolumeConcentrationUnit.MicroliterPerMilliliter, "MicroliterPerMilliliter", "MicrolitersPerMilliliter", BaseUnits.Undefined,
                     1000
                );
                yield return new (VolumeConcentrationUnit.MilliliterPerLiter, "MilliliterPerLiter", "MillilitersPerLiter", BaseUnits.Undefined,
                     1000
                );
                yield return new (VolumeConcentrationUnit.MilliliterPerMilliliter, "MilliliterPerMilliliter", "MillilitersPerMilliliter", BaseUnits.Undefined,
                     1
                );
                yield return new (VolumeConcentrationUnit.NanoliterPerLiter, "NanoliterPerLiter", "NanolitersPerLiter", BaseUnits.Undefined,
                     1000000000
                );
                yield return new (VolumeConcentrationUnit.NanoliterPerMilliliter, "NanoliterPerMilliliter", "NanolitersPerMilliliter", BaseUnits.Undefined,
                     1000000
                );
                yield return new (VolumeConcentrationUnit.PartPerBillion, "PartPerBillion", "PartsPerBillion", BaseUnits.Undefined,
                     1000000000
                );
                yield return new (VolumeConcentrationUnit.PartPerMillion, "PartPerMillion", "PartsPerMillion", BaseUnits.Undefined,
                     1000000
                );
                yield return new (VolumeConcentrationUnit.PartPerThousand, "PartPerThousand", "PartsPerThousand", BaseUnits.Undefined,
                     1000
                );
                yield return new (VolumeConcentrationUnit.PartPerTrillion, "PartPerTrillion", "PartsPerTrillion", BaseUnits.Undefined,
                     1000000000000
                );
                yield return new (VolumeConcentrationUnit.Percent, "Percent", "Percent", BaseUnits.Undefined,
                     100
                );
                yield return new (VolumeConcentrationUnit.PicoliterPerLiter, "PicoliterPerLiter", "PicolitersPerLiter", BaseUnits.Undefined,
                     1000000000000
                );
                yield return new (VolumeConcentrationUnit.PicoliterPerMilliliter, "PicoliterPerMilliliter", "PicolitersPerMilliliter", BaseUnits.Undefined,
                     1000000000
                );
            }
        }

        static VolumeConcentration()
        {
            Info = UnitsNetSetup.CreateQuantityInfo(VolumeConcentrationInfo.CreateDefault);
        }

        /// <summary>
        ///     Creates the quantity with the given numeric value and unit.
        /// </summary>
        /// <param name="value">The numeric value to construct this quantity with.</param>
        /// <param name="unit">The unit representation to construct this quantity with.</param>
        public VolumeConcentration(QuantityValue value, VolumeConcentrationUnit unit)
        {
            _value = value;
            _unit = unit;
        }

        #region Static Properties

        /// <summary>
        ///     The <see cref="UnitConverter" /> containing the default generated conversion functions for <see cref="VolumeConcentration" /> instances.
        /// </summary>
        [Obsolete("Replaced by UnitConverter.Default")]
        public static UnitConverter DefaultConversionFunctions
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => UnitConverter.Default;
        }

        /// <inheritdoc cref="IQuantity.QuantityInfo"/>
        public static QuantityInfo<VolumeConcentration, VolumeConcentrationUnit> Info { get; }

        /// <summary>
        ///     The <see cref="BaseDimensions" /> of this quantity.
        /// </summary>
        public static BaseDimensions BaseDimensions
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => Info.BaseDimensions;
        }

        /// <summary>
        ///     The base unit of VolumeConcentration, which is DecimalFraction. All conversions go via this value.
        /// </summary>
        public static VolumeConcentrationUnit BaseUnit
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => Info.BaseUnitInfo.Value;
        }

        /// <summary>
        ///     All units of measurement for the VolumeConcentration quantity.
        /// </summary>
        public static IReadOnlyCollection<VolumeConcentrationUnit> Units
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => Info.Units;
        }

        /// <summary>
        ///     Gets an instance of this quantity with a value of 0 in the base unit DecimalFraction.
        /// </summary>
        public static VolumeConcentration Zero
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => Info.Zero;
        }

        #endregion

        #region Properties

        /// <inheritdoc />
        public QuantityValue Value
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => _value;
        }

        /// <inheritdoc />
        public VolumeConcentrationUnit Unit
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => _unit.GetValueOrDefault(BaseUnit);
        }

        /// <inheritdoc />
        public QuantityInfo<VolumeConcentration, VolumeConcentrationUnit> QuantityInfo
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => Info;
        }

        #region Explicit implementations

        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        UnitKey IQuantity.UnitKey
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => UnitKey.ForUnit(Unit);
        }

#if NETSTANDARD2_0
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        IQuantityInstanceInfo<VolumeConcentration> IQuantityOfType<VolumeConcentration>.QuantityInfo
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => Info;
        }

        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        QuantityInfo<VolumeConcentrationUnit> IQuantity<VolumeConcentrationUnit>.QuantityInfo
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => Info;
        }

        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        QuantityInfo IQuantity.QuantityInfo
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => Info;
        }

        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        Enum IQuantity.Unit
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => Unit;
        }
#endif

        #endregion

        #endregion

        #region Conversion Properties

        /// <inheritdoc cref="IQuantity{VolumeConcentration,VolumeConcentrationUnit}.AsBaseQuantity"/>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public VolumeConcentration AsBaseQuantity()
            => new(this.As(BaseUnit), BaseUnit);

        /// <inheritdoc cref="IQuantity{VolumeConcentration,VolumeConcentrationUnit}.AsBaseValue"/>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public QuantityValue AsBaseValue()
            => this.As(BaseUnit);

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="VolumeConcentrationUnit.CentiliterPerLiter"/>
        /// </summary>
        public QuantityValue CentilitersPerLiter
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(VolumeConcentrationUnit.CentiliterPerLiter);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="VolumeConcentrationUnit.CentiliterPerMilliliter"/>
        /// </summary>
        public QuantityValue CentilitersPerMilliliter
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(VolumeConcentrationUnit.CentiliterPerMilliliter);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="VolumeConcentrationUnit.DeciliterPerLiter"/>
        /// </summary>
        public QuantityValue DecilitersPerLiter
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(VolumeConcentrationUnit.DeciliterPerLiter);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="VolumeConcentrationUnit.DeciliterPerMilliliter"/>
        /// </summary>
        public QuantityValue DecilitersPerMilliliter
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(VolumeConcentrationUnit.DeciliterPerMilliliter);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="VolumeConcentrationUnit.DecimalFraction"/>
        /// </summary>
        public QuantityValue DecimalFractions
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(VolumeConcentrationUnit.DecimalFraction);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="VolumeConcentrationUnit.LiterPerLiter"/>
        /// </summary>
        public QuantityValue LitersPerLiter
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(VolumeConcentrationUnit.LiterPerLiter);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="VolumeConcentrationUnit.LiterPerMilliliter"/>
        /// </summary>
        public QuantityValue LitersPerMilliliter
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(VolumeConcentrationUnit.LiterPerMilliliter);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="VolumeConcentrationUnit.MicroliterPerLiter"/>
        /// </summary>
        public QuantityValue MicrolitersPerLiter
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(VolumeConcentrationUnit.MicroliterPerLiter);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="VolumeConcentrationUnit.MicroliterPerMilliliter"/>
        /// </summary>
        public QuantityValue MicrolitersPerMilliliter
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(VolumeConcentrationUnit.MicroliterPerMilliliter);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="VolumeConcentrationUnit.MilliliterPerLiter"/>
        /// </summary>
        public QuantityValue MillilitersPerLiter
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(VolumeConcentrationUnit.MilliliterPerLiter);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="VolumeConcentrationUnit.MilliliterPerMilliliter"/>
        /// </summary>
        public QuantityValue MillilitersPerMilliliter
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(VolumeConcentrationUnit.MilliliterPerMilliliter);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="VolumeConcentrationUnit.NanoliterPerLiter"/>
        /// </summary>
        public QuantityValue NanolitersPerLiter
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(VolumeConcentrationUnit.NanoliterPerLiter);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="VolumeConcentrationUnit.NanoliterPerMilliliter"/>
        /// </summary>
        public QuantityValue NanolitersPerMilliliter
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(VolumeConcentrationUnit.NanoliterPerMilliliter);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="VolumeConcentrationUnit.PartPerBillion"/>
        /// </summary>
        public QuantityValue PartsPerBillion
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(VolumeConcentrationUnit.PartPerBillion);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="VolumeConcentrationUnit.PartPerMillion"/>
        /// </summary>
        public QuantityValue PartsPerMillion
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(VolumeConcentrationUnit.PartPerMillion);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="VolumeConcentrationUnit.PartPerThousand"/>
        /// </summary>
        public QuantityValue PartsPerThousand
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(VolumeConcentrationUnit.PartPerThousand);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="VolumeConcentrationUnit.PartPerTrillion"/>
        /// </summary>
        public QuantityValue PartsPerTrillion
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(VolumeConcentrationUnit.PartPerTrillion);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="VolumeConcentrationUnit.Percent"/>
        /// </summary>
        public QuantityValue Percent
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(VolumeConcentrationUnit.Percent);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="VolumeConcentrationUnit.PicoliterPerLiter"/>
        /// </summary>
        public QuantityValue PicolitersPerLiter
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(VolumeConcentrationUnit.PicoliterPerLiter);
        }

        /// <summary>
        ///     Gets a <see cref="QuantityValue"/> value of this quantity converted into <see cref="VolumeConcentrationUnit.PicoliterPerMilliliter"/>
        /// </summary>
        public QuantityValue PicolitersPerMilliliter
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.As(VolumeConcentrationUnit.PicoliterPerMilliliter);
        }

        #endregion

        #region Static Methods

        /// <summary>
        ///     Get unit abbreviation string.
        /// </summary>
        /// <param name="unit">Unit to get abbreviation for.</param>
        /// <returns>Unit abbreviation string.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static string GetAbbreviation(VolumeConcentrationUnit unit)
            => GetAbbreviation(unit, null);

        /// <summary>
        ///     Get unit abbreviation string.
        /// </summary>
        /// <param name="unit">Unit to get abbreviation for.</param>
        /// <returns>Unit abbreviation string.</returns>
        /// <param name="provider">Format to use for localization. Defaults to <see cref="CultureInfo.CurrentCulture" /> if null.</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static string GetAbbreviation(VolumeConcentrationUnit unit, IFormatProvider? provider)
            => UnitsNetSetup.Default.UnitAbbreviations.GetDefaultAbbreviation(unit, provider);

        #endregion

        #region Static Factory Methods

        /// <summary>
        ///     Creates a <see cref="VolumeConcentration"/> from <see cref="VolumeConcentrationUnit.CentiliterPerLiter"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static VolumeConcentration FromCentilitersPerLiter(QuantityValue value)
            => new(value, VolumeConcentrationUnit.CentiliterPerLiter);

        /// <summary>
        ///     Creates a <see cref="VolumeConcentration"/> from <see cref="VolumeConcentrationUnit.CentiliterPerMilliliter"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static VolumeConcentration FromCentilitersPerMilliliter(QuantityValue value)
            => new(value, VolumeConcentrationUnit.CentiliterPerMilliliter);

        /// <summary>
        ///     Creates a <see cref="VolumeConcentration"/> from <see cref="VolumeConcentrationUnit.DeciliterPerLiter"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static VolumeConcentration FromDecilitersPerLiter(QuantityValue value)
            => new(value, VolumeConcentrationUnit.DeciliterPerLiter);

        /// <summary>
        ///     Creates a <see cref="VolumeConcentration"/> from <see cref="VolumeConcentrationUnit.DeciliterPerMilliliter"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static VolumeConcentration FromDecilitersPerMilliliter(QuantityValue value)
            => new(value, VolumeConcentrationUnit.DeciliterPerMilliliter);

        /// <summary>
        ///     Creates a <see cref="VolumeConcentration"/> from <see cref="VolumeConcentrationUnit.DecimalFraction"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static VolumeConcentration FromDecimalFractions(QuantityValue value)
            => new(value, VolumeConcentrationUnit.DecimalFraction);

        /// <summary>
        ///     Creates a <see cref="VolumeConcentration"/> from <see cref="VolumeConcentrationUnit.LiterPerLiter"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static VolumeConcentration FromLitersPerLiter(QuantityValue value)
            => new(value, VolumeConcentrationUnit.LiterPerLiter);

        /// <summary>
        ///     Creates a <see cref="VolumeConcentration"/> from <see cref="VolumeConcentrationUnit.LiterPerMilliliter"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static VolumeConcentration FromLitersPerMilliliter(QuantityValue value)
            => new(value, VolumeConcentrationUnit.LiterPerMilliliter);

        /// <summary>
        ///     Creates a <see cref="VolumeConcentration"/> from <see cref="VolumeConcentrationUnit.MicroliterPerLiter"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static VolumeConcentration FromMicrolitersPerLiter(QuantityValue value)
            => new(value, VolumeConcentrationUnit.MicroliterPerLiter);

        /// <summary>
        ///     Creates a <see cref="VolumeConcentration"/> from <see cref="VolumeConcentrationUnit.MicroliterPerMilliliter"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static VolumeConcentration FromMicrolitersPerMilliliter(QuantityValue value)
            => new(value, VolumeConcentrationUnit.MicroliterPerMilliliter);

        /// <summary>
        ///     Creates a <see cref="VolumeConcentration"/> from <see cref="VolumeConcentrationUnit.MilliliterPerLiter"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static VolumeConcentration FromMillilitersPerLiter(QuantityValue value)
            => new(value, VolumeConcentrationUnit.MilliliterPerLiter);

        /// <summary>
        ///     Creates a <see cref="VolumeConcentration"/> from <see cref="VolumeConcentrationUnit.MilliliterPerMilliliter"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static VolumeConcentration FromMillilitersPerMilliliter(QuantityValue value)
            => new(value, VolumeConcentrationUnit.MilliliterPerMilliliter);

        /// <summary>
        ///     Creates a <see cref="VolumeConcentration"/> from <see cref="VolumeConcentrationUnit.NanoliterPerLiter"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static VolumeConcentration FromNanolitersPerLiter(QuantityValue value)
            => new(value, VolumeConcentrationUnit.NanoliterPerLiter);

        /// <summary>
        ///     Creates a <see cref="VolumeConcentration"/> from <see cref="VolumeConcentrationUnit.NanoliterPerMilliliter"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static VolumeConcentration FromNanolitersPerMilliliter(QuantityValue value)
            => new(value, VolumeConcentrationUnit.NanoliterPerMilliliter);

        /// <summary>
        ///     Creates a <see cref="VolumeConcentration"/> from <see cref="VolumeConcentrationUnit.PartPerBillion"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static VolumeConcentration FromPartsPerBillion(QuantityValue value)
            => new(value, VolumeConcentrationUnit.PartPerBillion);

        /// <summary>
        ///     Creates a <see cref="VolumeConcentration"/> from <see cref="VolumeConcentrationUnit.PartPerMillion"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static VolumeConcentration FromPartsPerMillion(QuantityValue value)
            => new(value, VolumeConcentrationUnit.PartPerMillion);

        /// <summary>
        ///     Creates a <see cref="VolumeConcentration"/> from <see cref="VolumeConcentrationUnit.PartPerThousand"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static VolumeConcentration FromPartsPerThousand(QuantityValue value)
            => new(value, VolumeConcentrationUnit.PartPerThousand);

        /// <summary>
        ///     Creates a <see cref="VolumeConcentration"/> from <see cref="VolumeConcentrationUnit.PartPerTrillion"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static VolumeConcentration FromPartsPerTrillion(QuantityValue value)
            => new(value, VolumeConcentrationUnit.PartPerTrillion);

        /// <summary>
        ///     Creates a <see cref="VolumeConcentration"/> from <see cref="VolumeConcentrationUnit.Percent"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static VolumeConcentration FromPercent(QuantityValue value)
            => new(value, VolumeConcentrationUnit.Percent);

        /// <summary>
        ///     Creates a <see cref="VolumeConcentration"/> from <see cref="VolumeConcentrationUnit.PicoliterPerLiter"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static VolumeConcentration FromPicolitersPerLiter(QuantityValue value)
            => new(value, VolumeConcentrationUnit.PicoliterPerLiter);

        /// <summary>
        ///     Creates a <see cref="VolumeConcentration"/> from <see cref="VolumeConcentrationUnit.PicoliterPerMilliliter"/>.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static VolumeConcentration FromPicolitersPerMilliliter(QuantityValue value)
            => new(value, VolumeConcentrationUnit.PicoliterPerMilliliter);

        /// <summary>
        ///     Dynamically convert from value and unit enum <see cref="VolumeConcentrationUnit" /> to <see cref="VolumeConcentration" />.
        /// </summary>
        /// <param name="value">Value to convert from.</param>
        /// <param name="fromUnit">Unit to convert from.</param>
        /// <returns>VolumeConcentration unit value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static VolumeConcentration From(QuantityValue value, VolumeConcentrationUnit fromUnit)
            => new(value, fromUnit);

        #endregion

        #region Static Parse Methods

        /// <summary>
        ///     Parse a string with one or two quantities of the format "&lt;quantity&gt; &lt;unit&gt;".
        /// </summary>
        /// <param name="str">String to parse. Typically in the form: {number} {unit}</param>
        /// <example>
        ///     Length.Parse("5.5 m", CultureInfo.GetCultureInfo("en-US"));
        /// </example>
        /// <exception cref="ArgumentNullException">The value of 'str' cannot be null. </exception>
        /// <exception cref="ArgumentException">
        ///     Expected string to have one or two pairs of quantity and unit in the format
        ///     "&lt;quantity&gt; &lt;unit&gt;". Eg. "5.5 m" or "1ft 2in"
        /// </exception>
        /// <exception cref="AmbiguousUnitParseException">
        ///     More than one unit is represented by the specified unit abbreviation.
        ///     Example: Volume.Parse("1 cup") will throw, because it can refer to any of
        ///     <see cref="VolumeUnit.MetricCup" />, <see cref="VolumeUnit.UsLegalCup" /> and <see cref="VolumeUnit.UsCustomaryCup" />.
        /// </exception>
        /// <exception cref="UnitsNetException">
        ///     If anything else goes wrong, typically due to a bug or unhandled case.
        ///     We wrap exceptions in <see cref="UnitsNetException" /> to allow you to distinguish
        ///     Units.NET exceptions from other exceptions.
        /// </exception>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static VolumeConcentration Parse(string str)
            => Parse(str, null);

        /// <summary>
        ///     Parse a string with one or two quantities of the format "&lt;quantity&gt; &lt;unit&gt;".
        /// </summary>
        /// <param name="str">String to parse. Typically in the form: {number} {unit}</param>
        /// <example>
        ///     Length.Parse("5.5 m", CultureInfo.GetCultureInfo("en-US"));
        /// </example>
        /// <exception cref="ArgumentNullException">The value of 'str' cannot be null. </exception>
        /// <exception cref="ArgumentException">
        ///     Expected string to have one or two pairs of quantity and unit in the format
        ///     "&lt;quantity&gt; &lt;unit&gt;". Eg. "5.5 m" or "1ft 2in"
        /// </exception>
        /// <exception cref="AmbiguousUnitParseException">
        ///     More than one unit is represented by the specified unit abbreviation.
        ///     Example: Volume.Parse("1 cup") will throw, because it can refer to any of
        ///     <see cref="VolumeUnit.MetricCup" />, <see cref="VolumeUnit.UsLegalCup" /> and <see cref="VolumeUnit.UsCustomaryCup" />.
        /// </exception>
        /// <exception cref="UnitsNetException">
        ///     If anything else goes wrong, typically due to a bug or unhandled case.
        ///     We wrap exceptions in <see cref="UnitsNetException" /> to allow you to distinguish
        ///     Units.NET exceptions from other exceptions.
        /// </exception>
        /// <param name="provider">Format to use when parsing number and unit. Defaults to <see cref="CultureInfo.CurrentCulture" /> if null.</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static VolumeConcentration Parse(string str, IFormatProvider? provider)
            => QuantityParser.Default.Parse<VolumeConcentration, VolumeConcentrationUnit>(str, provider, From);

        /// <summary>
        ///     Try to parse a string with one or two quantities of the format "&lt;quantity&gt; &lt;unit&gt;".
        /// </summary>
        /// <param name="str">String to parse. Typically in the form: {number} {unit}</param>
        /// <param name="result">Resulting unit quantity if successful.</param>
        /// <example>
        ///     Length.Parse("5.5 m", CultureInfo.GetCultureInfo("en-US"));
        /// </example>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool TryParse([NotNullWhen(true)]string? str, out VolumeConcentration result)
            => TryParse(str, null, out result);

        /// <summary>
        ///     Try to parse a string with one or two quantities of the format "&lt;quantity&gt; &lt;unit&gt;".
        /// </summary>
        /// <param name="str">String to parse. Typically in the form: {number} {unit}</param>
        /// <param name="result">Resulting unit quantity if successful.</param>
        /// <returns>True if successful, otherwise false.</returns>
        /// <example>
        ///     Length.Parse("5.5 m", CultureInfo.GetCultureInfo("en-US"));
        /// </example>
        /// <param name="provider">Format to use when parsing number and unit. Defaults to <see cref="CultureInfo.CurrentCulture" /> if null.</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool TryParse([NotNullWhen(true)]string? str, IFormatProvider? provider, out VolumeConcentration result)
            => QuantityParser.Default.TryParse<VolumeConcentration, VolumeConcentrationUnit>(str, provider, From, out result);

        /// <summary>
        ///     Parse a unit string.
        /// </summary>
        /// <param name="str">String to parse. Typically in the form: {number} {unit}</param>
        /// <example>
        ///     Length.ParseUnit("m", CultureInfo.GetCultureInfo("en-US"));
        /// </example>
        /// <exception cref="ArgumentNullException">The value of 'str' cannot be null. </exception>
        /// <exception cref="UnitsNetException">Error parsing string.</exception>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static VolumeConcentrationUnit ParseUnit(string str)
            => ParseUnit(str, null);

        /// <summary>
        ///     Parse a unit string.
        /// </summary>
        /// <param name="str">String to parse. Typically in the form: {number} {unit}</param>
        /// <param name="provider">Format to use when parsing the unit. Defaults to <see cref="CultureInfo.CurrentCulture" /> if null.</param>
        /// <example>
        ///     Length.ParseUnit("m", CultureInfo.GetCultureInfo("en-US"));
        /// </example>
        /// <exception cref="ArgumentNullException">The value of 'str' cannot be null. </exception>
        /// <exception cref="UnitsNetException">Error parsing string.</exception>
        public static VolumeConcentrationUnit ParseUnit(string str, IFormatProvider? provider)
            => UnitParser.Default.Parse(str, Info.UnitInfos, provider).Value;

        /// <inheritdoc cref="TryParseUnit(string,IFormatProvider?,out UnitsNet.Units.VolumeConcentrationUnit)"/>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool TryParseUnit([NotNullWhen(true)]string? str, out VolumeConcentrationUnit unit)
            => TryParseUnit(str, null, out unit);

        /// <summary>
        ///     Parse a unit string.
        /// </summary>
        /// <param name="str">String to parse. Typically in the form: {number} {unit}</param>
        /// <param name="unit">The parsed unit if successful.</param>
        /// <returns>True if successful, otherwise false.</returns>
        /// <example>
        ///     Length.TryParseUnit("m", CultureInfo.GetCultureInfo("en-US"));
        /// </example>
        /// <param name="provider">Format to use when parsing the unit. Defaults to <see cref="CultureInfo.CurrentCulture" /> if null.</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool TryParseUnit([NotNullWhen(true)]string? str, IFormatProvider? provider, out VolumeConcentrationUnit unit)
            => UnitParser.Default.TryParse(str, Info, provider, out unit);

        #endregion

        #region Arithmetic Operators

        /// <summary>Negate the value.</summary>
        public static VolumeConcentration operator -(VolumeConcentration right)
            => new(-right.Value, right.Unit);

        /// <summary>Get <see cref="VolumeConcentration"/> from adding two <see cref="VolumeConcentration"/>.</summary>
        public static VolumeConcentration operator +(VolumeConcentration left, VolumeConcentration right)
            => new(left.Value + right.As(left.Unit), left.Unit);

        /// <summary>Get <see cref="VolumeConcentration"/> from subtracting two <see cref="VolumeConcentration"/>.</summary>
        public static VolumeConcentration operator -(VolumeConcentration left, VolumeConcentration right)
            => new(left.Value - right.As(left.Unit), left.Unit);

        /// <summary>Get <see cref="VolumeConcentration"/> from multiplying value and <see cref="VolumeConcentration"/>.</summary>
        public static VolumeConcentration operator *(QuantityValue left, VolumeConcentration right)
            => new(left * right.Value, right.Unit);

        /// <summary>Get <see cref="VolumeConcentration"/> from multiplying value and <see cref="VolumeConcentration"/>.</summary>
        public static VolumeConcentration operator *(VolumeConcentration left, QuantityValue right)
            => new(left.Value * right, left.Unit);

        /// <summary>Get <see cref="VolumeConcentration"/> from dividing <see cref="VolumeConcentration"/> by value.</summary>
        public static VolumeConcentration operator /(VolumeConcentration left, QuantityValue right)
            => new(left.Value / right, left.Unit);

        /// <summary>Get ratio value from dividing <see cref="VolumeConcentration"/> by <see cref="VolumeConcentration"/>.</summary>
        public static QuantityValue operator /(VolumeConcentration left, VolumeConcentration right)
            => left.DecimalFractions / right.DecimalFractions;

        #endregion

        #region Relational Operators

        /// <summary>Get <see cref="MassConcentration"/> from <see cref="VolumeConcentration"/> * <see cref="Density"/>.</summary>
        public static MassConcentration operator *(VolumeConcentration volumeConcentration, Density density)
            => MassConcentration.FromKilogramsPerCubicMeter(volumeConcentration.DecimalFractions * density.KilogramsPerCubicMeter);

        /// <summary>Get <see cref="Molarity"/> from <see cref="VolumeConcentration"/> * <see cref="Molarity"/>.</summary>
        public static Molarity operator *(VolumeConcentration volumeConcentration, Molarity molarity)
            => Molarity.FromMolesPerCubicMeter(volumeConcentration.DecimalFractions * molarity.MolesPerCubicMeter);

        #endregion

        #region Equality / IComparable

        /// <summary>Returns true if less or equal to.</summary>
        public static bool operator <=(VolumeConcentration left, VolumeConcentration right)
            => left.Value <= right.As(left.Unit);

        /// <summary>Returns true if greater than or equal to.</summary>
        public static bool operator >=(VolumeConcentration left, VolumeConcentration right)
            => left.Value >= right.As(left.Unit);

        /// <summary>Returns true if less than.</summary>
        public static bool operator <(VolumeConcentration left, VolumeConcentration right)
            => left.Value < right.As(left.Unit);

        /// <summary>Returns true if greater than.</summary>
        public static bool operator >(VolumeConcentration left, VolumeConcentration right)
            => left.Value > right.As(left.Unit);

        /// <summary>
        ///     Determines whether two <see cref="VolumeConcentration"/> instances are equal.
        /// </summary>
        /// <remarks>
        ///     Equality is evaluated in a unit-aware manner. The right-hand operand is converted to the unit of the left-hand
        ///     operand and then the underlying numeric values are compared.
        ///     This means two quantities with numerically equal values but different units will be considered equal.
        ///     The operator delegates to <see cref="Equals(VolumeConcentration)"/>, which implements this conversion-and-compare logic.
        /// </remarks>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool operator ==(VolumeConcentration left, VolumeConcentration right)
            => left.Equals(right);

        /// <summary>
        ///     Determines whether two <see cref="VolumeConcentration"/> instances are not equal.
        /// </summary>
        /// <remarks>
        ///     This operator is the logical negation of <see cref="operator ==(VolumeConcentration,VolumeConcentration)"/>.
        ///     See that operator (and <see cref="Equals(VolumeConcentration)"/>) for details on how equality is evaluated
        ///     (i.e., by converting one operand to the other's unit and comparing their numeric values).
        /// </remarks>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool operator !=(VolumeConcentration left, VolumeConcentration right)
            => !(left == right);

        /// <inheritdoc />
        /// <summary>
        ///     Determines whether the specified object is equal to the current <see cref="VolumeConcentration"/> instance.
        /// </summary>
        /// <remarks>
        ///     Returns <c>false</c> if <paramref name="obj"/> is <c>null</c> or not a <see cref="VolumeConcentration"/>.
        ///     When <paramref name="obj"/> is a <see cref="VolumeConcentration"/>, this method delegates to
        ///     <see cref="Equals(VolumeConcentration)"/>, which performs a unit-aware comparison by converting the other
        ///     instance to this instance's unit before comparing numeric values.
        /// </remarks>
        public override bool Equals(object? obj)
            => obj is VolumeConcentration otherQuantity && Equals(otherQuantity);

        /// <inheritdoc />
        /// <summary>
        ///     Determines whether the current instance is equal to another <see cref="VolumeConcentration"/> instance.
        /// </summary>
        /// <remarks>
        ///     Comparison is performed by converting <paramref name="other"/> to this instance's unit and then comparing the underlying numeric values.
        ///     This makes two quantities equal even when their units differ, provided the converted numeric values are equal.
        /// </remarks>
        public bool Equals(VolumeConcentration other)
            => _value.Equals(other.As(Unit));

        /// <summary>
        ///     Returns the hash code for this instance.
        /// </summary>
        /// <returns>A hash code for the current VolumeConcentration.</returns>
        public override int GetHashCode()
            => Comparison.GetHashCode(typeof(VolumeConcentration), this.As(BaseUnit));

        /// <inheritdoc  cref="CompareTo(VolumeConcentration)" />
        /// <param name="obj">An object to compare with this instance.</param>
        /// <exception cref="T:System.ArgumentException">
        ///    <paramref name="obj" /> is not the same type as this instance.
        /// </exception>
        public int CompareTo(object? obj)
        {
            if (obj is not VolumeConcentration otherQuantity)
                throw obj is null ? new ArgumentNullException(nameof(obj)) : ExceptionHelper.CreateArgumentException<VolumeConcentration>(obj, nameof(obj));

            return CompareTo(otherQuantity);
        }

        /// <summary>
        ///     Compares the current <see cref="VolumeConcentration"/> with another <see cref="VolumeConcentration"/> and returns an integer that indicates
        ///     whether the current instance precedes, follows, or occurs in the same position in the sort order as the other quantity, when converted to the same unit.
        /// </summary>
        /// <param name="other">A quantity to compare with this instance.</param>
        /// <returns>A value that indicates the relative order of the quantities being compared. The return value has these meanings:
        ///     <list type="table">
        ///         <listheader><term> Value</term><description> Meaning</description></listheader>
        ///         <item><term> Less than zero</term><description> This instance precedes <paramref name="other" /> in the sort order.</description></item>
        ///         <item><term> Zero</term><description> This instance occurs in the same position in the sort order as <paramref name="other" />.</description></item>
        ///         <item><term> Greater than zero</term><description> This instance follows <paramref name="other" /> in the sort order.</description></item>
        ///     </list>
        /// </returns>
        public int CompareTo(VolumeConcentration other)
            => _value.CompareTo(other.As(Unit));

        #endregion

        #region ToString Methods

        /// <summary>
        ///     Gets the default string representation of value and unit.
        /// </summary>
        /// <returns>String representation.</returns>
        public override string ToString()
            => ToString(null, null);

        /// <inheritdoc cref="QuantityFormatter.Format{TQuantity}(TQuantity, string, IFormatProvider)"/>
        /// <summary>
        /// Gets the string representation of this instance in the specified format string using the specified format provider, or <see cref="CultureInfo.CurrentCulture" /> if null.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public string ToString(
            [StringSyntax(StringSyntaxAttribute.NumericFormat)] string? format,
            IFormatProvider? provider)
            => QuantityFormatter.Default.Format(this, format, provider);

        #endregion

    }
}
